/*
 * Internal module API header file.
 *
 * Generated by SIP 4.19.8
 *
 * Copyright (c) 2016 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of PyQt4.
 * 
 * This file may be used under the terms of the GNU General Public License
 * version 3.0 as published by the Free Software Foundation and appearing in
 * the file LICENSE included in the packaging of this file.  Please review the
 * following information to ensure the GNU General Public License version 3.0
 * requirements will be met: http://www.gnu.org/copyleft/gpl.html.
 * 
 * If you do not wish to use this file under the terms of the GPL version 3.0
 * then you may purchase a commercial license.  For more information contact
 * info@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#ifndef _QtSqlAPI_H
#define _QtSqlAPI_H

#include <sip.h>

#include <QMetaType>
#include <QThread>

/* These are the qualifiers that are enabled. */
#define SIP_FEATURE_PyQt_Process
#define SIP_FEATURE_PyQt_NotBootstrapped
#define SIP_FEATURE_PyQt_Deprecated_5_0
#define SIP_FEATURE_PyQt_NoOpenGLES
#define SIP_FEATURE_PyQt_RawFont
#define SIP_FEATURE_PyQt_SystemTrayIcon
#define SIP_FEATURE_PyQt_PrintPreviewDialog
#define SIP_FEATURE_PyQt_PrintPreviewWidget
#define SIP_FEATURE_PyQt_Printer
#define SIP_FEATURE_PyQt_PrintDialog
#define SIP_FEATURE_Py_v3
#define SIP_FEATURE_PyQt_qreal_double
#define SIP_FEATURE_PyQt_SizeGrip
#define SIP_FEATURE_PyQt_OpenSSL
#define SIP_FEATURE_Py_DateTime
#define SIP_FEATURE_PyQt_NoQtPrintRangeBug
#define SIP_FEATURE_PyQt_WhatsThis
#define SIP_FEATURE_PyQt_ToolTip
#define SIP_FEATURE_PyQt_StatusTip
#define SIP_FEATURE_PyQt_SessionManager
#define SIP_FEATURE_PyQt_Accessibility
#define SIP_PLATFORM_WS_X11
#define SIP_TIMELINE_Qt_5_0_0


/*
 * Convenient names to refer to various strings defined in this module.
 * Only the class names are part of the public API.
 */
#define sipNameNr_QSqlRelationalTableModel__JoinMode 0
#define sipName_QSqlRelationalTableModel__JoinMode &sipStrings_QtSql[0]
#define sipNameNr_QSqlDriver__NotificationSource 35
#define sipName_QSqlDriver__NotificationSource &sipStrings_QtSql[35]
#define sipNameNr_QSql__NumericalPrecisionPolicy 66
#define sipName_QSql__NumericalPrecisionPolicy &sipStrings_QtSql[66]
#define sipNameNr_QSqlQuery__BatchExecutionMode 97
#define sipName_QSqlQuery__BatchExecutionMode &sipStrings_QtSql[97]
#define sipNameNr_QSqlTableModel__EditStrategy 127
#define sipName_QSqlTableModel__EditStrategy &sipStrings_QtSql[127]
#define sipNameNr_PyQt4_QtCore_pyqtWrapperType 156
#define sipName_PyQt4_QtCore_pyqtWrapperType &sipStrings_QtSql[156]
#define sipNameNr_unsubscribeFromNotification 185
#define sipName_unsubscribeFromNotification &sipStrings_QtSql[185]
#define sipNameNr_setNumericalPrecisionPolicy 213
#define sipName_setNumericalPrecisionPolicy &sipStrings_QtSql[213]
#define sipNameNr_QSqlDriver__IdentifierType 241
#define sipName_QSqlDriver__IdentifierType &sipStrings_QtSql[241]
#define sipNameNr_QSqlResult__BindingSyntax 268
#define sipName_QSqlResult__BindingSyntax &sipStrings_QtSql[268]
#define sipNameNr_QSqlField__RequiredStatus 294
#define sipName_QSqlField__RequiredStatus &sipStrings_QtSql[294]
#define sipNameNr_subscribedToNotifications 320
#define sipName_subscribedToNotifications &sipStrings_QtSql[320]
#define sipNameNr_QSqlDriver__StatementType 346
#define sipName_QSqlDriver__StatementType &sipStrings_QtSql[346]
#define sipNameNr_QSqlDriver__DriverFeature 372
#define sipName_QSqlDriver__DriverFeature &sipStrings_QtSql[372]
#define sipNameNr_QSqlRelationalTableModel 398
#define sipName_QSqlRelationalTableModel &sipStrings_QtSql[398]
#define sipNameNr_numericalPrecisionPolicy 423
#define sipName_numericalPrecisionPolicy &sipStrings_QtSql[423]
#define sipNameNr_NumericalPrecisionPolicy 72
#define sipName_NumericalPrecisionPolicy &sipStrings_QtSql[72]
#define sipNameNr_subscribeToNotification 448
#define sipName_subscribeToNotification &sipStrings_QtSql[448]
#define sipNameNr_QSqlRelationalDelegate 472
#define sipName_QSqlRelationalDelegate &sipStrings_QtSql[472]
#define sipNameNr_PositionalPlaceholders 495
#define sipName_PositionalPlaceholders &sipStrings_QtSql[495]
#define sipNameNr_QSqlDriverCreatorBase 518
#define sipName_QSqlDriverCreatorBase &sipStrings_QtSql[518]
#define sipNameNr_QSqlError__ErrorType 540
#define sipName_QSqlError__ErrorType &sipStrings_QtSql[540]
#define sipNameNr_updateEditorGeometry 561
#define sipName_updateEditorGeometry &sipStrings_QtSql[561]
#define sipNameNr_supportedDragActions 582
#define sipName_supportedDragActions &sipStrings_QtSql[582]
#define sipNameNr_supportedDropActions 603
#define sipName_supportedDropActions &sipStrings_QtSql[603]
#define sipNameNr_isIdentifierEscaped 624
#define sipName_isIdentifierEscaped &sipStrings_QtSql[624]
#define sipNameNr_rollbackTransaction 644
#define sipName_rollbackTransaction &sipStrings_QtSql[644]
#define sipNameNr_LowPrecisionNumbers 664
#define sipName_LowPrecisionNumbers &sipStrings_QtSql[664]
#define sipNameNr_QSql__ParamTypeFlag 684
#define sipName_QSql__ParamTypeFlag &sipStrings_QtSql[684]
#define sipNameNr_defaultButtonNumber 704
#define sipName_defaultButtonNumber &sipStrings_QtSql[704]
#define sipNameNr_deleteRowFromTable 724
#define sipName_deleteRowFromTable &sipStrings_QtSql[724]
#define sipNameNr_insertRowIntoTable 743
#define sipName_insertRowIntoTable &sipStrings_QtSql[743]
#define sipNameNr_BatchExecutionMode 108
#define sipName_BatchExecutionMode &sipStrings_QtSql[108]
#define sipNameNr_NotificationSource 47
#define sipName_NotificationSource &sipStrings_QtSql[47]
#define sipNameNr_MultipleResultSets 762
#define sipName_MultipleResultSets &sipStrings_QtSql[762]
#define sipNameNr_EventNotifications 781
#define sipName_EventNotifications &sipStrings_QtSql[781]
#define sipNameNr_LowPrecisionDouble 800
#define sipName_LowPrecisionDouble &sipStrings_QtSql[800]
#define sipNameNr_escapeButtonNumber 819
#define sipName_escapeButtonNumber &sipStrings_QtSql[819]
#define sipNameNr_beginRemoveColumns 838
#define sipName_beginRemoveColumns &sipStrings_QtSql[838]
#define sipNameNr_beginInsertColumns 857
#define sipName_beginInsertColumns &sipStrings_QtSql[857]
#define sipNameNr_876 876
#define sipName_876 &sipStrings_QtSql[876]
#define sipNameNr_PositionalBinding 894
#define sipName_PositionalBinding &sipStrings_QtSql[894]
#define sipNameNr_setRequiredStatus 912
#define sipName_setRequiredStatus &sipStrings_QtSql[912]
#define sipNameNr_commitTransaction 930
#define sipName_commitTransaction &sipStrings_QtSql[930]
#define sipNameNr_NamedPlaceholders 948
#define sipName_NamedPlaceholders &sipStrings_QtSql[948]
#define sipNameNr_isDriverAvailable 966
#define sipName_isDriverAvailable &sipStrings_QtSql[966]
#define sipNameNr_registerSqlDriver 984
#define sipName_registerSqlDriver &sipStrings_QtSql[984]
#define sipNameNr_setConnectOptions 1002
#define sipName_setConnectOptions &sipStrings_QtSql[1002]
#define sipNameNr_LowPrecisionInt64 1020
#define sipName_LowPrecisionInt64 &sipStrings_QtSql[1020]
#define sipNameNr_LowPrecisionInt32 1038
#define sipName_LowPrecisionInt32 &sipStrings_QtSql[1038]
#define sipNameNr_sip_simplewrapper 1056
#define sipName_sip_simplewrapper &sipStrings_QtSql[1056]
#define sipNameNr_updateRowInTable 1074
#define sipName_updateRowInTable &sipStrings_QtSql[1074]
#define sipNameNr_TransactionError 1091
#define sipName_TransactionError &sipStrings_QtSql[1091]
#define sipNameNr_escapeIdentifier 1108
#define sipName_escapeIdentifier &sipStrings_QtSql[1108]
#define sipNameNr_beginTransaction 1125
#define sipName_beginTransaction &sipStrings_QtSql[1125]
#define sipNameNr_disconnectNotify 1142
#define sipName_disconnectNotify &sipStrings_QtSql[1142]
#define sipNameNr_endRemoveColumns 1159
#define sipName_endRemoveColumns &sipStrings_QtSql[1159]
#define sipNameNr_endInsertColumns 1176
#define sipName_endInsertColumns &sipStrings_QtSql[1176]
#define sipNameNr_setEditStrategy 1193
#define sipName_setEditStrategy &sipStrings_QtSql[1193]
#define sipNameNr_boundValueCount 1209
#define sipName_boundValueCount &sipStrings_QtSql[1209]
#define sipNameNr_selectStatement 1225
#define sipName_selectStatement &sipStrings_QtSql[1225]
#define sipNameNr_numRowsAffected 1241
#define sipName_numRowsAffected &sipStrings_QtSql[1241]
#define sipNameNr_ValuesAsColumns 1257
#define sipName_ValuesAsColumns &sipStrings_QtSql[1257]
#define sipNameNr_setDefaultValue 1273
#define sipName_setDefaultValue &sipStrings_QtSql[1273]
#define sipNameNr_setDatabaseText 1289
#define sipName_setDatabaseText &sipStrings_QtSql[1289]
#define sipNameNr_ConnectionError 1305
#define sipName_ConnectionError &sipStrings_QtSql[1305]
#define sipNameNr_stripDelimiters 1321
#define sipName_stripDelimiters &sipStrings_QtSql[1321]
#define sipNameNr_DeleteStatement 1337
#define sipName_DeleteStatement &sipStrings_QtSql[1337]
#define sipNameNr_InsertStatement 1353
#define sipName_InsertStatement &sipStrings_QtSql[1353]
#define sipNameNr_UpdateStatement 1369
#define sipName_UpdateStatement &sipStrings_QtSql[1369]
#define sipNameNr_SelectStatement 1385
#define sipName_SelectStatement &sipStrings_QtSql[1385]
#define sipNameNr_BatchOperations 1401
#define sipName_BatchOperations &sipStrings_QtSql[1401]
#define sipNameNr_PreparedQueries 1417
#define sipName_PreparedQueries &sipStrings_QtSql[1417]
#define sipNameNr_connectionNames 1433
#define sipName_connectionNames &sipStrings_QtSql[1433]
#define sipNameNr_setDatabaseName 1449
#define sipName_setDatabaseName &sipStrings_QtSql[1449]
#define sipNameNr_QSql__TableType 1465
#define sipName_QSql__TableType &sipStrings_QtSql[1465]
#define sipNameNr_QSql__ParamType 1481
#define sipName_QSql__ParamType &sipStrings_QtSql[1481]
#define sipNameNr_aspectRatioMode 1497
#define sipName_aspectRatioMode &sipStrings_QtSql[1497]
#define sipNameNr_deviceTransform 1513
#define sipName_deviceTransform &sipStrings_QtSql[1513]
#define sipNameNr_canDropMimeData 1529
#define sipName_canDropMimeData &sipStrings_QtSql[1529]
#define sipNameNr_beginResetModel 1545
#define sipName_beginResetModel &sipStrings_QtSql[1545]
#define sipNameNr_beginRemoveRows 1561
#define sipName_beginRemoveRows &sipStrings_QtSql[1561]
#define sipNameNr_beginInsertRows 1577
#define sipName_beginInsertRows &sipStrings_QtSql[1577]
#define sipNameNr_OnManualSubmit 1593
#define sipName_OnManualSubmit &sipStrings_QtSql[1593]
#define sipNameNr_boundValueName 1608
#define sipName_boundValueName &sipStrings_QtSql[1608]
#define sipNameNr_QSqlTableModel 1623
#define sipName_QSqlTableModel &sipStrings_QtSql[1623]
#define sipNameNr_QSqlQueryModel 1638
#define sipName_QSqlQueryModel &sipStrings_QtSql[1638]
#define sipNameNr_setForwardOnly 1653
#define sipName_setForwardOnly &sipStrings_QtSql[1653]
#define sipNameNr_requiredStatus 1668
#define sipName_requiredStatus &sipStrings_QtSql[1668]
#define sipNameNr_RequiredStatus 305
#define sipName_RequiredStatus &sipStrings_QtSql[305]
#define sipNameNr_StatementError 1683
#define sipName_StatementError &sipStrings_QtSql[1683]
#define sipNameNr_IdentifierType 253
#define sipName_IdentifierType &sipStrings_QtSql[253]
#define sipNameNr_WhereStatement 1698
#define sipName_WhereStatement &sipStrings_QtSql[1698]
#define sipNameNr_removeDatabase 1713
#define sipName_removeDatabase &sipStrings_QtSql[1713]
#define sipNameNr_connectionName 1728
#define sipName_connectionName &sipStrings_QtSql[1728]
#define sipNameNr_connectOptions 1743
#define sipName_connectOptions &sipStrings_QtSql[1743]
#define sipNameNr_BeforeFirstRow 1758
#define sipName_BeforeFirstRow &sipStrings_QtSql[1758]
#define sipNameNr_QSql__Location 1773
#define sipName_QSql__Location &sipStrings_QtSql[1773]
#define sipNameNr_drawDecoration 1788
#define sipName_drawDecoration &sipStrings_QtSql[1788]
#define sipNameNr_selectedFilter 1803
#define sipName_selectedFilter &sipStrings_QtSql[1803]
#define sipNameNr_disambiguation 1818
#define sipName_disambiguation &sipStrings_QtSql[1818]
#define sipNameNr_setPrimaryKey 1833
#define sipName_setPrimaryKey &sipStrings_QtSql[1833]
#define sipNameNr_OnFieldChange 1847
#define sipName_OnFieldChange &sipStrings_QtSql[1847]
#define sipNameNr_fetchPrevious 1861
#define sipName_fetchPrevious &sipStrings_QtSql[1861]
#define sipNameNr_bindingSyntax 1875
#define sipName_bindingSyntax &sipStrings_QtSql[1875]
#define sipNameNr_bindValueType 1889
#define sipName_bindValueType &sipStrings_QtSql[1889]
#define sipNameNr_BindingSyntax 280
#define sipName_BindingSyntax &sipStrings_QtSql[280]
#define sipNameNr_orderByClause 1903
#define sipName_orderByClause &sipStrings_QtSql[1903]
#define sipNameNr_relationModel 1917
#define sipName_relationModel &sipStrings_QtSql[1917]
#define sipNameNr_displayColumn 1931
#define sipName_displayColumn &sipStrings_QtSql[1931]
#define sipNameNr_executedQuery 1945
#define sipName_executedQuery &sipStrings_QtSql[1945]
#define sipNameNr_isForwardOnly 1959
#define sipName_isForwardOnly &sipStrings_QtSql[1959]
#define sipNameNr_setDescending 1973
#define sipName_setDescending &sipStrings_QtSql[1973]
#define sipNameNr_setCursorName 1987
#define sipName_setCursorName &sipStrings_QtSql[1987]
#define sipNameNr_setDriverText 2001
#define sipName_setDriverText &sipStrings_QtSql[2001]
#define sipNameNr_UnknownSource 2015
#define sipName_UnknownSource &sipStrings_QtSql[2015]
#define sipNameNr_StatementType 358
#define sipName_StatementType &sipStrings_QtSql[358]
#define sipNameNr_SimpleLocking 2029
#define sipName_SimpleLocking &sipStrings_QtSql[2029]
#define sipNameNr_DriverFeature 384
#define sipName_DriverFeature &sipStrings_QtSql[384]
#define sipNameNr_cloneDatabase 2043
#define sipName_cloneDatabase &sipStrings_QtSql[2043]
#define sipNameNr_HighPrecision 2057
#define sipName_HighPrecision &sipStrings_QtSql[2057]
#define sipNameNr_ParamTypeFlag 690
#define sipName_ParamTypeFlag &sipStrings_QtSql[690]
#define sipNameNr_transformMode 2071
#define sipName_transformMode &sipStrings_QtSql[2071]
#define sipNameNr_destroyEditor 2085
#define sipName_destroyEditor &sipStrings_QtSql[2085]
#define sipNameNr_setEditorData 2099
#define sipName_setEditorData &sipStrings_QtSql[2099]
#define sipNameNr_connectNotify 1145
#define sipName_connectNotify &sipStrings_QtSql[1145]
#define sipNameNr_endResetModel 2113
#define sipName_endResetModel &sipStrings_QtSql[2113]
#define sipNameNr_endRemoveRows 2127
#define sipName_endRemoveRows &sipStrings_QtSql[2127]
#define sipNameNr_endInsertRows 2141
#define sipName_endInsertRows &sipStrings_QtSql[2141]
#define sipNameNr_removeColumns 2155
#define sipName_removeColumns &sipStrings_QtSql[2155]
#define sipNameNr_insertColumns 2169
#define sipName_insertColumns &sipStrings_QtSql[2169]
#define sipNameNr_setHeaderData 2183
#define sipName_setHeaderData &sipStrings_QtSql[2183]
#define sipNameNr_beforeDelete 2197
#define sipName_beforeDelete &sipStrings_QtSql[2197]
#define sipNameNr_beforeUpdate 2210
#define sipName_beforeUpdate &sipStrings_QtSql[2210]
#define sipNameNr_beforeInsert 2223
#define sipName_beforeInsert &sipStrings_QtSql[2223]
#define sipNameNr_insertRecord 2236
#define sipName_insertRecord &sipStrings_QtSql[2236]
#define sipNameNr_editStrategy 2249
#define sipName_editStrategy &sipStrings_QtSql[2249]
#define sipNameNr_EditStrategy 143
#define sipName_EditStrategy &sipStrings_QtSql[143]
#define sipNameNr_hasOutValues 2262
#define sipName_hasOutValues &sipStrings_QtSql[2262]
#define sipNameNr_NamedBinding 2275
#define sipName_NamedBinding &sipStrings_QtSql[2275]
#define sipNameNr_QSqlRelation 2288
#define sipName_QSqlRelation &sipStrings_QtSql[2288]
#define sipNameNr_indexInQuery 2301
#define sipName_indexInQuery &sipStrings_QtSql[2301]
#define sipNameNr_lastInsertId 2314
#define sipName_lastInsertId &sipStrings_QtSql[2314]
#define sipNameNr_addBindValue 2327
#define sipName_addBindValue &sipStrings_QtSql[2327]
#define sipNameNr_ValuesAsRows 2340
#define sipName_ValuesAsRows &sipStrings_QtSql[2340]
#define sipNameNr_isDescending 2353
#define sipName_isDescending &sipStrings_QtSql[2353]
#define sipNameNr_setAutoValue 2366
#define sipName_setAutoValue &sipStrings_QtSql[2366]
#define sipNameNr_setGenerated 2379
#define sipName_setGenerated &sipStrings_QtSql[2379]
#define sipNameNr_setPrecision 2392
#define sipName_setPrecision &sipStrings_QtSql[2392]
#define sipNameNr_databaseText 2405
#define sipName_databaseText &sipStrings_QtSql[2405]
#define sipNameNr_notification 2418
#define sipName_notification &sipStrings_QtSql[2418]
#define sipNameNr_setLastError 2431
#define sipName_setLastError &sipStrings_QtSql[2431]
#define sipNameNr_setOpenError 2444
#define sipName_setOpenError &sipStrings_QtSql[2444]
#define sipNameNr_createResult 2457
#define sipName_createResult &sipStrings_QtSql[2457]
#define sipNameNr_sqlStatement 2470
#define sipName_sqlStatement &sipStrings_QtSql[2470]
#define sipNameNr_LastInsertId 2483
#define sipName_LastInsertId &sipStrings_QtSql[2483]
#define sipNameNr_Transactions 2496
#define sipName_Transactions &sipStrings_QtSql[2496]
#define sipNameNr_databaseName 2509
#define sipName_databaseName &sipStrings_QtSql[2509]
#define sipNameNr_primaryIndex 2522
#define sipName_primaryIndex &sipStrings_QtSql[2522]
#define sipNameNr_QSqlDatabase 2535
#define sipName_QSqlDatabase &sipStrings_QtSql[2535]
#define sipNameNr_SystemTables 2548
#define sipName_SystemTables &sipStrings_QtSql[2548]
#define sipNameNr_AfterLastRow 2561
#define sipName_AfterLastRow &sipStrings_QtSql[2561]
#define sipNameNr_sourceRegion 2574
#define sipName_sourceRegion &sipStrings_QtSql[2574]
#define sipNameNr_targetOffset 2587
#define sipName_targetOffset &sipStrings_QtSql[2587]
#define sipNameNr_createObject 2600
#define sipName_createObject &sipStrings_QtSql[2600]
#define sipNameNr_boundingRect 2613
#define sipName_boundingRect &sipStrings_QtSql[2613]
#define sipNameNr_midLineWidth 2626
#define sipName_midLineWidth &sipStrings_QtSql[2626]
#define sipNameNr_setModelData 2639
#define sipName_setModelData &sipStrings_QtSql[2639]
#define sipNameNr_createEditor 2652
#define sipName_createEditor &sipStrings_QtSql[2652]
#define sipNameNr_defaultValue 2665
#define sipName_defaultValue &sipStrings_QtSql[2665]
#define sipNameNr_UnknownError 2678
#define sipName_UnknownError &sipStrings_QtSql[2678]
#define sipNameNr_canFetchMore 2691
#define sipName_canFetchMore &sipStrings_QtSql[2691]
#define sipNameNr_dropMimeData 2704
#define sipName_dropMimeData &sipStrings_QtSql[2704]
#define sipNameNr_primeInsert 2717
#define sipName_primeInsert &sipStrings_QtSql[2717]
#define sipNameNr_OnRowChange 2729
#define sipName_OnRowChange &sipStrings_QtSql[2729]
#define sipNameNr_savePrepare 2741
#define sipName_savePrepare &sipStrings_QtSql[2741]
#define sipNameNr_setJoinMode 2753
#define sipName_setJoinMode &sipStrings_QtSql[2753]
#define sipNameNr_setRelation 2765
#define sipName_setRelation &sipStrings_QtSql[2765]
#define sipNameNr_indexColumn 2777
#define sipName_indexColumn &sipStrings_QtSql[2777]
#define sipNameNr_clearValues 2789
#define sipName_clearValues &sipStrings_QtSql[2789]
#define sipNameNr_queryChange 2801
#define sipName_queryChange &sipStrings_QtSql[2801]
#define sipNameNr_boundValues 2813
#define sipName_boundValues &sipStrings_QtSql[2813]
#define sipNameNr_isGenerated 2825
#define sipName_isGenerated &sipStrings_QtSql[2825]
#define sipNameNr_setRequired 2837
#define sipName_setRequired &sipStrings_QtSql[2837]
#define sipNameNr_isAutoValue 2849
#define sipName_isAutoValue &sipStrings_QtSql[2849]
#define sipNameNr_OtherSource 2861
#define sipName_OtherSource &sipStrings_QtSql[2861]
#define sipNameNr_formatValue 2873
#define sipName_formatValue &sipStrings_QtSql[2873]
#define sipNameNr_trimStrings 2885
#define sipName_trimStrings &sipStrings_QtSql[2885]
#define sipNameNr_FinishQuery 2897
#define sipName_FinishQuery &sipStrings_QtSql[2897]
#define sipNameNr_addDatabase 2909
#define sipName_addDatabase &sipStrings_QtSql[2909]
#define sipNameNr_setHostName 2921
#define sipName_setHostName &sipStrings_QtSql[2921]
#define sipNameNr_transaction 2933
#define sipName_transaction &sipStrings_QtSql[2933]
#define sipNameNr_isOpenError 2945
#define sipName_isOpenError &sipStrings_QtSql[2945]
#define sipNameNr_button2Text 2957
#define sipName_button2Text &sipStrings_QtSql[2957]
#define sipNameNr_button1Text 2969
#define sipName_button1Text &sipStrings_QtSql[2969]
#define sipNameNr_drawDisplay 2981
#define sipName_drawDisplay &sipStrings_QtSql[2981]
#define sipNameNr_setReadOnly 2993
#define sipName_setReadOnly &sipStrings_QtSql[2993]
#define sipNameNr_editorEvent 3005
#define sipName_editorEvent &sipStrings_QtSql[3005]
#define sipNameNr_setPassword 3017
#define sipName_setPassword &sipStrings_QtSql[3017]
#define sipNameNr_setUserName 3029
#define sipName_setUserName &sipStrings_QtSql[3029]
#define sipNameNr_customEvent 3041
#define sipName_customEvent &sipStrings_QtSql[3041]
#define sipNameNr_eventFilter 3053
#define sipName_eventFilter &sipStrings_QtSql[3053]
#define sipNameNr_moveColumns 845
#define sipName_moveColumns &sipStrings_QtSql[845]
#define sipNameNr_setItemData 3065
#define sipName_setItemData &sipStrings_QtSql[3065]
#define sipNameNr_hasChildren 3077
#define sipName_hasChildren &sipStrings_QtSql[3077]
#define sipNameNr_columnCount 3089
#define sipName_columnCount &sipStrings_QtSql[3089]
#define sipNameNr_PyQt4_QtSql 3101
#define sipName_PyQt4_QtSql &sipStrings_QtSql[3101]
#define sipNameNr_fieldIndex 3113
#define sipName_fieldIndex &sipStrings_QtSql[3113]
#define sipNameNr_primaryKey 3124
#define sipName_primaryKey &sipStrings_QtSql[3124]
#define sipNameNr_fetchFirst 3135
#define sipName_fetchFirst &sipStrings_QtSql[3135]
#define sipNameNr_QSqlResult 3146
#define sipName_QSqlResult &sipStrings_QtSql[3146]
#define sipNameNr_nextResult 3157
#define sipName_nextResult &sipStrings_QtSql[3157]
#define sipNameNr_boundValue 3168
#define sipName_boundValue &sipStrings_QtSql[3168]
#define sipNameNr_cursorName 3179
#define sipName_cursorName &sipStrings_QtSql[3179]
#define sipNameNr_QSqlRecord 3190
#define sipName_QSqlRecord &sipStrings_QtSql[3190]
#define sipNameNr_setSqlType 3201
#define sipName_setSqlType &sipStrings_QtSql[3201]
#define sipNameNr_driverText 3212
#define sipName_driverText &sipStrings_QtSql[3212]
#define sipNameNr_SelfSource 3223
#define sipName_SelfSource &sipStrings_QtSql[3223]
#define sipNameNr_QSqlDriver 3234
#define sipName_QSqlDriver &sipStrings_QtSql[3234]
#define sipNameNr_driverName 3245
#define sipName_driverName &sipStrings_QtSql[3245]
#define sipNameNr_hasFeature 3256
#define sipName_hasFeature &sipStrings_QtSql[3256]
#define sipNameNr_isReadOnly 3267
#define sipName_isReadOnly &sipStrings_QtSql[3267]
#define sipNameNr_fieldwidth 3278
#define sipName_fieldwidth &sipStrings_QtSql[3278]
#define sipNameNr_fieldWidth 3289
#define sipName_fieldWidth &sipStrings_QtSql[3289]
#define sipNameNr_childEvent 3300
#define sipName_childEvent &sipStrings_QtSql[3300]
#define sipNameNr_timerEvent 3311
#define sipName_timerEvent &sipStrings_QtSql[3311]
#define sipNameNr_removeRows 3322
#define sipName_removeRows &sipStrings_QtSql[3322]
#define sipNameNr_insertRows 3333
#define sipName_insertRows &sipStrings_QtSql[3333]
#define sipNameNr_headerData 3344
#define sipName_headerData &sipStrings_QtSql[3344]
#define sipNameNr___invert__ 3355
#define sipName___invert__ &sipStrings_QtSql[3355]
#define sipNameNr_revertAll 3366
#define sipName_revertAll &sipStrings_QtSql[3366]
#define sipNameNr_submitAll 3376
#define sipName_submitAll &sipStrings_QtSql[3376]
#define sipNameNr_setRecord 3386
#define sipName_setRecord &sipStrings_QtSql[3386]
#define sipNameNr_fetchLast 3396
#define sipName_fetchLast &sipStrings_QtSql[3396]
#define sipNameNr_fetchNext 3406
#define sipName_fetchNext &sipStrings_QtSql[3406]
#define sipNameNr_setSelect 3416
#define sipName_setSelect &sipStrings_QtSql[3416]
#define sipNameNr_InnerJoin 3426
#define sipName_InnerJoin &sipStrings_QtSql[3426]
#define sipNameNr_revertRow 3436
#define sipName_revertRow &sipStrings_QtSql[3436]
#define sipNameNr_bindValue 3446
#define sipName_bindValue &sipStrings_QtSql[3446]
#define sipNameNr_execBatch 3456
#define sipName_execBatch &sipStrings_QtSql[3456]
#define sipNameNr_lastQuery 3466
#define sipName_lastQuery &sipStrings_QtSql[3466]
#define sipNameNr_QSqlQuery 3476
#define sipName_QSqlQuery &sipStrings_QtSql[3476]
#define sipNameNr_QSqlIndex 3486
#define sipName_QSqlIndex &sipStrings_QtSql[3486]
#define sipNameNr_fieldName 3496
#define sipName_fieldName &sipStrings_QtSql[3496]
#define sipNameNr_QSqlField 3506
#define sipName_QSqlField &sipStrings_QtSql[3506]
#define sipNameNr_setNumber 3516
#define sipName_setNumber &sipStrings_QtSql[3516]
#define sipNameNr_ErrorType 551
#define sipName_ErrorType &sipStrings_QtSql[551]
#define sipNameNr_QSqlError 3526
#define sipName_QSqlError &sipStrings_QtSql[3526]
#define sipNameNr_tableName 3536
#define sipName_tableName &sipStrings_QtSql[3536]
#define sipNameNr_TableName 3546
#define sipName_TableName &sipStrings_QtSql[3546]
#define sipNameNr_FieldName 3556
#define sipName_FieldName &sipStrings_QtSql[3556]
#define sipNameNr_QuerySize 3566
#define sipName_QuerySize &sipStrings_QtSql[3566]
#define sipNameNr_lastError 3576
#define sipName_lastError &sipStrings_QtSql[3576]
#define sipNameNr_AllTables 3586
#define sipName_AllTables &sipStrings_QtSql[3586]
#define sipNameNr_TableType 1471
#define sipName_TableType &sipStrings_QtSql[1471]
#define sipNameNr_ParamType 1487
#define sipName_ParamType &sipStrings_QtSql[1487]
#define sipNameNr_selectRow 3596
#define sipName_selectRow &sipStrings_QtSql[3596]
#define sipNameNr_operation 3606
#define sipName_operation &sipStrings_QtSql[3606]
#define sipNameNr_drawFocus 3616
#define sipName_drawFocus &sipStrings_QtSql[3616]
#define sipNameNr_drawCheck 3626
#define sipName_drawCheck &sipStrings_QtSql[3626]
#define sipNameNr_setActive 3636
#define sipName_setActive &sipStrings_QtSql[3636]
#define sipNameNr_lineWidth 3646
#define sipName_lineWidth &sipStrings_QtSql[3646]
#define sipNameNr_helpEvent 3656
#define sipName_helpEvent &sipStrings_QtSql[3656]
#define sipNameNr_directory 3666
#define sipName_directory &sipStrings_QtSql[3666]
#define sipNameNr_alignment 3676
#define sipName_alignment &sipStrings_QtSql[3676]
#define sipNameNr_setLength 3686
#define sipName_setLength &sipStrings_QtSql[3686]
#define sipNameNr_setFilter 3696
#define sipName_setFilter &sipStrings_QtSql[3696]
#define sipNameNr_precision 3706
#define sipName_precision &sipStrings_QtSql[3706]
#define sipNameNr_roleNames 3716
#define sipName_roleNames &sipStrings_QtSql[3716]
#define sipNameNr_fetchMore 3726
#define sipName_fetchMore &sipStrings_QtSql[3726]
#define sipNameNr_mimeTypes 3736
#define sipName_mimeTypes &sipStrings_QtSql[3736]
#define sipNameNr_LeftJoin 3746
#define sipName_LeftJoin &sipStrings_QtSql[3746]
#define sipNameNr_JoinMode 26
#define sipName_JoinMode &sipStrings_QtSql[26]
#define sipNameNr_relation 3755
#define sipName_relation &sipStrings_QtSql[3755]
#define sipNameNr_setTable 3764
#define sipName_setTable &sipStrings_QtSql[3764]
#define sipNameNr_isSelect 3773
#define sipName_isSelect &sipStrings_QtSql[3773]
#define sipNameNr_Required 2840
#define sipName_Required &sipStrings_QtSql[2840]
#define sipNameNr_Optional 3782
#define sipName_Optional &sipStrings_QtSql[3782]
#define sipNameNr_database 3791
#define sipName_database &sipStrings_QtSql[3791]
#define sipNameNr_hostName 3800
#define sipName_hostName &sipStrings_QtSql[3800]
#define sipNameNr_rollback 3809
#define sipName_rollback &sipStrings_QtSql[3809]
#define sipNameNr_Location 1779
#define sipName_Location &sipStrings_QtSql[1779]
#define sipNameNr_fillRule 3818
#define sipName_fillRule &sipStrings_QtSql[3818]
#define sipNameNr_tabArray 3827
#define sipName_tabArray &sipStrings_QtSql[3827]
#define sipNameNr_tabStops 3836
#define sipName_tabStops &sipStrings_QtSql[3836]
#define sipNameNr_userData 3845
#define sipName_userData &sipStrings_QtSql[3845]
#define sipNameNr_previous 3854
#define sipName_previous &sipStrings_QtSql[3854]
#define sipNameNr_sizeHint 3863
#define sipName_sizeHint &sipStrings_QtSql[3863]
#define sipNameNr_shortcut 3872
#define sipName_shortcut &sipStrings_QtSql[3872]
#define sipNameNr_setQuery 3881
#define sipName_setQuery &sipStrings_QtSql[3881]
#define sipNameNr_relative 3890
#define sipName_relative &sipStrings_QtSql[3890]
#define sipNameNr_password 3899
#define sipName_password &sipStrings_QtSql[3899]
#define sipNameNr_userName 3908
#define sipName_userName &sipStrings_QtSql[3908]
#define sipNameNr_behavior 3917
#define sipName_behavior &sipStrings_QtSql[3917]
#define sipNameNr_position 3926
#define sipName_position &sipStrings_QtSql[3926]
#define sipNameNr_fillChar 3935
#define sipName_fillChar &sipStrings_QtSql[3935]
#define sipNameNr_setValue 3944
#define sipName_setValue &sipStrings_QtSql[3944]
#define sipNameNr_encoding 3953
#define sipName_encoding &sipStrings_QtSql[3953]
#define sipNameNr_contains 3962
#define sipName_contains &sipStrings_QtSql[3962]
#define sipNameNr_isActive 3971
#define sipName_isActive &sipStrings_QtSql[3971]
#define sipNameNr_moveRows 1568
#define sipName_moveRows &sipStrings_QtSql[1568]
#define sipNameNr_mimeData 3980
#define sipName_mimeData &sipStrings_QtSql[3980]
#define sipNameNr_itemData 3989
#define sipName_itemData &sipStrings_QtSql[3989]
#define sipNameNr_rowCount 3998
#define sipName_rowCount &sipStrings_QtSql[3998]
#define sipNameNr___bool__ 4007
#define sipName___bool__ &sipStrings_QtSql[4007]
#define sipNameNr___ixor__ 4016
#define sipName___ixor__ &sipStrings_QtSql[4016]
#define sipNameNr___iand__ 4025
#define sipName___iand__ &sipStrings_QtSql[4025]
#define sipNameNr_setSort 4034
#define sipName_setSort &sipStrings_QtSql[4034]
#define sipNameNr_isDirty 4042
#define sipName_isDirty &sipStrings_QtSql[4042]
#define sipNameNr_setNull 4050
#define sipName_setNull &sipStrings_QtSql[4050]
#define sipNameNr_setOpen 4058
#define sipName_setOpen &sipStrings_QtSql[4058]
#define sipNameNr_Unicode 4066
#define sipName_Unicode &sipStrings_QtSql[4066]
#define sipNameNr_drivers 4074
#define sipName_drivers &sipStrings_QtSql[4074]
#define sipNameNr_setName 4082
#define sipName_setName &sipStrings_QtSql[4082]
#define sipNameNr_Unknown 4090
#define sipName_Unknown &sipStrings_QtSql[4090]
#define sipNameNr_prepare 4098
#define sipName_prepare &sipStrings_QtSql[4098]
#define sipNameNr_exposed 4106
#define sipName_exposed &sipStrings_QtSql[4106]
#define sipNameNr_button2 4114
#define sipName_button2 &sipStrings_QtSql[4114]
#define sipNameNr_button1 4122
#define sipName_button1 &sipStrings_QtSql[4122]
#define sipNameNr_quality 4130
#define sipName_quality &sipStrings_QtSql[4130]
#define sipNameNr_yMargin 4138
#define sipName_yMargin &sipStrings_QtSql[4138]
#define sipNameNr_xMargin 4146
#define sipName_xMargin &sipStrings_QtSql[4146]
#define sipNameNr_caption 4154
#define sipName_caption &sipStrings_QtSql[4154]
#define sipNameNr_setPort 4162
#define sipName_setPort &sipStrings_QtSql[4162]
#define sipNameNr_options 4170
#define sipName_options &sipStrings_QtSql[4170]
#define sipNameNr_NoError 4178
#define sipName_NoError &sipStrings_QtSql[4178]
#define sipNameNr_setType 4186
#define sipName_setType &sipStrings_QtSql[4186]
#define sipNameNr_replace 4194
#define sipName_replace &sipStrings_QtSql[4194]
#define sipNameNr_indexOf 4202
#define sipName_indexOf &sipStrings_QtSql[4202]
#define sipNameNr_isEmpty 4210
#define sipName_isEmpty &sipStrings_QtSql[4210]
#define sipNameNr___len__ 4218
#define sipName___len__ &sipStrings_QtSql[4218]
#define sipNameNr_setData 4226
#define sipName_setData &sipStrings_QtSql[4226]
#define sipNameNr_sibling 4234
#define sipName_sibling &sipStrings_QtSql[4234]
#define sipNameNr_isValid 4242
#define sipName_isValid &sipStrings_QtSql[4242]
#define sipNameNr_filters 4250
#define sipName_filters &sipStrings_QtSql[4250]
#define sipNameNr___xor__ 4258
#define sipName___xor__ &sipStrings_QtSql[4258]
#define sipNameNr___ior__ 4266
#define sipName___ior__ &sipStrings_QtSql[4266]
#define sipNameNr___and__ 4274
#define sipName___and__ &sipStrings_QtSql[4274]
#define sipNameNr___int__ 4282
#define sipName___int__ &sipStrings_QtSql[4282]
#define sipNameNr_typeID 4290
#define sipName_typeID &sipStrings_QtSql[4290]
#define sipNameNr_driver 4297
#define sipName_driver &sipStrings_QtSql[4297]
#define sipNameNr_commit 4304
#define sipName_commit &sipStrings_QtSql[4304]
#define sipNameNr_record 4311
#define sipName_record &sipStrings_QtSql[4311]
#define sipNameNr_tables 4318
#define sipName_tables &sipStrings_QtSql[4318]
#define sipNameNr_Tables 2554
#define sipName_Tables &sipStrings_QtSql[2554]
#define sipNameNr_Binary 4325
#define sipName_Binary &sipStrings_QtSql[4325]
#define sipNameNr_finish 4332
#define sipName_finish &sipStrings_QtSql[4332]
#define sipNameNr_yRound 4339
#define sipName_yRound &sipStrings_QtSql[4339]
#define sipNameNr_xRound 4346
#define sipName_xRound &sipStrings_QtSql[4346]
#define sipNameNr_select 4353
#define sipName_select &sipStrings_QtSql[4353]
#define sipNameNr_layers 4360
#define sipName_layers &sipStrings_QtSql[4360]
#define sipNameNr_sunken 4367
#define sipName_sunken &sipStrings_QtSql[4367]
#define sipNameNr_option 4374
#define sipName_option &sipStrings_QtSql[4374]
#define sipNameNr_proper 4381
#define sipName_proper &sipStrings_QtSql[4381]
#define sipNameNr_value9 4388
#define sipName_value9 &sipStrings_QtSql[4388]
#define sipNameNr_value8 4395
#define sipName_value8 &sipStrings_QtSql[4395]
#define sipNameNr_value7 4402
#define sipName_value7 &sipStrings_QtSql[4402]
#define sipNameNr_value6 4409
#define sipName_value6 &sipStrings_QtSql[4409]
#define sipNameNr_value5 4416
#define sipName_value5 &sipStrings_QtSql[4416]
#define sipNameNr_value4 4423
#define sipName_value4 &sipStrings_QtSql[4423]
#define sipNameNr_value3 4430
#define sipName_value3 &sipStrings_QtSql[4430]
#define sipNameNr_value2 4437
#define sipName_value2 &sipStrings_QtSql[4437]
#define sipNameNr_value1 4444
#define sipName_value1 &sipStrings_QtSql[4444]
#define sipNameNr_value0 4451
#define sipName_value0 &sipStrings_QtSql[4451]
#define sipNameNr_symbol 4458
#define sipName_symbol &sipStrings_QtSql[4458]
#define sipNameNr_isOpen 4465
#define sipName_isOpen &sipStrings_QtSql[4465]
#define sipNameNr_suffix 4472
#define sipName_suffix &sipStrings_QtSql[4472]
#define sipNameNr_handle 4479
#define sipName_handle &sipStrings_QtSql[4479]
#define sipNameNr_prefix 4486
#define sipName_prefix &sipStrings_QtSql[4486]
#define sipNameNr_number 4493
#define sipName_number &sipStrings_QtSql[4493]
#define sipNameNr_format 4500
#define sipName_format &sipStrings_QtSql[4500]
#define sipNameNr_remove 4507
#define sipName_remove &sipStrings_QtSql[4507]
#define sipNameNr_insert 4514
#define sipName_insert &sipStrings_QtSql[4514]
#define sipNameNr_append 4521
#define sipName_append &sipStrings_QtSql[4521]
#define sipNameNr_length 4528
#define sipName_length &sipStrings_QtSql[4528]
#define sipNameNr_isNull 4535
#define sipName_isNull &sipStrings_QtSql[4535]
#define sipNameNr_result 4542
#define sipName_result &sipStrings_QtSql[4542]
#define sipNameNr_revert 4549
#define sipName_revert &sipStrings_QtSql[4549]
#define sipNameNr_submit 4556
#define sipName_submit &sipStrings_QtSql[4556]
#define sipNameNr_column 4563
#define sipName_column &sipStrings_QtSql[4563]
#define sipNameNr_filter 4570
#define sipName_filter &sipStrings_QtSql[4570]
#define sipNameNr_parent 4577
#define sipName_parent &sipStrings_QtSql[4577]
#define sipNameNr___ne__ 4584
#define sipName___ne__ &sipStrings_QtSql[4584]
#define sipNameNr___eq__ 4591
#define sipName___eq__ &sipStrings_QtSql[4591]
#define sipNameNr___or__ 4598
#define sipName___or__ &sipStrings_QtSql[4598]
#define sipNameNr_fetch 4605
#define sipName_fetch &sipStrings_QtSql[4605]
#define sipNameNr_setAt 4611
#define sipName_setAt &sipStrings_QtSql[4611]
#define sipNameNr_Views 4617
#define sipName_Views &sipStrings_QtSql[4617]
#define sipNameNr_InOut 4623
#define sipName_InOut &sipStrings_QtSql[4623]
#define sipNameNr_field 4629
#define sipName_field &sipStrings_QtSql[4629]
#define sipNameNr_brush 4635
#define sipName_brush &sipStrings_QtSql[4635]
#define sipNameNr_paint 4641
#define sipName_paint &sipStrings_QtSql[4641]
#define sipNameNr_query 4647
#define sipName_query &sipStrings_QtSql[4647]
#define sipNameNr_exec_ 4653
#define sipName_exec_ &sipStrings_QtSql[4653]
#define sipNameNr_close 4659
#define sipName_close &sipStrings_QtSql[4659]
#define sipNameNr_clear 4665
#define sipName_clear &sipStrings_QtSql[4665]
#define sipNameNr_reset 4671
#define sipName_reset &sipStrings_QtSql[4671]
#define sipNameNr_first 4677
#define sipName_first &sipStrings_QtSql[4677]
#define sipNameNr_match 4683
#define sipName_match &sipStrings_QtSql[4683]
#define sipNameNr_buddy 4689
#define sipName_buddy &sipStrings_QtSql[4689]
#define sipNameNr_order 4695
#define sipName_order &sipStrings_QtSql[4695]
#define sipNameNr_count 4701
#define sipName_count &sipStrings_QtSql[4701]
#define sipNameNr_value 4707
#define sipName_value &sipStrings_QtSql[4707]
#define sipNameNr_index 4713
#define sipName_index &sipStrings_QtSql[4713]
#define sipNameNr_flags 4719
#define sipName_flags &sipStrings_QtSql[4719]
#define sipNameNr_event 4725
#define sipName_event &sipStrings_QtSql[4725]
#define sipNameNr_msecs 4731
#define sipName_msecs &sipStrings_QtSql[4731]
#define sipNameNr_state 4737
#define sipName_state &sipStrings_QtSql[4737]
#define sipNameNr_BLOB 4743
#define sipName_BLOB &sipStrings_QtSql[4743]
#define sipNameNr_user 4748
#define sipName_user &sipStrings_QtSql[4748]
#define sipNameNr_QSql 4753
#define sipName_QSql &sipStrings_QtSql[4753]
#define sipNameNr_port 4758
#define sipName_port &sipStrings_QtSql[4758]
#define sipNameNr_host 4763
#define sipName_host &sipStrings_QtSql[4763]
#define sipNameNr_text 4768
#define sipName_text &sipStrings_QtSql[4768]
#define sipNameNr_mode 4773
#define sipName_mode &sipStrings_QtSql[4773]
#define sipNameNr_next 4778
#define sipName_next &sipStrings_QtSql[4778]
#define sipNameNr_name 4783
#define sipName_name &sipStrings_QtSql[4783]
#define sipNameNr_exec 4788
#define sipName_exec &sipStrings_QtSql[4788]
#define sipNameNr_base 1723
#define sipName_base &sipStrings_QtSql[1723]
#define sipNameNr_seek 4793
#define sipName_seek &sipStrings_QtSql[4793]
#define sipNameNr_open 4798
#define sipName_open &sipStrings_QtSql[4798]
#define sipNameNr_fill 4803
#define sipName_fill &sipStrings_QtSql[4803]
#define sipNameNr_from 4808
#define sipName_from &sipStrings_QtSql[4808]
#define sipNameNr_last 4813
#define sipName_last &sipStrings_QtSql[4813]
#define sipNameNr_span 4818
#define sipName_span &sipStrings_QtSql[4818]
#define sipNameNr_sort 4823
#define sipName_sort &sipStrings_QtSql[4823]
#define sipNameNr_role 4828
#define sipName_role &sipStrings_QtSql[4828]
#define sipNameNr_data 4833
#define sipName_data &sipStrings_QtSql[4833]
#define sipNameNr_type 4838
#define sipName_type &sipStrings_QtSql[4838]
#define sipNameNr_size 4843
#define sipName_size &sipStrings_QtSql[4843]
#define sipNameNr_Out 4625
#define sipName_Out &sipStrings_QtSql[4625]
#define sipNameNr_pen 4062
#define sipName_pen &sipStrings_QtSql[4062]
#define sipNameNr_end 4524
#define sipName_end &sipStrings_QtSql[4524]
#define sipNameNr_pos 4848
#define sipName_pos &sipStrings_QtSql[4848]
#define sipNameNr_db 4852
#define sipName_db &sipStrings_QtSql[4852]
#define sipNameNr_In 4855
#define sipName_In &sipStrings_QtSql[4855]
#define sipNameNr_sw 4858
#define sipName_sw &sipStrings_QtSql[4858]
#define sipNameNr_sy 4861
#define sipName_sy &sipStrings_QtSql[4861]
#define sipNameNr_sx 4864
#define sipName_sx &sipStrings_QtSql[4864]
#define sipNameNr_sh 4336
#define sipName_sh &sipStrings_QtSql[4336]
#define sipNameNr_cs 4734
#define sipName_cs &sipStrings_QtSql[4734]
#define sipNameNr_at 4504
#define sipName_at &sipStrings_QtSql[4504]

#define sipMalloc                   sipAPI_QtSql->api_malloc
#define sipFree                     sipAPI_QtSql->api_free
#define sipBuildResult              sipAPI_QtSql->api_build_result
#define sipCallMethod               sipAPI_QtSql->api_call_method
#define sipCallProcedureMethod      sipAPI_QtSql->api_call_procedure_method
#define sipCallErrorHandler         sipAPI_QtSql->api_call_error_handler
#define sipParseResultEx            sipAPI_QtSql->api_parse_result_ex
#define sipParseResult              sipAPI_QtSql->api_parse_result
#define sipParseArgs                sipAPI_QtSql->api_parse_args
#define sipParseKwdArgs             sipAPI_QtSql->api_parse_kwd_args
#define sipParsePair                sipAPI_QtSql->api_parse_pair
#define sipInstanceDestroyed        sipAPI_QtSql->api_instance_destroyed
#define sipInstanceDestroyedEx      sipAPI_QtSql->api_instance_destroyed_ex
#define sipConvertFromSequenceIndex sipAPI_QtSql->api_convert_from_sequence_index
#define sipConvertFromVoidPtr       sipAPI_QtSql->api_convert_from_void_ptr
#define sipConvertToVoidPtr         sipAPI_QtSql->api_convert_to_void_ptr
#define sipAddException             sipAPI_QtSql->api_add_exception
#define sipNoFunction               sipAPI_QtSql->api_no_function
#define sipNoMethod                 sipAPI_QtSql->api_no_method
#define sipAbstractMethod           sipAPI_QtSql->api_abstract_method
#define sipBadClass                 sipAPI_QtSql->api_bad_class
#define sipBadCatcherResult         sipAPI_QtSql->api_bad_catcher_result
#define sipBadCallableArg           sipAPI_QtSql->api_bad_callable_arg
#define sipBadOperatorArg           sipAPI_QtSql->api_bad_operator_arg
#define sipTrace                    sipAPI_QtSql->api_trace
#define sipTransferBack             sipAPI_QtSql->api_transfer_back
#define sipTransferTo               sipAPI_QtSql->api_transfer_to
#define sipTransferBreak            sipAPI_QtSql->api_transfer_break
#define sipSimpleWrapper_Type       sipAPI_QtSql->api_simplewrapper_type
#define sipWrapper_Type             sipAPI_QtSql->api_wrapper_type
#define sipWrapperType_Type         sipAPI_QtSql->api_wrappertype_type
#define sipVoidPtr_Type             sipAPI_QtSql->api_voidptr_type
#define sipGetPyObject              sipAPI_QtSql->api_get_pyobject
#define sipGetAddress               sipAPI_QtSql->api_get_address
#define sipGetMixinAddress          sipAPI_QtSql->api_get_mixin_address
#define sipGetCppPtr                sipAPI_QtSql->api_get_cpp_ptr
#define sipGetComplexCppPtr         sipAPI_QtSql->api_get_complex_cpp_ptr
#define sipIsPyMethod               sipAPI_QtSql->api_is_py_method
#define sipCallHook                 sipAPI_QtSql->api_call_hook
#define sipEndThread                sipAPI_QtSql->api_end_thread
#define sipConnectRx                sipAPI_QtSql->api_connect_rx
#define sipDisconnectRx             sipAPI_QtSql->api_disconnect_rx
#define sipRaiseUnknownException    sipAPI_QtSql->api_raise_unknown_exception
#define sipRaiseTypeException       sipAPI_QtSql->api_raise_type_exception
#define sipBadLengthForSlice        sipAPI_QtSql->api_bad_length_for_slice
#define sipAddTypeInstance          sipAPI_QtSql->api_add_type_instance
#define sipFreeSipslot              sipAPI_QtSql->api_free_sipslot
#define sipSameSlot                 sipAPI_QtSql->api_same_slot
#define sipPySlotExtend             sipAPI_QtSql->api_pyslot_extend
#define sipConvertRx                sipAPI_QtSql->api_convert_rx
#define sipAddDelayedDtor           sipAPI_QtSql->api_add_delayed_dtor
#define sipCanConvertToType         sipAPI_QtSql->api_can_convert_to_type
#define sipConvertToType            sipAPI_QtSql->api_convert_to_type
#define sipForceConvertToType       sipAPI_QtSql->api_force_convert_to_type
#define sipCanConvertToEnum         sipAPI_QtSql->api_can_convert_to_enum
#define sipConvertToEnum            sipAPI_QtSql->api_convert_to_enum
#define sipConvertToBool            sipAPI_QtSql->api_convert_to_bool
#define sipReleaseType              sipAPI_QtSql->api_release_type
#define sipConvertFromType          sipAPI_QtSql->api_convert_from_type
#define sipConvertFromNewType       sipAPI_QtSql->api_convert_from_new_type
#define sipConvertFromNewPyType     sipAPI_QtSql->api_convert_from_new_pytype
#define sipConvertFromEnum          sipAPI_QtSql->api_convert_from_enum
#define sipGetState                 sipAPI_QtSql->api_get_state
#define sipExportSymbol             sipAPI_QtSql->api_export_symbol
#define sipImportSymbol             sipAPI_QtSql->api_import_symbol
#define sipFindType                 sipAPI_QtSql->api_find_type
#define sipFindNamedEnum            sipAPI_QtSql->api_find_named_enum
#define sipBytes_AsChar             sipAPI_QtSql->api_bytes_as_char
#define sipBytes_AsString           sipAPI_QtSql->api_bytes_as_string
#define sipString_AsASCIIChar       sipAPI_QtSql->api_string_as_ascii_char
#define sipString_AsASCIIString     sipAPI_QtSql->api_string_as_ascii_string
#define sipString_AsLatin1Char      sipAPI_QtSql->api_string_as_latin1_char
#define sipString_AsLatin1String    sipAPI_QtSql->api_string_as_latin1_string
#define sipString_AsUTF8Char        sipAPI_QtSql->api_string_as_utf8_char
#define sipString_AsUTF8String      sipAPI_QtSql->api_string_as_utf8_string
#define sipUnicode_AsWChar          sipAPI_QtSql->api_unicode_as_wchar
#define sipUnicode_AsWString        sipAPI_QtSql->api_unicode_as_wstring
#define sipConvertFromConstVoidPtr  sipAPI_QtSql->api_convert_from_const_void_ptr
#define sipConvertFromVoidPtrAndSize    sipAPI_QtSql->api_convert_from_void_ptr_and_size
#define sipConvertFromConstVoidPtrAndSize   sipAPI_QtSql->api_convert_from_const_void_ptr_and_size
#define sipInvokeSlot               sipAPI_QtSql->api_invoke_slot
#define sipInvokeSlotEx             sipAPI_QtSql->api_invoke_slot_ex
#define sipSaveSlot                 sipAPI_QtSql->api_save_slot
#define sipClearAnySlotReference    sipAPI_QtSql->api_clear_any_slot_reference
#define sipVisitSlot                sipAPI_QtSql->api_visit_slot
#define sipWrappedTypeName(wt)      ((wt)->wt_td->td_cname)
#define sipDeprecated               sipAPI_QtSql->api_deprecated
#define sipGetReference             sipAPI_QtSql->api_get_reference
#define sipKeepReference            sipAPI_QtSql->api_keep_reference
#define sipRegisterProxyResolver    sipAPI_QtSql->api_register_proxy_resolver
#define sipRegisterPyType           sipAPI_QtSql->api_register_py_type
#define sipTypeFromPyTypeObject     sipAPI_QtSql->api_type_from_py_type_object
#define sipTypeScope                sipAPI_QtSql->api_type_scope
#define sipResolveTypedef           sipAPI_QtSql->api_resolve_typedef
#define sipRegisterAttributeGetter  sipAPI_QtSql->api_register_attribute_getter
#define sipIsAPIEnabled             sipAPI_QtSql->api_is_api_enabled
#define sipSetDestroyOnExit         sipAPI_QtSql->api_set_destroy_on_exit
#define sipEnableAutoconversion     sipAPI_QtSql->api_enable_autoconversion
#define sipEnableOverflowChecking   sipAPI_QtSql->api_enable_overflow_checking
#define sipInitMixin                sipAPI_QtSql->api_init_mixin
#define sipExportModule             sipAPI_QtSql->api_export_module
#define sipInitModule               sipAPI_QtSql->api_init_module
#define sipGetInterpreter           sipAPI_QtSql->api_get_interpreter
#define sipSetNewUserTypeHandler    sipAPI_QtSql->api_set_new_user_type_handler
#define sipSetTypeUserData          sipAPI_QtSql->api_set_type_user_data
#define sipGetTypeUserData          sipAPI_QtSql->api_get_type_user_data
#define sipPyTypeDict               sipAPI_QtSql->api_py_type_dict
#define sipPyTypeName               sipAPI_QtSql->api_py_type_name
#define sipGetCFunction             sipAPI_QtSql->api_get_c_function
#define sipGetMethod                sipAPI_QtSql->api_get_method
#define sipFromMethod               sipAPI_QtSql->api_from_method
#define sipGetDate                  sipAPI_QtSql->api_get_date
#define sipFromDate                 sipAPI_QtSql->api_from_date
#define sipGetDateTime              sipAPI_QtSql->api_get_datetime
#define sipFromDateTime             sipAPI_QtSql->api_from_datetime
#define sipGetTime                  sipAPI_QtSql->api_get_time
#define sipFromTime                 sipAPI_QtSql->api_from_time
#define sipIsUserType               sipAPI_QtSql->api_is_user_type
#define sipGetFrame                 sipAPI_QtSql->api_get_frame
#define sipCheckPluginForType       sipAPI_QtSql->api_check_plugin_for_type
#define sipUnicodeNew               sipAPI_QtSql->api_unicode_new
#define sipUnicodeWrite             sipAPI_QtSql->api_unicode_write
#define sipUnicodeData              sipAPI_QtSql->api_unicode_data
#define sipGetBufferInfo            sipAPI_QtSql->api_get_buffer_info
#define sipReleaseBufferInfo        sipAPI_QtSql->api_release_buffer_info
#define sipIsOwnedByPython          sipAPI_QtSql->api_is_owned_by_python
#define sipIsDerivedClass           sipAPI_QtSql->api_is_derived_class
#define sipGetUserObject            sipAPI_QtSql->api_get_user_object
#define sipSetUserObject            sipAPI_QtSql->api_set_user_object
#define sipRegisterEventHandler     sipAPI_QtSql->api_register_event_handler
#define sipLong_AsChar              sipAPI_QtSql->api_long_as_char
#define sipLong_AsSignedChar        sipAPI_QtSql->api_long_as_signed_char
#define sipLong_AsUnsignedChar      sipAPI_QtSql->api_long_as_unsigned_char
#define sipLong_AsShort             sipAPI_QtSql->api_long_as_short
#define sipLong_AsUnsignedShort     sipAPI_QtSql->api_long_as_unsigned_short
#define sipLong_AsInt               sipAPI_QtSql->api_long_as_int
#define sipLong_AsUnsignedInt       sipAPI_QtSql->api_long_as_unsigned_int
#define sipLong_AsLong              sipAPI_QtSql->api_long_as_long
#define sipLong_AsUnsignedLong      sipAPI_QtSql->api_long_as_unsigned_long
#define sipLong_AsLongLong          sipAPI_QtSql->api_long_as_long_long
#define sipLong_AsUnsignedLongLong  sipAPI_QtSql->api_long_as_unsigned_long_long

/* These are deprecated. */
#define sipMapStringToClass         sipAPI_QtSql->api_map_string_to_class
#define sipMapIntToClass            sipAPI_QtSql->api_map_int_to_class
#define sipFindClass                sipAPI_QtSql->api_find_class
#define sipFindMappedType           sipAPI_QtSql->api_find_mapped_type
#define sipConvertToArray           sipAPI_QtSql->api_convert_to_array
#define sipConvertToTypedArray      sipAPI_QtSql->api_convert_to_typed_array
#define sipEnableGC                 sipAPI_QtSql->api_enable_gc
#define sipPrintObject              sipAPI_QtSql->api_print_object
#define sipWrapper_Check(w)         PyObject_TypeCheck((w), sipAPI_QtSql->api_wrapper_type)
#define sipGetWrapper(p, wt)        sipGetPyObject((p), (wt)->wt_td)
#define sipReleaseInstance(p, wt, s)    sipReleaseType((p), (wt)->wt_td, (s))
#define sipReleaseMappedType        sipReleaseType
#define sipCanConvertToInstance(o, wt, f)   sipCanConvertToType((o), (wt)->wt_td, (f))
#define sipCanConvertToMappedType   sipCanConvertToType
#define sipConvertToInstance(o, wt, t, f, s, e)     sipConvertToType((o), (wt)->wt_td, (t), (f), (s), (e))
#define sipConvertToMappedType      sipConvertToType
#define sipForceConvertToInstance(o, wt, t, f, s, e)    sipForceConvertToType((o), (wt)->wt_td, (t), (f), (s), (e))
#define sipForceConvertToMappedType sipForceConvertToType
#define sipConvertFromInstance(p, wt, t)    sipConvertFromType((p), (wt)->wt_td, (t))
#define sipConvertFromMappedType    sipConvertFromType
#define sipConvertFromNamedEnum(v, pt)  sipConvertFromEnum((v), ((sipEnumTypeObject *)(pt))->type)
#define sipConvertFromNewInstance(p, wt, t) sipConvertFromNewType((p), (wt)->wt_td, (t))

/* The strings used by this module. */
extern const char sipStrings_QtSql[];

#define sipType_QSql sipExportedTypes_QtSql[0]
#define sipClass_QSql sipExportedTypes_QtSql[0]->u.td_wrapper_type

#define sipType_QSql_NumericalPrecisionPolicy sipExportedTypes_QtSql[2]
#define sipEnum_QSql_NumericalPrecisionPolicy sipExportedTypes_QtSql[2]->u.td_py_type

#define sipType_QSql_TableType sipExportedTypes_QtSql[5]
#define sipEnum_QSql_TableType sipExportedTypes_QtSql[5]->u.td_py_type

#define sipType_QSql_ParamTypeFlag sipExportedTypes_QtSql[4]
#define sipEnum_QSql_ParamTypeFlag sipExportedTypes_QtSql[4]->u.td_py_type

#define sipType_QSql_Location sipExportedTypes_QtSql[1]
#define sipEnum_QSql_Location sipExportedTypes_QtSql[1]->u.td_py_type

extern sipClassTypeDef sipTypeDef_QtSql_QSql;

#define sipType_QSql_ParamType sipExportedTypes_QtSql[3]
#define sipClass_QSql_ParamType sipExportedTypes_QtSql[3]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtSql_QSql_ParamType;

#define sipType_QSqlDriverCreatorBase sipExportedTypes_QtSql[12]
#define sipClass_QSqlDriverCreatorBase sipExportedTypes_QtSql[12]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtSql_QSqlDriverCreatorBase;

#define sipType_QSqlDatabase sipExportedTypes_QtSql[6]
#define sipClass_QSqlDatabase sipExportedTypes_QtSql[6]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtSql_QSqlDatabase;

#define sipType_QSqlDriver sipExportedTypes_QtSql[7]
#define sipClass_QSqlDriver sipExportedTypes_QtSql[7]->u.td_wrapper_type

#define sipType_QSqlDriver_NotificationSource sipExportedTypes_QtSql[10]
#define sipEnum_QSqlDriver_NotificationSource sipExportedTypes_QtSql[10]->u.td_py_type

#define sipType_QSqlDriver_IdentifierType sipExportedTypes_QtSql[9]
#define sipEnum_QSqlDriver_IdentifierType sipExportedTypes_QtSql[9]->u.td_py_type

#define sipType_QSqlDriver_StatementType sipExportedTypes_QtSql[11]
#define sipEnum_QSqlDriver_StatementType sipExportedTypes_QtSql[11]->u.td_py_type

#define sipType_QSqlDriver_DriverFeature sipExportedTypes_QtSql[8]
#define sipEnum_QSqlDriver_DriverFeature sipExportedTypes_QtSql[8]->u.td_py_type

extern sipClassTypeDef sipTypeDef_QtSql_QSqlDriver;

#define sipType_QSqlError sipExportedTypes_QtSql[13]
#define sipClass_QSqlError sipExportedTypes_QtSql[13]->u.td_wrapper_type

#define sipType_QSqlError_ErrorType sipExportedTypes_QtSql[14]
#define sipEnum_QSqlError_ErrorType sipExportedTypes_QtSql[14]->u.td_py_type

extern sipClassTypeDef sipTypeDef_QtSql_QSqlError;

#define sipType_QSqlField sipExportedTypes_QtSql[15]
#define sipClass_QSqlField sipExportedTypes_QtSql[15]->u.td_wrapper_type

#define sipType_QSqlField_RequiredStatus sipExportedTypes_QtSql[16]
#define sipEnum_QSqlField_RequiredStatus sipExportedTypes_QtSql[16]->u.td_py_type

extern sipClassTypeDef sipTypeDef_QtSql_QSqlField;

#define sipType_QSqlRecord sipExportedTypes_QtSql[21]
#define sipClass_QSqlRecord sipExportedTypes_QtSql[21]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtSql_QSqlRecord;

#define sipType_QSqlIndex sipExportedTypes_QtSql[17]
#define sipClass_QSqlIndex sipExportedTypes_QtSql[17]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtSql_QSqlIndex;

#define sipType_QSqlQuery sipExportedTypes_QtSql[18]
#define sipClass_QSqlQuery sipExportedTypes_QtSql[18]->u.td_wrapper_type

#define sipType_QSqlQuery_BatchExecutionMode sipExportedTypes_QtSql[19]
#define sipEnum_QSqlQuery_BatchExecutionMode sipExportedTypes_QtSql[19]->u.td_py_type

extern sipClassTypeDef sipTypeDef_QtSql_QSqlQuery;

#define sipType_QSqlQueryModel sipExportedTypes_QtSql[20]
#define sipClass_QSqlQueryModel sipExportedTypes_QtSql[20]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtSql_QSqlQueryModel;

#define sipType_QSqlRelationalDelegate sipExportedTypes_QtSql[23]
#define sipClass_QSqlRelationalDelegate sipExportedTypes_QtSql[23]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtSql_QSqlRelationalDelegate;

#define sipType_QSqlRelation sipExportedTypes_QtSql[22]
#define sipClass_QSqlRelation sipExportedTypes_QtSql[22]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtSql_QSqlRelation;

#define sipType_QSqlTableModel sipExportedTypes_QtSql[28]
#define sipClass_QSqlTableModel sipExportedTypes_QtSql[28]->u.td_wrapper_type

#define sipType_QSqlTableModel_EditStrategy sipExportedTypes_QtSql[29]
#define sipEnum_QSqlTableModel_EditStrategy sipExportedTypes_QtSql[29]->u.td_py_type

extern sipClassTypeDef sipTypeDef_QtSql_QSqlTableModel;

#define sipType_QSqlRelationalTableModel sipExportedTypes_QtSql[24]
#define sipClass_QSqlRelationalTableModel sipExportedTypes_QtSql[24]->u.td_wrapper_type

#define sipType_QSqlRelationalTableModel_JoinMode sipExportedTypes_QtSql[25]
#define sipEnum_QSqlRelationalTableModel_JoinMode sipExportedTypes_QtSql[25]->u.td_py_type

extern sipClassTypeDef sipTypeDef_QtSql_QSqlRelationalTableModel;

#define sipType_QSqlResult sipExportedTypes_QtSql[26]
#define sipClass_QSqlResult sipExportedTypes_QtSql[26]->u.td_wrapper_type

#define sipType_QSqlResult_BindingSyntax sipExportedTypes_QtSql[27]
#define sipEnum_QSqlResult_BindingSyntax sipExportedTypes_QtSql[27]->u.td_py_type

extern sipClassTypeDef sipTypeDef_QtSql_QSqlResult;

#define sipType_QVector_0100QVariant sipExportedTypes_QtSql[30]

extern sipMappedTypeDef sipTypeDef_QtSql_QVector_0100QVariant;

/* The SIP API, this module's API and the APIs of any imported modules. */
extern const sipAPIDef *sipAPI_QtSql;
extern sipExportedModuleDef sipModuleAPI_QtSql;
extern sipTypeDef *sipExportedTypes_QtSql[];

#define sipType_Qt_CheckState sipImportedTypes_QtSql_QtCore[19].it_td
#define sipEnum_Qt_CheckState sipImportedTypes_QtSql_QtCore[19].it_td->u.td_py_type

#define sipType_Qt_DropAction sipImportedTypes_QtSql_QtCore[20].it_td
#define sipEnum_Qt_DropAction sipImportedTypes_QtSql_QtCore[20].it_td->u.td_py_type

#define sipType_Qt_SortOrder sipImportedTypes_QtSql_QtCore[25].it_td
#define sipEnum_Qt_SortOrder sipImportedTypes_QtSql_QtCore[25].it_td->u.td_py_type

#define sipType_Qt_Orientation sipImportedTypes_QtSql_QtCore[24].it_td
#define sipEnum_Qt_Orientation sipImportedTypes_QtSql_QtCore[24].it_td->u.td_py_type

#define sipType_Qt_DropActions sipImportedTypes_QtSql_QtCore[21].it_td
#define sipClass_Qt_DropActions sipImportedTypes_QtSql_QtCore[21].it_td->u.td_wrapper_type

#define sipType_Qt_ItemFlags sipImportedTypes_QtSql_QtCore[22].it_td
#define sipClass_Qt_ItemFlags sipImportedTypes_QtSql_QtCore[22].it_td->u.td_wrapper_type

#define sipType_Qt_MatchFlags sipImportedTypes_QtSql_QtCore[23].it_td
#define sipClass_Qt_MatchFlags sipImportedTypes_QtSql_QtCore[23].it_td->u.td_wrapper_type

#define sipType_QObject sipImportedTypes_QtSql_QtCore[11].it_td
#define sipClass_QObject sipImportedTypes_QtSql_QtCore[11].it_td->u.td_wrapper_type

#define sipType_QModelIndex sipImportedTypes_QtSql_QtCore[10].it_td
#define sipClass_QModelIndex sipImportedTypes_QtSql_QtCore[10].it_td->u.td_wrapper_type

#define sipType_QAbstractItemModel sipImportedTypes_QtSql_QtCore[0].it_td
#define sipClass_QAbstractItemModel sipImportedTypes_QtSql_QtCore[0].it_td->u.td_wrapper_type

#define sipType_QAbstractTableModel sipImportedTypes_QtSql_QtCore[1].it_td
#define sipClass_QAbstractTableModel sipImportedTypes_QtSql_QtCore[1].it_td->u.td_wrapper_type

#define sipType_QEvent sipImportedTypes_QtSql_QtCore[3].it_td
#define sipClass_QEvent sipImportedTypes_QtSql_QtCore[3].it_td->u.td_wrapper_type

#define sipType_QTimerEvent sipImportedTypes_QtSql_QtCore[16].it_td
#define sipClass_QTimerEvent sipImportedTypes_QtSql_QtCore[16].it_td->u.td_wrapper_type

#define sipType_QChildEvent sipImportedTypes_QtSql_QtCore[2].it_td
#define sipClass_QChildEvent sipImportedTypes_QtSql_QtCore[2].it_td->u.td_wrapper_type

#define sipType_QMetaMethod sipImportedTypes_QtSql_QtCore[8].it_td
#define sipClass_QMetaMethod sipImportedTypes_QtSql_QtCore[8].it_td->u.td_wrapper_type

#define sipType_QMimeData sipImportedTypes_QtSql_QtCore[9].it_td
#define sipClass_QMimeData sipImportedTypes_QtSql_QtCore[9].it_td->u.td_wrapper_type

#define sipType_QRect sipImportedTypes_QtSql_QtCore[12].it_td
#define sipClass_QRect sipImportedTypes_QtSql_QtCore[12].it_td->u.td_wrapper_type

#define sipType_QSize sipImportedTypes_QtSql_QtCore[13].it_td
#define sipClass_QSize sipImportedTypes_QtSql_QtCore[13].it_td->u.td_wrapper_type

#define sipType_QVariant sipImportedTypes_QtSql_QtCore[17].it_td
#define sipClass_QVariant sipImportedTypes_QtSql_QtCore[17].it_td->u.td_wrapper_type

#define sipType_QVariant_Type sipImportedTypes_QtSql_QtCore[18].it_td
#define sipEnum_QVariant_Type sipImportedTypes_QtSql_QtCore[18].it_td->u.td_py_type

#define sipType_QHash_1800_0100QByteArray sipImportedTypes_QtSql_QtCore[4].it_td

#define sipType_QMap_1800_0100QVariant sipImportedTypes_QtSql_QtCore[7].it_td

#define sipType_QMap_0100QString_0100QVariant sipImportedTypes_QtSql_QtCore[6].it_td

#define sipType_QList_0100QModelIndex sipImportedTypes_QtSql_QtCore[5].it_td

#define sipType_QStringList sipImportedTypes_QtSql_QtCore[15].it_td

#define sipType_QString sipImportedTypes_QtSql_QtCore[14].it_td
extern sipImportedTypeDef sipImportedTypes_QtSql_QtCore[];

#define sipType_QWidget sipImportedTypes_QtSql_QtGui[7].it_td
#define sipClass_QWidget sipImportedTypes_QtSql_QtGui[7].it_td->u.td_wrapper_type

#define sipType_QAbstractItemDelegate sipImportedTypes_QtSql_QtGui[0].it_td
#define sipClass_QAbstractItemDelegate sipImportedTypes_QtSql_QtGui[0].it_td->u.td_wrapper_type

#define sipType_QAbstractItemView sipImportedTypes_QtSql_QtGui[1].it_td
#define sipClass_QAbstractItemView sipImportedTypes_QtSql_QtGui[1].it_td->u.td_wrapper_type

#define sipType_QPixmap sipImportedTypes_QtSql_QtGui[5].it_td
#define sipClass_QPixmap sipImportedTypes_QtSql_QtGui[5].it_td->u.td_wrapper_type

#define sipType_QHelpEvent sipImportedTypes_QtSql_QtGui[2].it_td
#define sipClass_QHelpEvent sipImportedTypes_QtSql_QtGui[2].it_td->u.td_wrapper_type

#define sipType_QItemDelegate sipImportedTypes_QtSql_QtGui[3].it_td
#define sipClass_QItemDelegate sipImportedTypes_QtSql_QtGui[3].it_td->u.td_wrapper_type

#define sipType_QPainter sipImportedTypes_QtSql_QtGui[4].it_td
#define sipClass_QPainter sipImportedTypes_QtSql_QtGui[4].it_td->u.td_wrapper_type

#define sipType_QStyleOptionViewItem sipImportedTypes_QtSql_QtGui[6].it_td
#define sipClass_QStyleOptionViewItem sipImportedTypes_QtSql_QtGui[6].it_td->u.td_wrapper_type
extern sipImportedTypeDef sipImportedTypes_QtSql_QtGui[];

typedef const QMetaObject *(*sip_qt_metaobject_func)(sipSimpleWrapper *,sipTypeDef *);
extern sip_qt_metaobject_func sip_QtSql_qt_metaobject;

typedef int (*sip_qt_metacall_func)(sipSimpleWrapper *,sipTypeDef *,QMetaObject::Call,int,void **);
extern sip_qt_metacall_func sip_QtSql_qt_metacall;

typedef int (*sip_qt_metacast_func)(sipSimpleWrapper *, sipTypeDef *, const char *);
extern sip_qt_metacast_func sip_QtSql_qt_metacast;

#endif
