/*
 * Internal module API header file.
 *
 * Generated by SIP 4.19.8
 *
 * Copyright (c) 2016 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of PyQt4.
 * 
 * This file may be used under the terms of the GNU General Public License
 * version 3.0 as published by the Free Software Foundation and appearing in
 * the file LICENSE included in the packaging of this file.  Please review the
 * following information to ensure the GNU General Public License version 3.0
 * requirements will be met: http://www.gnu.org/copyleft/gpl.html.
 * 
 * If you do not wish to use this file under the terms of the GPL version 3.0
 * then you may purchase a commercial license.  For more information contact
 * info@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#ifndef _QtSvgAPI_H
#define _QtSvgAPI_H

#include <sip.h>

#include <QMetaType>
#include <QThread>

/* These are the qualifiers that are enabled. */
#define SIP_FEATURE_PyQt_Process
#define SIP_FEATURE_PyQt_NotBootstrapped
#define SIP_FEATURE_PyQt_Deprecated_5_0
#define SIP_FEATURE_PyQt_NoOpenGLES
#define SIP_FEATURE_PyQt_RawFont
#define SIP_FEATURE_PyQt_SystemTrayIcon
#define SIP_FEATURE_PyQt_PrintPreviewDialog
#define SIP_FEATURE_PyQt_PrintPreviewWidget
#define SIP_FEATURE_PyQt_Printer
#define SIP_FEATURE_PyQt_PrintDialog
#define SIP_FEATURE_Py_v3
#define SIP_FEATURE_PyQt_qreal_double
#define SIP_FEATURE_PyQt_SizeGrip
#define SIP_FEATURE_PyQt_OpenSSL
#define SIP_FEATURE_Py_DateTime
#define SIP_FEATURE_PyQt_NoQtPrintRangeBug
#define SIP_FEATURE_PyQt_WhatsThis
#define SIP_FEATURE_PyQt_ToolTip
#define SIP_FEATURE_PyQt_StatusTip
#define SIP_FEATURE_PyQt_SessionManager
#define SIP_FEATURE_PyQt_Accessibility
#define SIP_PLATFORM_WS_X11
#define SIP_TIMELINE_Qt_5_0_0


/*
 * Convenient names to refer to various strings defined in this module.
 * Only the class names are part of the public API.
 */
#define sipNameNr_mouseDoubleClickEvent 0
#define sipName_mouseDoubleClickEvent &sipStrings_QtSvg[0]
#define sipNameNr_setMaximumCacheSize 22
#define sipName_setMaximumCacheSize &sipStrings_QtSvg[22]
#define sipNameNr_defaultButtonNumber 42
#define sipName_defaultButtonNumber &sipStrings_QtSvg[42]
#define sipNameNr_setFramesPerSecond 62
#define sipName_setFramesPerSecond &sipStrings_QtSvg[62]
#define sipNameNr_escapeButtonNumber 81
#define sipName_escapeButtonNumber &sipStrings_QtSvg[81]
#define sipNameNr_focusNextPrevChild 100
#define sipName_focusNextPrevChild &sipStrings_QtSvg[100]
#define sipNameNr_animationDuration 119
#define sipName_animationDuration &sipStrings_QtSvg[119]
#define sipNameNr_setCachingEnabled 137
#define sipName_setCachingEnabled &sipStrings_QtSvg[137]
#define sipNameNr_setSharedRenderer 155
#define sipName_setSharedRenderer &sipStrings_QtSvg[155]
#define sipNameNr_hasHeightForWidth 173
#define sipName_hasHeightForWidth &sipStrings_QtSvg[173]
#define sipNameNr_mouseReleaseEvent 191
#define sipName_mouseReleaseEvent &sipStrings_QtSvg[191]
#define sipNameNr_matrixForElement 209
#define sipName_matrixForElement &sipStrings_QtSvg[209]
#define sipNameNr_maximumCacheSize 226
#define sipName_maximumCacheSize &sipStrings_QtSvg[226]
#define sipNameNr_isCachingEnabled 243
#define sipName_isCachingEnabled &sipStrings_QtSvg[243]
#define sipNameNr_QGraphicsSvgItem 260
#define sipName_QGraphicsSvgItem &sipStrings_QtSvg[260]
#define sipNameNr_sceneEventFilter 277
#define sipName_sceneEventFilter &sipStrings_QtSvg[277]
#define sipNameNr_collidesWithPath 294
#define sipName_collidesWithPath &sipStrings_QtSvg[294]
#define sipNameNr_collidesWithItem 311
#define sipName_collidesWithItem &sipStrings_QtSvg[311]
#define sipNameNr_contextMenuEvent 328
#define sipName_contextMenuEvent &sipStrings_QtSvg[328]
#define sipNameNr_inputMethodEvent 345
#define sipName_inputMethodEvent &sipStrings_QtSvg[345]
#define sipNameNr_inputMethodQuery 362
#define sipName_inputMethodQuery &sipStrings_QtSvg[362]
#define sipNameNr_disconnectNotify 379
#define sipName_disconnectNotify &sipStrings_QtSvg[379]
#define sipNameNr_setCurrentFrame 396
#define sipName_setCurrentFrame &sipStrings_QtSvg[396]
#define sipNameNr_framesPerSecond 412
#define sipName_framesPerSecond &sipStrings_QtSvg[412]
#define sipNameNr_boundsOnElement 428
#define sipName_boundsOnElement &sipStrings_QtSvg[428]
#define sipNameNr_setOutputDevice 444
#define sipName_setOutputDevice &sipStrings_QtSvg[444]
#define sipNameNr_aspectRatioMode 460
#define sipName_aspectRatioMode &sipStrings_QtSvg[460]
#define sipNameNr_deviceTransform 476
#define sipName_deviceTransform &sipStrings_QtSvg[476]
#define sipNameNr_hoverLeaveEvent 492
#define sipName_hoverLeaveEvent &sipStrings_QtSvg[492]
#define sipNameNr_hoverEnterEvent 508
#define sipName_hoverEnterEvent &sipStrings_QtSvg[508]
#define sipNameNr_minimumSizeHint 524
#define sipName_minimumSizeHint &sipStrings_QtSvg[524]
#define sipNameNr_mousePressEvent 540
#define sipName_mousePressEvent &sipStrings_QtSvg[540]
#define sipNameNr_keyReleaseEvent 556
#define sipName_keyReleaseEvent &sipStrings_QtSvg[556]
#define sipNameNr_hoverMoveEvent 572
#define sipName_hoverMoveEvent &sipStrings_QtSvg[572]
#define sipNameNr_selectedFilter 587
#define sipName_selectedFilter &sipStrings_QtSvg[587]
#define sipNameNr_setDescription 602
#define sipName_setDescription &sipStrings_QtSvg[602]
#define sipNameNr_heightForWidth 617
#define sipName_heightForWidth &sipStrings_QtSvg[617]
#define sipNameNr_dragLeaveEvent 632
#define sipName_dragLeaveEvent &sipStrings_QtSvg[632]
#define sipNameNr_dragEnterEvent 647
#define sipName_dragEnterEvent &sipStrings_QtSvg[647]
#define sipNameNr_mouseMoveEvent 662
#define sipName_mouseMoveEvent &sipStrings_QtSvg[662]
#define sipNameNr_disambiguation 677
#define sipName_disambiguation &sipStrings_QtSvg[677]
#define sipNameNr_repaintNeeded 692
#define sipName_repaintNeeded &sipStrings_QtSvg[692]
#define sipNameNr_elementExists 706
#define sipName_elementExists &sipStrings_QtSvg[706]
#define sipNameNr_QSvgGenerator 720
#define sipName_QSvgGenerator &sipStrings_QtSvg[720]
#define sipNameNr_sharedPainter 734
#define sipName_sharedPainter &sipStrings_QtSvg[734]
#define sipNameNr_setResolution 748
#define sipName_setResolution &sipStrings_QtSvg[748]
#define sipNameNr_transformMode 762
#define sipName_transformMode &sipStrings_QtSvg[762]
#define sipNameNr_dragMoveEvent 776
#define sipName_dragMoveEvent &sipStrings_QtSvg[776]
#define sipNameNr_focusOutEvent 790
#define sipName_focusOutEvent &sipStrings_QtSvg[790]
#define sipNameNr_keyPressEvent 804
#define sipName_keyPressEvent &sipStrings_QtSvg[804]
#define sipNameNr_connectNotify 382
#define sipName_connectNotify &sipStrings_QtSvg[382]
#define sipNameNr_QSvgRenderer 818
#define sipName_QSvgRenderer &sipStrings_QtSvg[818]
#define sipNameNr_outputDevice 831
#define sipName_outputDevice &sipStrings_QtSvg[831]
#define sipNameNr_setElementId 844
#define sipName_setElementId &sipStrings_QtSvg[844]
#define sipNameNr_sourceRegion 857
#define sipName_sourceRegion &sipStrings_QtSvg[857]
#define sipNameNr_targetOffset 870
#define sipName_targetOffset &sipStrings_QtSvg[870]
#define sipNameNr_isObscuredBy 883
#define sipName_isObscuredBy &sipStrings_QtSvg[883]
#define sipNameNr_boundingRect 896
#define sipName_boundingRect &sipStrings_QtSvg[896]
#define sipNameNr_midLineWidth 909
#define sipName_midLineWidth &sipStrings_QtSvg[909]
#define sipNameNr_focusInEvent 922
#define sipName_focusInEvent &sipStrings_QtSvg[922]
#define sipNameNr_currentFrame 935
#define sipName_currentFrame &sipStrings_QtSvg[935]
#define sipNameNr_defaultSize 948
#define sipName_defaultSize &sipStrings_QtSvg[948]
#define sipNameNr_initPainter 960
#define sipName_initPainter &sipStrings_QtSvg[960]
#define sipNameNr_nativeEvent 972
#define sipName_nativeEvent &sipStrings_QtSvg[972]
#define sipNameNr_tabletEvent 984
#define sipName_tabletEvent &sipStrings_QtSvg[984]
#define sipNameNr_button2Text 996
#define sipName_button2Text &sipStrings_QtSvg[996]
#define sipNameNr_button1Text 1008
#define sipName_button1Text &sipStrings_QtSvg[1008]
#define sipNameNr_actionEvent 1020
#define sipName_actionEvent &sipStrings_QtSvg[1020]
#define sipNameNr_paintEngine 1032
#define sipName_paintEngine &sipStrings_QtSvg[1032]
#define sipNameNr_description 1044
#define sipName_description &sipStrings_QtSvg[1044]
#define sipNameNr_resizeEvent 1056
#define sipName_resizeEvent &sipStrings_QtSvg[1056]
#define sipNameNr_changeEvent 1068
#define sipName_changeEvent &sipStrings_QtSvg[1068]
#define sipNameNr_customEvent 1080
#define sipName_customEvent &sipStrings_QtSvg[1080]
#define sipNameNr_eventFilter 1092
#define sipName_eventFilter &sipStrings_QtSvg[1092]
#define sipNameNr_setFileName 1104
#define sipName_setFileName &sipStrings_QtSvg[1104]
#define sipNameNr_PyQt4_QtSvg 1116
#define sipName_PyQt4_QtSvg &sipStrings_QtSvg[1116]
#define sipNameNr_QSvgWidget 1128
#define sipName_QSvgWidget &sipStrings_QtSvg[1128]
#define sipNameNr_setViewBox 1139
#define sipName_setViewBox &sipStrings_QtSvg[1139]
#define sipNameNr_resolution 1150
#define sipName_resolution &sipStrings_QtSvg[1150]
#define sipNameNr_redirected 1161
#define sipName_redirected &sipStrings_QtSvg[1161]
#define sipNameNr_enterEvent 1172
#define sipName_enterEvent &sipStrings_QtSvg[1172]
#define sipNameNr_leaveEvent 1183
#define sipName_leaveEvent &sipStrings_QtSvg[1183]
#define sipNameNr_sceneEvent 1194
#define sipName_sceneEvent &sipStrings_QtSvg[1194]
#define sipNameNr_itemChange 1205
#define sipName_itemChange &sipStrings_QtSvg[1205]
#define sipNameNr_opaqueArea 1216
#define sipName_opaqueArea &sipStrings_QtSvg[1216]
#define sipNameNr_setVisible 1227
#define sipName_setVisible &sipStrings_QtSvg[1227]
#define sipNameNr_closeEvent 1238
#define sipName_closeEvent &sipStrings_QtSvg[1238]
#define sipNameNr_wheelEvent 1249
#define sipName_wheelEvent &sipStrings_QtSvg[1249]
#define sipNameNr_paintEvent 1260
#define sipName_paintEvent &sipStrings_QtSvg[1260]
#define sipNameNr_fieldwidth 1271
#define sipName_fieldwidth &sipStrings_QtSvg[1271]
#define sipNameNr_fieldWidth 1282
#define sipName_fieldWidth &sipStrings_QtSvg[1282]
#define sipNameNr_childEvent 1293
#define sipName_childEvent &sipStrings_QtSvg[1293]
#define sipNameNr_timerEvent 1304
#define sipName_timerEvent &sipStrings_QtSvg[1304]
#define sipNameNr_elementId 1315
#define sipName_elementId &sipStrings_QtSvg[1315]
#define sipNameNr_operation 1325
#define sipName_operation &sipStrings_QtSvg[1325]
#define sipNameNr_moveEvent 1335
#define sipName_moveEvent &sipStrings_QtSvg[1335]
#define sipNameNr_lineWidth 1345
#define sipName_lineWidth &sipStrings_QtSvg[1345]
#define sipNameNr_showEvent 1355
#define sipName_showEvent &sipStrings_QtSvg[1355]
#define sipNameNr_hideEvent 1365
#define sipName_hideEvent &sipStrings_QtSvg[1365]
#define sipNameNr_dropEvent 1375
#define sipName_dropEvent &sipStrings_QtSvg[1375]
#define sipNameNr_directory 1385
#define sipName_directory &sipStrings_QtSvg[1385]
#define sipNameNr_alignment 1395
#define sipName_alignment &sipStrings_QtSvg[1395]
#define sipNameNr_precision 1405
#define sipName_precision &sipStrings_QtSvg[1405]
#define sipNameNr_animated 1415
#define sipName_animated &sipStrings_QtSvg[1415]
#define sipNameNr_viewBoxF 1424
#define sipName_viewBoxF &sipStrings_QtSvg[1424]
#define sipNameNr_renderer 1433
#define sipName_renderer &sipStrings_QtSvg[1433]
#define sipNameNr_setTitle 1442
#define sipName_setTitle &sipStrings_QtSvg[1442]
#define sipNameNr_fillRule 1451
#define sipName_fillRule &sipStrings_QtSvg[1451]
#define sipNameNr_tabArray 1460
#define sipName_tabArray &sipStrings_QtSvg[1460]
#define sipNameNr_tabStops 1469
#define sipName_tabStops &sipStrings_QtSvg[1469]
#define sipNameNr_userData 1478
#define sipName_userData &sipStrings_QtSvg[1478]
#define sipNameNr_sizeHint 1487
#define sipName_sizeHint &sipStrings_QtSvg[1487]
#define sipNameNr_shortcut 1496
#define sipName_shortcut &sipStrings_QtSvg[1496]
#define sipNameNr_behavior 1505
#define sipName_behavior &sipStrings_QtSvg[1505]
#define sipNameNr_position 1514
#define sipName_position &sipStrings_QtSvg[1514]
#define sipNameNr_fillChar 1523
#define sipName_fillChar &sipStrings_QtSvg[1523]
#define sipNameNr_encoding 1532
#define sipName_encoding &sipStrings_QtSvg[1532]
#define sipNameNr_contains 1541
#define sipName_contains &sipStrings_QtSvg[1541]
#define sipNameNr_fileName 1550
#define sipName_fileName &sipStrings_QtSvg[1550]
#define sipNameNr_viewBox 1559
#define sipName_viewBox &sipStrings_QtSvg[1559]
#define sipNameNr_exposed 1567
#define sipName_exposed &sipStrings_QtSvg[1567]
#define sipNameNr_button2 1575
#define sipName_button2 &sipStrings_QtSvg[1575]
#define sipNameNr_button1 1583
#define sipName_button1 &sipStrings_QtSvg[1583]
#define sipNameNr_quality 1591
#define sipName_quality &sipStrings_QtSvg[1591]
#define sipNameNr_devType 1599
#define sipName_devType &sipStrings_QtSvg[1599]
#define sipNameNr_advance 1607
#define sipName_advance &sipStrings_QtSvg[1607]
#define sipNameNr_yMargin 1615
#define sipName_yMargin &sipStrings_QtSvg[1615]
#define sipNameNr_xMargin 1623
#define sipName_xMargin &sipStrings_QtSvg[1623]
#define sipNameNr_caption 1631
#define sipName_caption &sipStrings_QtSvg[1631]
#define sipNameNr_setSize 1639
#define sipName_setSize &sipStrings_QtSvg[1639]
#define sipNameNr_options 1647
#define sipName_options &sipStrings_QtSvg[1647]
#define sipNameNr_isValid 1655
#define sipName_isValid &sipStrings_QtSvg[1655]
#define sipNameNr_filters 1663
#define sipName_filters &sipStrings_QtSvg[1663]
#define sipNameNr_bounds 1671
#define sipName_bounds &sipStrings_QtSvg[1671]
#define sipNameNr_yRound 1678
#define sipName_yRound &sipStrings_QtSvg[1678]
#define sipNameNr_xRound 1685
#define sipName_xRound &sipStrings_QtSvg[1685]
#define sipNameNr_metric 1692
#define sipName_metric &sipStrings_QtSvg[1692]
#define sipNameNr_layers 1699
#define sipName_layers &sipStrings_QtSvg[1699]
#define sipNameNr_render 1706
#define sipName_render &sipStrings_QtSvg[1706]
#define sipNameNr_sunken 1713
#define sipName_sunken &sipStrings_QtSvg[1713]
#define sipNameNr_option 1720
#define sipName_option &sipStrings_QtSvg[1720]
#define sipNameNr_widget 1727
#define sipName_widget &sipStrings_QtSvg[1727]
#define sipNameNr_proper 1734
#define sipName_proper &sipStrings_QtSvg[1734]
#define sipNameNr_value9 1741
#define sipName_value9 &sipStrings_QtSvg[1741]
#define sipNameNr_value8 1748
#define sipName_value8 &sipStrings_QtSvg[1748]
#define sipNameNr_value7 1755
#define sipName_value7 &sipStrings_QtSvg[1755]
#define sipNameNr_value6 1762
#define sipName_value6 &sipStrings_QtSvg[1762]
#define sipNameNr_value5 1769
#define sipName_value5 &sipStrings_QtSvg[1769]
#define sipNameNr_value4 1776
#define sipName_value4 &sipStrings_QtSvg[1776]
#define sipNameNr_value3 1783
#define sipName_value3 &sipStrings_QtSvg[1783]
#define sipNameNr_value2 1790
#define sipName_value2 &sipStrings_QtSvg[1790]
#define sipNameNr_value1 1797
#define sipName_value1 &sipStrings_QtSvg[1797]
#define sipNameNr_value0 1804
#define sipName_value0 &sipStrings_QtSvg[1804]
#define sipNameNr_symbol 1811
#define sipName_symbol &sipStrings_QtSvg[1811]
#define sipNameNr_suffix 1818
#define sipName_suffix &sipStrings_QtSvg[1818]
#define sipNameNr_prefix 1825
#define sipName_prefix &sipStrings_QtSvg[1825]
#define sipNameNr_format 1832
#define sipName_format &sipStrings_QtSvg[1832]
#define sipNameNr_column 1839
#define sipName_column &sipStrings_QtSvg[1839]
#define sipNameNr_filter 1846
#define sipName_filter &sipStrings_QtSvg[1846]
#define sipNameNr_parent 1853
#define sipName_parent &sipStrings_QtSvg[1853]
#define sipNameNr_title 1860
#define sipName_title &sipStrings_QtSvg[1860]
#define sipNameNr_brush 1866
#define sipName_brush &sipStrings_QtSvg[1866]
#define sipNameNr_paint 1872
#define sipName_paint &sipStrings_QtSvg[1872]
#define sipNameNr_shape 1878
#define sipName_shape &sipStrings_QtSvg[1878]
#define sipNameNr_order 1884
#define sipName_order &sipStrings_QtSvg[1884]
#define sipNameNr_flags 1890
#define sipName_flags &sipStrings_QtSvg[1890]
#define sipNameNr_event 1896
#define sipName_event &sipStrings_QtSvg[1896]
#define sipNameNr_msecs 1902
#define sipName_msecs &sipStrings_QtSvg[1902]
#define sipNameNr_state 1908
#define sipName_state &sipStrings_QtSvg[1908]
#define sipNameNr_load 1914
#define sipName_load &sipStrings_QtSvg[1914]
#define sipNameNr_mode 1919
#define sipName_mode &sipStrings_QtSvg[1919]
#define sipNameNr_name 1924
#define sipName_name &sipStrings_QtSvg[1924]
#define sipNameNr_base 1929
#define sipName_base &sipStrings_QtSvg[1929]
#define sipNameNr_fill 1934
#define sipName_fill &sipStrings_QtSvg[1934]
#define sipNameNr_from 1939
#define sipName_from &sipStrings_QtSvg[1939]
#define sipNameNr_sort 1944
#define sipName_sort &sipStrings_QtSvg[1944]
#define sipNameNr_type 1949
#define sipName_type &sipStrings_QtSvg[1949]
#define sipNameNr_size 1954
#define sipName_size &sipStrings_QtSvg[1954]
#define sipNameNr_pen 1959
#define sipName_pen &sipStrings_QtSvg[1959]
#define sipNameNr_end 1963
#define sipName_end &sipStrings_QtSvg[1963]
#define sipNameNr_pos 1967
#define sipName_pos &sipStrings_QtSvg[1967]
#define sipNameNr_sw 1971
#define sipName_sw &sipStrings_QtSvg[1971]
#define sipNameNr_sy 1974
#define sipName_sy &sipStrings_QtSvg[1974]
#define sipNameNr_sx 1977
#define sipName_sx &sipStrings_QtSvg[1977]
#define sipNameNr_sh 1869
#define sipName_sh &sipStrings_QtSvg[1869]
#define sipNameNr_cs 1905
#define sipName_cs &sipStrings_QtSvg[1905]
#define sipNameNr_at 1836
#define sipName_at &sipStrings_QtSvg[1836]

#define sipMalloc                   sipAPI_QtSvg->api_malloc
#define sipFree                     sipAPI_QtSvg->api_free
#define sipBuildResult              sipAPI_QtSvg->api_build_result
#define sipCallMethod               sipAPI_QtSvg->api_call_method
#define sipCallProcedureMethod      sipAPI_QtSvg->api_call_procedure_method
#define sipCallErrorHandler         sipAPI_QtSvg->api_call_error_handler
#define sipParseResultEx            sipAPI_QtSvg->api_parse_result_ex
#define sipParseResult              sipAPI_QtSvg->api_parse_result
#define sipParseArgs                sipAPI_QtSvg->api_parse_args
#define sipParseKwdArgs             sipAPI_QtSvg->api_parse_kwd_args
#define sipParsePair                sipAPI_QtSvg->api_parse_pair
#define sipInstanceDestroyed        sipAPI_QtSvg->api_instance_destroyed
#define sipInstanceDestroyedEx      sipAPI_QtSvg->api_instance_destroyed_ex
#define sipConvertFromSequenceIndex sipAPI_QtSvg->api_convert_from_sequence_index
#define sipConvertFromVoidPtr       sipAPI_QtSvg->api_convert_from_void_ptr
#define sipConvertToVoidPtr         sipAPI_QtSvg->api_convert_to_void_ptr
#define sipAddException             sipAPI_QtSvg->api_add_exception
#define sipNoFunction               sipAPI_QtSvg->api_no_function
#define sipNoMethod                 sipAPI_QtSvg->api_no_method
#define sipAbstractMethod           sipAPI_QtSvg->api_abstract_method
#define sipBadClass                 sipAPI_QtSvg->api_bad_class
#define sipBadCatcherResult         sipAPI_QtSvg->api_bad_catcher_result
#define sipBadCallableArg           sipAPI_QtSvg->api_bad_callable_arg
#define sipBadOperatorArg           sipAPI_QtSvg->api_bad_operator_arg
#define sipTrace                    sipAPI_QtSvg->api_trace
#define sipTransferBack             sipAPI_QtSvg->api_transfer_back
#define sipTransferTo               sipAPI_QtSvg->api_transfer_to
#define sipTransferBreak            sipAPI_QtSvg->api_transfer_break
#define sipSimpleWrapper_Type       sipAPI_QtSvg->api_simplewrapper_type
#define sipWrapper_Type             sipAPI_QtSvg->api_wrapper_type
#define sipWrapperType_Type         sipAPI_QtSvg->api_wrappertype_type
#define sipVoidPtr_Type             sipAPI_QtSvg->api_voidptr_type
#define sipGetPyObject              sipAPI_QtSvg->api_get_pyobject
#define sipGetAddress               sipAPI_QtSvg->api_get_address
#define sipGetMixinAddress          sipAPI_QtSvg->api_get_mixin_address
#define sipGetCppPtr                sipAPI_QtSvg->api_get_cpp_ptr
#define sipGetComplexCppPtr         sipAPI_QtSvg->api_get_complex_cpp_ptr
#define sipIsPyMethod               sipAPI_QtSvg->api_is_py_method
#define sipCallHook                 sipAPI_QtSvg->api_call_hook
#define sipEndThread                sipAPI_QtSvg->api_end_thread
#define sipConnectRx                sipAPI_QtSvg->api_connect_rx
#define sipDisconnectRx             sipAPI_QtSvg->api_disconnect_rx
#define sipRaiseUnknownException    sipAPI_QtSvg->api_raise_unknown_exception
#define sipRaiseTypeException       sipAPI_QtSvg->api_raise_type_exception
#define sipBadLengthForSlice        sipAPI_QtSvg->api_bad_length_for_slice
#define sipAddTypeInstance          sipAPI_QtSvg->api_add_type_instance
#define sipFreeSipslot              sipAPI_QtSvg->api_free_sipslot
#define sipSameSlot                 sipAPI_QtSvg->api_same_slot
#define sipPySlotExtend             sipAPI_QtSvg->api_pyslot_extend
#define sipConvertRx                sipAPI_QtSvg->api_convert_rx
#define sipAddDelayedDtor           sipAPI_QtSvg->api_add_delayed_dtor
#define sipCanConvertToType         sipAPI_QtSvg->api_can_convert_to_type
#define sipConvertToType            sipAPI_QtSvg->api_convert_to_type
#define sipForceConvertToType       sipAPI_QtSvg->api_force_convert_to_type
#define sipCanConvertToEnum         sipAPI_QtSvg->api_can_convert_to_enum
#define sipConvertToEnum            sipAPI_QtSvg->api_convert_to_enum
#define sipConvertToBool            sipAPI_QtSvg->api_convert_to_bool
#define sipReleaseType              sipAPI_QtSvg->api_release_type
#define sipConvertFromType          sipAPI_QtSvg->api_convert_from_type
#define sipConvertFromNewType       sipAPI_QtSvg->api_convert_from_new_type
#define sipConvertFromNewPyType     sipAPI_QtSvg->api_convert_from_new_pytype
#define sipConvertFromEnum          sipAPI_QtSvg->api_convert_from_enum
#define sipGetState                 sipAPI_QtSvg->api_get_state
#define sipExportSymbol             sipAPI_QtSvg->api_export_symbol
#define sipImportSymbol             sipAPI_QtSvg->api_import_symbol
#define sipFindType                 sipAPI_QtSvg->api_find_type
#define sipFindNamedEnum            sipAPI_QtSvg->api_find_named_enum
#define sipBytes_AsChar             sipAPI_QtSvg->api_bytes_as_char
#define sipBytes_AsString           sipAPI_QtSvg->api_bytes_as_string
#define sipString_AsASCIIChar       sipAPI_QtSvg->api_string_as_ascii_char
#define sipString_AsASCIIString     sipAPI_QtSvg->api_string_as_ascii_string
#define sipString_AsLatin1Char      sipAPI_QtSvg->api_string_as_latin1_char
#define sipString_AsLatin1String    sipAPI_QtSvg->api_string_as_latin1_string
#define sipString_AsUTF8Char        sipAPI_QtSvg->api_string_as_utf8_char
#define sipString_AsUTF8String      sipAPI_QtSvg->api_string_as_utf8_string
#define sipUnicode_AsWChar          sipAPI_QtSvg->api_unicode_as_wchar
#define sipUnicode_AsWString        sipAPI_QtSvg->api_unicode_as_wstring
#define sipConvertFromConstVoidPtr  sipAPI_QtSvg->api_convert_from_const_void_ptr
#define sipConvertFromVoidPtrAndSize    sipAPI_QtSvg->api_convert_from_void_ptr_and_size
#define sipConvertFromConstVoidPtrAndSize   sipAPI_QtSvg->api_convert_from_const_void_ptr_and_size
#define sipInvokeSlot               sipAPI_QtSvg->api_invoke_slot
#define sipInvokeSlotEx             sipAPI_QtSvg->api_invoke_slot_ex
#define sipSaveSlot                 sipAPI_QtSvg->api_save_slot
#define sipClearAnySlotReference    sipAPI_QtSvg->api_clear_any_slot_reference
#define sipVisitSlot                sipAPI_QtSvg->api_visit_slot
#define sipWrappedTypeName(wt)      ((wt)->wt_td->td_cname)
#define sipDeprecated               sipAPI_QtSvg->api_deprecated
#define sipGetReference             sipAPI_QtSvg->api_get_reference
#define sipKeepReference            sipAPI_QtSvg->api_keep_reference
#define sipRegisterProxyResolver    sipAPI_QtSvg->api_register_proxy_resolver
#define sipRegisterPyType           sipAPI_QtSvg->api_register_py_type
#define sipTypeFromPyTypeObject     sipAPI_QtSvg->api_type_from_py_type_object
#define sipTypeScope                sipAPI_QtSvg->api_type_scope
#define sipResolveTypedef           sipAPI_QtSvg->api_resolve_typedef
#define sipRegisterAttributeGetter  sipAPI_QtSvg->api_register_attribute_getter
#define sipIsAPIEnabled             sipAPI_QtSvg->api_is_api_enabled
#define sipSetDestroyOnExit         sipAPI_QtSvg->api_set_destroy_on_exit
#define sipEnableAutoconversion     sipAPI_QtSvg->api_enable_autoconversion
#define sipEnableOverflowChecking   sipAPI_QtSvg->api_enable_overflow_checking
#define sipInitMixin                sipAPI_QtSvg->api_init_mixin
#define sipExportModule             sipAPI_QtSvg->api_export_module
#define sipInitModule               sipAPI_QtSvg->api_init_module
#define sipGetInterpreter           sipAPI_QtSvg->api_get_interpreter
#define sipSetNewUserTypeHandler    sipAPI_QtSvg->api_set_new_user_type_handler
#define sipSetTypeUserData          sipAPI_QtSvg->api_set_type_user_data
#define sipGetTypeUserData          sipAPI_QtSvg->api_get_type_user_data
#define sipPyTypeDict               sipAPI_QtSvg->api_py_type_dict
#define sipPyTypeName               sipAPI_QtSvg->api_py_type_name
#define sipGetCFunction             sipAPI_QtSvg->api_get_c_function
#define sipGetMethod                sipAPI_QtSvg->api_get_method
#define sipFromMethod               sipAPI_QtSvg->api_from_method
#define sipGetDate                  sipAPI_QtSvg->api_get_date
#define sipFromDate                 sipAPI_QtSvg->api_from_date
#define sipGetDateTime              sipAPI_QtSvg->api_get_datetime
#define sipFromDateTime             sipAPI_QtSvg->api_from_datetime
#define sipGetTime                  sipAPI_QtSvg->api_get_time
#define sipFromTime                 sipAPI_QtSvg->api_from_time
#define sipIsUserType               sipAPI_QtSvg->api_is_user_type
#define sipGetFrame                 sipAPI_QtSvg->api_get_frame
#define sipCheckPluginForType       sipAPI_QtSvg->api_check_plugin_for_type
#define sipUnicodeNew               sipAPI_QtSvg->api_unicode_new
#define sipUnicodeWrite             sipAPI_QtSvg->api_unicode_write
#define sipUnicodeData              sipAPI_QtSvg->api_unicode_data
#define sipGetBufferInfo            sipAPI_QtSvg->api_get_buffer_info
#define sipReleaseBufferInfo        sipAPI_QtSvg->api_release_buffer_info
#define sipIsOwnedByPython          sipAPI_QtSvg->api_is_owned_by_python
#define sipIsDerivedClass           sipAPI_QtSvg->api_is_derived_class
#define sipGetUserObject            sipAPI_QtSvg->api_get_user_object
#define sipSetUserObject            sipAPI_QtSvg->api_set_user_object
#define sipRegisterEventHandler     sipAPI_QtSvg->api_register_event_handler
#define sipLong_AsChar              sipAPI_QtSvg->api_long_as_char
#define sipLong_AsSignedChar        sipAPI_QtSvg->api_long_as_signed_char
#define sipLong_AsUnsignedChar      sipAPI_QtSvg->api_long_as_unsigned_char
#define sipLong_AsShort             sipAPI_QtSvg->api_long_as_short
#define sipLong_AsUnsignedShort     sipAPI_QtSvg->api_long_as_unsigned_short
#define sipLong_AsInt               sipAPI_QtSvg->api_long_as_int
#define sipLong_AsUnsignedInt       sipAPI_QtSvg->api_long_as_unsigned_int
#define sipLong_AsLong              sipAPI_QtSvg->api_long_as_long
#define sipLong_AsUnsignedLong      sipAPI_QtSvg->api_long_as_unsigned_long
#define sipLong_AsLongLong          sipAPI_QtSvg->api_long_as_long_long
#define sipLong_AsUnsignedLongLong  sipAPI_QtSvg->api_long_as_unsigned_long_long

/* These are deprecated. */
#define sipMapStringToClass         sipAPI_QtSvg->api_map_string_to_class
#define sipMapIntToClass            sipAPI_QtSvg->api_map_int_to_class
#define sipFindClass                sipAPI_QtSvg->api_find_class
#define sipFindMappedType           sipAPI_QtSvg->api_find_mapped_type
#define sipConvertToArray           sipAPI_QtSvg->api_convert_to_array
#define sipConvertToTypedArray      sipAPI_QtSvg->api_convert_to_typed_array
#define sipEnableGC                 sipAPI_QtSvg->api_enable_gc
#define sipPrintObject              sipAPI_QtSvg->api_print_object
#define sipWrapper_Check(w)         PyObject_TypeCheck((w), sipAPI_QtSvg->api_wrapper_type)
#define sipGetWrapper(p, wt)        sipGetPyObject((p), (wt)->wt_td)
#define sipReleaseInstance(p, wt, s)    sipReleaseType((p), (wt)->wt_td, (s))
#define sipReleaseMappedType        sipReleaseType
#define sipCanConvertToInstance(o, wt, f)   sipCanConvertToType((o), (wt)->wt_td, (f))
#define sipCanConvertToMappedType   sipCanConvertToType
#define sipConvertToInstance(o, wt, t, f, s, e)     sipConvertToType((o), (wt)->wt_td, (t), (f), (s), (e))
#define sipConvertToMappedType      sipConvertToType
#define sipForceConvertToInstance(o, wt, t, f, s, e)    sipForceConvertToType((o), (wt)->wt_td, (t), (f), (s), (e))
#define sipForceConvertToMappedType sipForceConvertToType
#define sipConvertFromInstance(p, wt, t)    sipConvertFromType((p), (wt)->wt_td, (t))
#define sipConvertFromMappedType    sipConvertFromType
#define sipConvertFromNamedEnum(v, pt)  sipConvertFromEnum((v), ((sipEnumTypeObject *)(pt))->type)
#define sipConvertFromNewInstance(p, wt, t) sipConvertFromNewType((p), (wt)->wt_td, (t))

/* The strings used by this module. */
extern const char sipStrings_QtSvg[];

#define sipType_QGraphicsSvgItem sipExportedTypes_QtSvg[0]
#define sipClass_QGraphicsSvgItem sipExportedTypes_QtSvg[0]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtSvg_QGraphicsSvgItem;

#define sipType_QSvgGenerator sipExportedTypes_QtSvg[1]
#define sipClass_QSvgGenerator sipExportedTypes_QtSvg[1]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtSvg_QSvgGenerator;

#define sipType_QSvgRenderer sipExportedTypes_QtSvg[2]
#define sipClass_QSvgRenderer sipExportedTypes_QtSvg[2]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtSvg_QSvgRenderer;

#define sipType_QSvgWidget sipExportedTypes_QtSvg[3]
#define sipClass_QSvgWidget sipExportedTypes_QtSvg[3]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtSvg_QSvgWidget;

/* The SIP API, this module's API and the APIs of any imported modules. */
extern const sipAPIDef *sipAPI_QtSvg;
extern sipExportedModuleDef sipModuleAPI_QtSvg;
extern sipTypeDef *sipExportedTypes_QtSvg[];

#define sipType_Qt_ItemSelectionMode sipImportedTypes_QtSvg_QtCore[16].it_td
#define sipEnum_Qt_ItemSelectionMode sipImportedTypes_QtSvg_QtCore[16].it_td->u.td_py_type

#define sipType_Qt_InputMethodQuery sipImportedTypes_QtSvg_QtCore[15].it_td
#define sipEnum_Qt_InputMethodQuery sipImportedTypes_QtSvg_QtCore[15].it_td->u.td_py_type

#define sipType_QObject sipImportedTypes_QtSvg_QtCore[5].it_td
#define sipClass_QObject sipImportedTypes_QtSvg_QtCore[5].it_td->u.td_wrapper_type

#define sipType_QIODevice sipImportedTypes_QtSvg_QtCore[3].it_td
#define sipClass_QIODevice sipImportedTypes_QtSvg_QtCore[3].it_td->u.td_wrapper_type

#define sipType_QByteArray sipImportedTypes_QtSvg_QtCore[0].it_td
#define sipClass_QByteArray sipImportedTypes_QtSvg_QtCore[0].it_td->u.td_wrapper_type

#define sipType_QEvent sipImportedTypes_QtSvg_QtCore[2].it_td
#define sipClass_QEvent sipImportedTypes_QtSvg_QtCore[2].it_td->u.td_wrapper_type

#define sipType_QTimerEvent sipImportedTypes_QtSvg_QtCore[12].it_td
#define sipClass_QTimerEvent sipImportedTypes_QtSvg_QtCore[12].it_td->u.td_wrapper_type

#define sipType_QChildEvent sipImportedTypes_QtSvg_QtCore[1].it_td
#define sipClass_QChildEvent sipImportedTypes_QtSvg_QtCore[1].it_td->u.td_wrapper_type

#define sipType_QMetaMethod sipImportedTypes_QtSvg_QtCore[4].it_td
#define sipClass_QMetaMethod sipImportedTypes_QtSvg_QtCore[4].it_td->u.td_wrapper_type

#define sipType_QPoint sipImportedTypes_QtSvg_QtCore[6].it_td
#define sipClass_QPoint sipImportedTypes_QtSvg_QtCore[6].it_td->u.td_wrapper_type

#define sipType_QPointF sipImportedTypes_QtSvg_QtCore[7].it_td
#define sipClass_QPointF sipImportedTypes_QtSvg_QtCore[7].it_td->u.td_wrapper_type

#define sipType_QRect sipImportedTypes_QtSvg_QtCore[8].it_td
#define sipClass_QRect sipImportedTypes_QtSvg_QtCore[8].it_td->u.td_wrapper_type

#define sipType_QRectF sipImportedTypes_QtSvg_QtCore[9].it_td
#define sipClass_QRectF sipImportedTypes_QtSvg_QtCore[9].it_td->u.td_wrapper_type

#define sipType_QSize sipImportedTypes_QtSvg_QtCore[10].it_td
#define sipClass_QSize sipImportedTypes_QtSvg_QtCore[10].it_td->u.td_wrapper_type

#define sipType_QVariant sipImportedTypes_QtSvg_QtCore[13].it_td
#define sipClass_QVariant sipImportedTypes_QtSvg_QtCore[13].it_td->u.td_wrapper_type

#define sipType_QXmlStreamReader sipImportedTypes_QtSvg_QtCore[14].it_td
#define sipClass_QXmlStreamReader sipImportedTypes_QtSvg_QtCore[14].it_td->u.td_wrapper_type

#define sipType_QString sipImportedTypes_QtSvg_QtCore[11].it_td
extern sipImportedTypeDef sipImportedTypes_QtSvg_QtCore[];

#define sipType_QPaintDevice sipImportedTypes_QtSvg_QtGui[22].it_td
#define sipClass_QPaintDevice sipImportedTypes_QtSvg_QtGui[22].it_td->u.td_wrapper_type

#define sipType_QPaintDevice_PaintDeviceMetric sipImportedTypes_QtSvg_QtGui[23].it_td
#define sipEnum_QPaintDevice_PaintDeviceMetric sipImportedTypes_QtSvg_QtGui[23].it_td->u.td_py_type

#define sipType_QWidget sipImportedTypes_QtSvg_QtGui[33].it_td
#define sipClass_QWidget sipImportedTypes_QtSvg_QtGui[33].it_td->u.td_wrapper_type

#define sipType_QMouseEvent sipImportedTypes_QtSvg_QtGui[20].it_td
#define sipClass_QMouseEvent sipImportedTypes_QtSvg_QtGui[20].it_td->u.td_wrapper_type

#define sipType_QWheelEvent sipImportedTypes_QtSvg_QtGui[32].it_td
#define sipClass_QWheelEvent sipImportedTypes_QtSvg_QtGui[32].it_td->u.td_wrapper_type

#define sipType_QTabletEvent sipImportedTypes_QtSvg_QtGui[31].it_td
#define sipClass_QTabletEvent sipImportedTypes_QtSvg_QtGui[31].it_td->u.td_wrapper_type

#define sipType_QKeyEvent sipImportedTypes_QtSvg_QtGui[18].it_td
#define sipClass_QKeyEvent sipImportedTypes_QtSvg_QtGui[18].it_td->u.td_wrapper_type

#define sipType_QFocusEvent sipImportedTypes_QtSvg_QtGui[7].it_td
#define sipClass_QFocusEvent sipImportedTypes_QtSvg_QtGui[7].it_td->u.td_wrapper_type

#define sipType_QPaintEvent sipImportedTypes_QtSvg_QtGui[25].it_td
#define sipClass_QPaintEvent sipImportedTypes_QtSvg_QtGui[25].it_td->u.td_wrapper_type

#define sipType_QMoveEvent sipImportedTypes_QtSvg_QtGui[21].it_td
#define sipClass_QMoveEvent sipImportedTypes_QtSvg_QtGui[21].it_td->u.td_wrapper_type

#define sipType_QResizeEvent sipImportedTypes_QtSvg_QtGui[28].it_td
#define sipClass_QResizeEvent sipImportedTypes_QtSvg_QtGui[28].it_td->u.td_wrapper_type

#define sipType_QCloseEvent sipImportedTypes_QtSvg_QtGui[1].it_td
#define sipClass_QCloseEvent sipImportedTypes_QtSvg_QtGui[1].it_td->u.td_wrapper_type

#define sipType_QShowEvent sipImportedTypes_QtSvg_QtGui[29].it_td
#define sipClass_QShowEvent sipImportedTypes_QtSvg_QtGui[29].it_td->u.td_wrapper_type

#define sipType_QHideEvent sipImportedTypes_QtSvg_QtGui[16].it_td
#define sipClass_QHideEvent sipImportedTypes_QtSvg_QtGui[16].it_td->u.td_wrapper_type

#define sipType_QContextMenuEvent sipImportedTypes_QtSvg_QtGui[2].it_td
#define sipClass_QContextMenuEvent sipImportedTypes_QtSvg_QtGui[2].it_td->u.td_wrapper_type

#define sipType_QInputMethodEvent sipImportedTypes_QtSvg_QtGui[17].it_td
#define sipClass_QInputMethodEvent sipImportedTypes_QtSvg_QtGui[17].it_td->u.td_wrapper_type

#define sipType_QDropEvent sipImportedTypes_QtSvg_QtGui[6].it_td
#define sipClass_QDropEvent sipImportedTypes_QtSvg_QtGui[6].it_td->u.td_wrapper_type

#define sipType_QDragMoveEvent sipImportedTypes_QtSvg_QtGui[5].it_td
#define sipClass_QDragMoveEvent sipImportedTypes_QtSvg_QtGui[5].it_td->u.td_wrapper_type

#define sipType_QDragEnterEvent sipImportedTypes_QtSvg_QtGui[3].it_td
#define sipClass_QDragEnterEvent sipImportedTypes_QtSvg_QtGui[3].it_td->u.td_wrapper_type

#define sipType_QDragLeaveEvent sipImportedTypes_QtSvg_QtGui[4].it_td
#define sipClass_QDragLeaveEvent sipImportedTypes_QtSvg_QtGui[4].it_td->u.td_wrapper_type

#define sipType_QActionEvent sipImportedTypes_QtSvg_QtGui[0].it_td
#define sipClass_QActionEvent sipImportedTypes_QtSvg_QtGui[0].it_td->u.td_wrapper_type

#define sipType_QGraphicsItem sipImportedTypes_QtSvg_QtGui[8].it_td
#define sipClass_QGraphicsItem sipImportedTypes_QtSvg_QtGui[8].it_td->u.td_wrapper_type

#define sipType_QGraphicsItem_GraphicsItemChange sipImportedTypes_QtSvg_QtGui[9].it_td
#define sipEnum_QGraphicsItem_GraphicsItemChange sipImportedTypes_QtSvg_QtGui[9].it_td->u.td_py_type

#define sipType_QGraphicsObject sipImportedTypes_QtSvg_QtGui[10].it_td
#define sipClass_QGraphicsObject sipImportedTypes_QtSvg_QtGui[10].it_td->u.td_wrapper_type

#define sipType_QGraphicsSceneMouseEvent sipImportedTypes_QtSvg_QtGui[14].it_td
#define sipClass_QGraphicsSceneMouseEvent sipImportedTypes_QtSvg_QtGui[14].it_td->u.td_wrapper_type

#define sipType_QGraphicsSceneWheelEvent sipImportedTypes_QtSvg_QtGui[15].it_td
#define sipClass_QGraphicsSceneWheelEvent sipImportedTypes_QtSvg_QtGui[15].it_td->u.td_wrapper_type

#define sipType_QGraphicsSceneContextMenuEvent sipImportedTypes_QtSvg_QtGui[11].it_td
#define sipClass_QGraphicsSceneContextMenuEvent sipImportedTypes_QtSvg_QtGui[11].it_td->u.td_wrapper_type

#define sipType_QGraphicsSceneHoverEvent sipImportedTypes_QtSvg_QtGui[13].it_td
#define sipClass_QGraphicsSceneHoverEvent sipImportedTypes_QtSvg_QtGui[13].it_td->u.td_wrapper_type

#define sipType_QGraphicsSceneDragDropEvent sipImportedTypes_QtSvg_QtGui[12].it_td
#define sipClass_QGraphicsSceneDragDropEvent sipImportedTypes_QtSvg_QtGui[12].it_td->u.td_wrapper_type

#define sipType_QMatrix sipImportedTypes_QtSvg_QtGui[19].it_td
#define sipClass_QMatrix sipImportedTypes_QtSvg_QtGui[19].it_td->u.td_wrapper_type

#define sipType_QPainter sipImportedTypes_QtSvg_QtGui[26].it_td
#define sipClass_QPainter sipImportedTypes_QtSvg_QtGui[26].it_td->u.td_wrapper_type

#define sipType_QPaintEngine sipImportedTypes_QtSvg_QtGui[24].it_td
#define sipClass_QPaintEngine sipImportedTypes_QtSvg_QtGui[24].it_td->u.td_wrapper_type

#define sipType_QPainterPath sipImportedTypes_QtSvg_QtGui[27].it_td
#define sipClass_QPainterPath sipImportedTypes_QtSvg_QtGui[27].it_td->u.td_wrapper_type

#define sipType_QStyleOptionGraphicsItem sipImportedTypes_QtSvg_QtGui[30].it_td
#define sipClass_QStyleOptionGraphicsItem sipImportedTypes_QtSvg_QtGui[30].it_td->u.td_wrapper_type
extern sipImportedTypeDef sipImportedTypes_QtSvg_QtGui[];

typedef const QMetaObject *(*sip_qt_metaobject_func)(sipSimpleWrapper *,sipTypeDef *);
extern sip_qt_metaobject_func sip_QtSvg_qt_metaobject;

typedef int (*sip_qt_metacall_func)(sipSimpleWrapper *,sipTypeDef *,QMetaObject::Call,int,void **);
extern sip_qt_metacall_func sip_QtSvg_qt_metacall;

typedef int (*sip_qt_metacast_func)(sipSimpleWrapper *, sipTypeDef *, const char *);
extern sip_qt_metacast_func sip_QtSvg_qt_metacast;
#line 103 "/home/rodrigo/Documents/Ajedrez/Qt/PyQt4_gpl_win-4.12.1/sip/QtSvg/qgraphicssvgitem.sip"
#include <qglobal.h>

#if QT_VERSION >= 0x040200

// This is needed by the %ConvertToSubClassCode.
#include <qgraphicssvgitem.h>

#endif
#line 803 "/home/rodrigo/Documents/Ajedrez/Qt/PyQt4_gpl_win-4.12.1/QtSvg/sipAPIQtSvg.h"

#endif
