%CompositeModule PyQt4.Qt

%Include QtCore/QtCoremod.sip
%Include QtGui/QtGuimod.sip
%Include QtMultimedia/QtMultimediamod.sip
%Include QtNetwork/QtNetworkmod.sip
%Include QtDBus/QtDBusmod.sip
%Include QtOpenGL/QtOpenGLmod.sip
%Include QtSql/QtSqlmod.sip
%Include QtSvg/QtSvgmod.sip
%Include QtTest/QtTestmod.sip
%Include QtWebKit/QtWebKitmod.sip
%Include QtXml/QtXmlmod.sip
%Include QtXmlPatterns/QtXmlPatternsmod.sip
