/*
 * Internal module API header file.
 *
 * Generated by SIP 4.19.8
 *
 * Copyright (c) 2016 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of PyQt4.
 * 
 * This file may be used under the terms of the GNU General Public License
 * version 3.0 as published by the Free Software Foundation and appearing in
 * the file LICENSE included in the packaging of this file.  Please review the
 * following information to ensure the GNU General Public License version 3.0
 * requirements will be met: http://www.gnu.org/copyleft/gpl.html.
 * 
 * If you do not wish to use this file under the terms of the GPL version 3.0
 * then you may purchase a commercial license.  For more information contact
 * info@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#ifndef _QtXmlAPI_H
#define _QtXmlAPI_H

#include <sip.h>

#include <QMetaType>
#include <QThread>

/* These are the qualifiers that are enabled. */
#define SIP_FEATURE_PyQt_Process
#define SIP_FEATURE_PyQt_NotBootstrapped
#define SIP_FEATURE_PyQt_Deprecated_5_0
#define SIP_FEATURE_PyQt_NoOpenGLES
#define SIP_FEATURE_PyQt_RawFont
#define SIP_FEATURE_PyQt_SystemTrayIcon
#define SIP_FEATURE_PyQt_PrintPreviewDialog
#define SIP_FEATURE_PyQt_PrintPreviewWidget
#define SIP_FEATURE_PyQt_Printer
#define SIP_FEATURE_PyQt_PrintDialog
#define SIP_FEATURE_Py_v3
#define SIP_FEATURE_PyQt_qreal_double
#define SIP_FEATURE_PyQt_SizeGrip
#define SIP_FEATURE_PyQt_OpenSSL
#define SIP_FEATURE_Py_DateTime
#define SIP_FEATURE_PyQt_NoQtPrintRangeBug
#define SIP_FEATURE_PyQt_WhatsThis
#define SIP_FEATURE_PyQt_ToolTip
#define SIP_FEATURE_PyQt_StatusTip
#define SIP_FEATURE_PyQt_SessionManager
#define SIP_FEATURE_PyQt_Accessibility
#define SIP_PLATFORM_WS_X11
#define SIP_TIMELINE_Qt_5_0_0


/*
 * Convenient names to refer to various strings defined in this module.
 * Only the class names are part of the public API.
 */
#define sipNameNr_QDomImplementation__InvalidDataPolicy 0
#define sipName_QDomImplementation__InvalidDataPolicy &sipStrings_QtXml[0]
#define sipNameNr_PyQt4_QtCore_pyqtWrapperType 38
#define sipName_PyQt4_QtCore_pyqtWrapperType &sipStrings_QtXml[38]
#define sipNameNr_createProcessingInstruction 67
#define sipName_createProcessingInstruction &sipStrings_QtXml[67]
#define sipNameNr_QDomProcessingInstruction 95
#define sipName_QDomProcessingInstruction &sipStrings_QtXml[95]
#define sipNameNr_ProcessingInstructionNode 121
#define sipName_ProcessingInstructionNode &sipStrings_QtXml[121]
#define sipNameNr_QDomNode__EncodingPolicy 147
#define sipName_QDomNode__EncodingPolicy &sipStrings_QtXml[147]
#define sipNameNr_toProcessingInstruction 172
#define sipName_toProcessingInstruction &sipStrings_QtXml[172]
#define sipNameNr_isProcessingInstruction 196
#define sipName_isProcessingInstruction &sipStrings_QtXml[196]
#define sipNameNr_createDocumentFragment 220
#define sipName_createDocumentFragment &sipStrings_QtXml[220]
#define sipNameNr_EncodingFromTextStream 243
#define sipName_EncodingFromTextStream &sipStrings_QtXml[243]
#define sipNameNr_previousSiblingElement 266
#define sipName_previousSiblingElement &sipStrings_QtXml[266]
#define sipNameNr_processingInstruction 289
#define sipName_processingInstruction &sipStrings_QtXml[289]
#define sipNameNr_createEntityReference 311
#define sipName_createEntityReference &sipStrings_QtXml[311]
#define sipNameNr_QXmlNamespaceSupport 333
#define sipName_QXmlNamespaceSupport &sipStrings_QtXml[333]
#define sipNameNr_QDomDocumentFragment 354
#define sipName_QDomDocumentFragment &sipStrings_QtXml[354]
#define sipNameNr_EncodingFromDocument 375
#define sipName_EncodingFromDocument &sipStrings_QtXml[375]
#define sipNameNr_DocumentFragmentNode 396
#define sipName_DocumentFragmentNode &sipStrings_QtXml[396]
#define sipNameNr_setInvalidDataPolicy 417
#define sipName_setInvalidDataPolicy &sipStrings_QtXml[417]
#define sipNameNr_ignorableWhitespace 438
#define sipName_ignorableWhitespace &sipStrings_QtXml[438]
#define sipNameNr_QDomEntityReference 458
#define sipName_QDomEntityReference &sipStrings_QtXml[458]
#define sipNameNr_removeAttributeNode 478
#define sipName_removeAttributeNode &sipStrings_QtXml[478]
#define sipNameNr_elementsByTagNameNS 498
#define sipName_elementsByTagNameNS &sipStrings_QtXml[498]
#define sipNameNr_EntityReferenceNode 518
#define sipName_EntityReferenceNode &sipStrings_QtXml[518]
#define sipNameNr_QXmlDefaultHandler 538
#define sipName_QXmlDefaultHandler &sipStrings_QtXml[538]
#define sipNameNr_externalEntityDecl 557
#define sipName_externalEntityDecl &sipStrings_QtXml[557]
#define sipNameNr_internalEntityDecl 576
#define sipName_internalEntityDecl &sipStrings_QtXml[576]
#define sipNameNr_QXmlLexicalHandler 595
#define sipName_QXmlLexicalHandler &sipStrings_QtXml[595]
#define sipNameNr_QXmlEntityResolver 614
#define sipName_QXmlEntityResolver &sipStrings_QtXml[614]
#define sipNameNr_unparsedEntityDecl 633
#define sipName_unparsedEntityDecl &sipStrings_QtXml[633]
#define sipNameNr_startPrefixMapping 652
#define sipName_startPrefixMapping &sipStrings_QtXml[652]
#define sipNameNr_setDocumentLocator 671
#define sipName_setDocumentLocator &sipStrings_QtXml[671]
#define sipNameNr_QXmlContentHandler 690
#define sipName_QXmlContentHandler &sipStrings_QtXml[690]
#define sipNameNr_QXmlParseException 709
#define sipName_QXmlParseException &sipStrings_QtXml[709]
#define sipNameNr_setAttributeNodeNS 728
#define sipName_setAttributeNodeNS &sipStrings_QtXml[728]
#define sipNameNr_createCDATASection 747
#define sipName_createCDATASection &sipStrings_QtXml[747]
#define sipNameNr_nextSiblingElement 766
#define sipName_nextSiblingElement &sipStrings_QtXml[766]
#define sipNameNr_toDocumentFragment 785
#define sipName_toDocumentFragment &sipStrings_QtXml[785]
#define sipNameNr_isDocumentFragment 804
#define sipName_isDocumentFragment &sipStrings_QtXml[804]
#define sipNameNr_QDomNode__NodeType 823
#define sipName_QDomNode__NodeType &sipStrings_QtXml[823]
#define sipNameNr_createDocumentType 842
#define sipName_createDocumentType &sipStrings_QtXml[842]
#define sipNameNr_AcceptInvalidChars 861
#define sipName_AcceptInvalidChars &sipStrings_QtXml[861]
#define sipNameNr_QDomImplementation 880
#define sipName_QDomImplementation &sipStrings_QtXml[880]
#define sipNameNr_setLexicalHandler 899
#define sipName_setLexicalHandler &sipStrings_QtXml[899]
#define sipNameNr_setContentHandler 917
#define sipName_setContentHandler &sipStrings_QtXml[917]
#define sipNameNr_removeAttributeNS 935
#define sipName_removeAttributeNS &sipStrings_QtXml[935]
#define sipNameNr_QDomCharacterData 953
#define sipName_QDomCharacterData &sipStrings_QtXml[953]
#define sipNameNr_removeNamedItemNS 971
#define sipName_removeNamedItemNS &sipStrings_QtXml[971]
#define sipNameNr_createAttributeNS 989
#define sipName_createAttributeNS &sipStrings_QtXml[989]
#define sipNameNr_elementsByTagName 1007
#define sipName_elementsByTagName &sipStrings_QtXml[1007]
#define sipNameNr_firstChildElement 1025
#define sipName_firstChildElement &sipStrings_QtXml[1025]
#define sipNameNr_toEntityReference 1043
#define sipName_toEntityReference &sipStrings_QtXml[1043]
#define sipNameNr_CharacterDataNode 1061
#define sipName_CharacterDataNode &sipStrings_QtXml[1061]
#define sipNameNr_invalidDataPolicy 1079
#define sipName_invalidDataPolicy &sipStrings_QtXml[1079]
#define sipNameNr_InvalidDataPolicy 20
#define sipName_InvalidDataPolicy &sipStrings_QtXml[20]
#define sipNameNr_setEntityResolver 1097
#define sipName_setEntityResolver &sipStrings_QtXml[1097]
#define sipNameNr_isEntityReference 1115
#define sipName_isEntityReference &sipStrings_QtXml[1115]
#define sipNameNr_sip_simplewrapper 1133
#define sipName_sip_simplewrapper &sipStrings_QtXml[1133]
#define sipNameNr_QXmlErrorHandler 1151
#define sipName_QXmlErrorHandler &sipStrings_QtXml[1151]
#define sipNameNr_endPrefixMapping 1168
#define sipName_endPrefixMapping &sipStrings_QtXml[1168]
#define sipNameNr_QXmlSimpleReader 1185
#define sipName_QXmlSimpleReader &sipStrings_QtXml[1185]
#define sipNameNr_QDomCDATASection 1202
#define sipName_QDomCDATASection &sipStrings_QtXml[1202]
#define sipNameNr_setAttributeNode 1219
#define sipName_setAttributeNode &sipStrings_QtXml[1219]
#define sipNameNr_QDomNamedNodeMap 1236
#define sipName_QDomNamedNodeMap &sipStrings_QtXml[1236]
#define sipNameNr_QDomDocumentType 1253
#define sipName_QDomDocumentType &sipStrings_QtXml[1253]
#define sipNameNr_lastChildElement 1270
#define sipName_lastChildElement &sipStrings_QtXml[1270]
#define sipNameNr_DocumentTypeNode 1287
#define sipName_DocumentTypeNode &sipStrings_QtXml[1287]
#define sipNameNr_CDATASectionNode 1304
#define sipName_CDATASectionNode &sipStrings_QtXml[1304]
#define sipNameNr_DropInvalidChars 1321
#define sipName_DropInvalidChars &sipStrings_QtXml[1321]
#define sipNameNr_QXmlDeclHandler 1338
#define sipName_QXmlDeclHandler &sipStrings_QtXml[1338]
#define sipNameNr_setErrorHandler 1354
#define sipName_setErrorHandler &sipStrings_QtXml[1354]
#define sipNameNr_QXmlInputSource 1370
#define sipName_QXmlInputSource &sipStrings_QtXml[1370]
#define sipNameNr_attributeNodeNS 1386
#define sipName_attributeNodeNS &sipStrings_QtXml[1386]
#define sipNameNr_removeAttribute 1402
#define sipName_removeAttribute &sipStrings_QtXml[1402]
#define sipNameNr_removeNamedItem 1418
#define sipName_removeNamedItem &sipStrings_QtXml[1418]
#define sipNameNr_documentElement 1434
#define sipName_documentElement &sipStrings_QtXml[1434]
#define sipNameNr_createElementNS 1450
#define sipName_createElementNS &sipStrings_QtXml[1450]
#define sipNameNr_createAttribute 1466
#define sipName_createAttribute &sipStrings_QtXml[1466]
#define sipNameNr_toCharacterData 1482
#define sipName_toCharacterData &sipStrings_QtXml[1482]
#define sipNameNr_isCharacterData 1498
#define sipName_isCharacterData &sipStrings_QtXml[1498]
#define sipNameNr_previousSibling 1514
#define sipName_previousSibling &sipStrings_QtXml[1514]
#define sipNameNr_QXmlDTDHandler 1530
#define sipName_QXmlDTDHandler &sipStrings_QtXml[1530]
#define sipNameNr_setDeclHandler 1545
#define sipName_setDeclHandler &sipStrings_QtXml[1545]
#define sipNameNr_lexicalHandler 1560
#define sipName_lexicalHandler &sipStrings_QtXml[1560]
#define sipNameNr_contentHandler 1575
#define sipName_contentHandler &sipStrings_QtXml[1575]
#define sipNameNr_QXmlAttributes 1590
#define sipName_QXmlAttributes &sipStrings_QtXml[1590]
#define sipNameNr_hasAttributeNS 1605
#define sipName_hasAttributeNS &sipStrings_QtXml[1605]
#define sipNameNr_setAttributeNS 1620
#define sipName_setAttributeNS &sipStrings_QtXml[1620]
#define sipNameNr_setNamedItemNS 1635
#define sipName_setNamedItemNS &sipStrings_QtXml[1635]
#define sipNameNr_implementation 1650
#define sipName_implementation &sipStrings_QtXml[1650]
#define sipNameNr_createTextNode 1665
#define sipName_createTextNode &sipStrings_QtXml[1665]
#define sipNameNr_internalSubset 1680
#define sipName_internalSubset &sipStrings_QtXml[1680]
#define sipNameNr_encodingPolicy 1695
#define sipName_encodingPolicy &sipStrings_QtXml[1695]
#define sipNameNr_EncodingPolicy 157
#define sipName_EncodingPolicy &sipStrings_QtXml[157]
#define sipNameNr_toDocumentType 1710
#define sipName_toDocumentType &sipStrings_QtXml[1710]
#define sipNameNr_toCDATASection 1725
#define sipName_toCDATASection &sipStrings_QtXml[1725]
#define sipNameNr_isDocumentType 1740
#define sipName_isDocumentType &sipStrings_QtXml[1740]
#define sipNameNr_isCDATASection 1755
#define sipName_isCDATASection &sipStrings_QtXml[1755]
#define sipNameNr_createDocument 1770
#define sipName_createDocument &sipStrings_QtXml[1770]
#define sipNameNr_ReturnNullNode 1785
#define sipName_ReturnNullNode &sipStrings_QtXml[1785]
#define sipNameNr_entityResolver 1800
#define sipName_entityResolver &sipStrings_QtXml[1800]
#define sipNameNr_disambiguation 1815
#define sipName_disambiguation &sipStrings_QtXml[1815]
#define sipNameNr_attributeDecl 1830
#define sipName_attributeDecl &sipStrings_QtXml[1830]
#define sipNameNr_resolveEntity 1844
#define sipName_resolveEntity &sipStrings_QtXml[1844]
#define sipNameNr_skippedEntity 1858
#define sipName_skippedEntity &sipStrings_QtXml[1858]
#define sipNameNr_startDocument 1872
#define sipName_startDocument &sipStrings_QtXml[1872]
#define sipNameNr_parseContinue 1886
#define sipName_parseContinue &sipStrings_QtXml[1886]
#define sipNameNr_setDTDHandler 1900
#define sipName_setDTDHandler &sipStrings_QtXml[1900]
#define sipNameNr_EndOfDocument 1914
#define sipName_EndOfDocument &sipStrings_QtXml[1914]
#define sipNameNr_attributeNode 1928
#define sipName_attributeNode &sipStrings_QtXml[1928]
#define sipNameNr_substringData 1942
#define sipName_substringData &sipStrings_QtXml[1942]
#define sipNameNr_createComment 1956
#define sipName_createComment &sipStrings_QtXml[1956]
#define sipNameNr_createElement 1970
#define sipName_createElement &sipStrings_QtXml[1970]
#define sipNameNr_hasAttributes 1984
#define sipName_hasAttributes &sipStrings_QtXml[1984]
#define sipNameNr_ownerDocument 1998
#define sipName_ownerDocument &sipStrings_QtXml[1998]
#define sipNameNr_hasChildNodes 2012
#define sipName_hasChildNodes &sipStrings_QtXml[2012]
#define sipNameNr_AttributeNode 484
#define sipName_AttributeNode &sipStrings_QtXml[484]
#define sipNameNr_notationDecl 2026
#define sipName_notationDecl &sipStrings_QtXml[2026]
#define sipNameNr_startElement 2039
#define sipName_startElement &sipStrings_QtXml[2039]
#define sipNameNr_errorHandler 2052
#define sipName_errorHandler &sipStrings_QtXml[2052]
#define sipNameNr_QDomNotation 2065
#define sipName_QDomNotation &sipStrings_QtXml[2065]
#define sipNameNr_ownerElement 2078
#define sipName_ownerElement &sipStrings_QtXml[2078]
#define sipNameNr_setNamedItem 2091
#define sipName_setNamedItem &sipStrings_QtXml[2091]
#define sipNameNr_QDomDocument 2104
#define sipName_QDomDocument &sipStrings_QtXml[2104]
#define sipNameNr_QDomNodeList 2117
#define sipName_QDomNodeList &sipStrings_QtXml[2117]
#define sipNameNr_setNodeValue 2130
#define sipName_setNodeValue &sipStrings_QtXml[2130]
#define sipNameNr_namespaceURI 2143
#define sipName_namespaceURI &sipStrings_QtXml[2143]
#define sipNameNr_replaceChild 2156
#define sipName_replaceChild &sipStrings_QtXml[2156]
#define sipNameNr_insertBefore 2169
#define sipName_insertBefore &sipStrings_QtXml[2169]
#define sipNameNr_NotationNode 2182
#define sipName_NotationNode &sipStrings_QtXml[2182]
#define sipNameNr_DocumentNode 2195
#define sipName_DocumentNode &sipStrings_QtXml[2195]
#define sipNameNr_columnNumber 2208
#define sipName_columnNumber &sipStrings_QtXml[2208]
#define sipNameNr_notationName 2221
#define sipName_notationName &sipStrings_QtXml[2221]
#define sipNameNr_hasAttribute 2234
#define sipName_hasAttribute &sipStrings_QtXml[2234]
#define sipNameNr_defaultValue 2247
#define sipName_defaultValue &sipStrings_QtXml[2247]
#define sipNameNr_setAttribute 2260
#define sipName_setAttribute &sipStrings_QtXml[2260]
#define sipNameNr_startEntity 2273
#define sipName_startEntity &sipStrings_QtXml[2273]
#define sipNameNr_endDocument 2285
#define sipName_endDocument &sipStrings_QtXml[2285]
#define sipNameNr_QXmlLocator 2297
#define sipName_QXmlLocator &sipStrings_QtXml[2297]
#define sipNameNr_declHandler 2309
#define sipName_declHandler &sipStrings_QtXml[2309]
#define sipNameNr_hasProperty 2321
#define sipName_hasProperty &sipStrings_QtXml[2321]
#define sipNameNr_pushContext 2333
#define sipName_pushContext &sipStrings_QtXml[2333]
#define sipNameNr_processName 2345
#define sipName_processName &sipStrings_QtXml[2345]
#define sipNameNr_QDomComment 2357
#define sipName_QDomComment &sipStrings_QtXml[2357]
#define sipNameNr_attributeNS 2369
#define sipName_attributeNS &sipStrings_QtXml[2369]
#define sipNameNr_QDomElement 2381
#define sipName_QDomElement &sipStrings_QtXml[2381]
#define sipNameNr_replaceData 2393
#define sipName_replaceData &sipStrings_QtXml[2393]
#define sipNameNr_namedItemNS 2405
#define sipName_namedItemNS &sipStrings_QtXml[2405]
#define sipNameNr_errorColumn 2417
#define sipName_errorColumn &sipStrings_QtXml[2417]
#define sipNameNr_elementById 2429
#define sipName_elementById &sipStrings_QtXml[2429]
#define sipNameNr_nextSibling 2441
#define sipName_nextSibling &sipStrings_QtXml[2441]
#define sipNameNr_isSupported 2453
#define sipName_isSupported &sipStrings_QtXml[2453]
#define sipNameNr_appendChild 2465
#define sipName_appendChild &sipStrings_QtXml[2465]
#define sipNameNr_removeChild 2477
#define sipName_removeChild &sipStrings_QtXml[2477]
#define sipNameNr_insertAfter 2489
#define sipName_insertAfter &sipStrings_QtXml[2489]
#define sipNameNr_CommentNode 2501
#define sipName_CommentNode &sipStrings_QtXml[2501]
#define sipNameNr_ElementNode 2513
#define sipName_ElementNode &sipStrings_QtXml[2513]
#define sipNameNr_toByteArray 2525
#define sipName_toByteArray &sipStrings_QtXml[2525]
#define sipNameNr_setProperty 2537
#define sipName_setProperty &sipStrings_QtXml[2537]
#define sipNameNr_errorString 2549
#define sipName_errorString &sipStrings_QtXml[2549]
#define sipNameNr_fromRawData 2561
#define sipName_fromRawData &sipStrings_QtXml[2561]
#define sipNameNr_PyQt4_QtXml 2573
#define sipName_PyQt4_QtXml &sipStrings_QtXml[2573]
#define sipNameNr_startCDATA 2585
#define sipName_startCDATA &sipStrings_QtXml[2585]
#define sipNameNr_fatalError 2596
#define sipName_fatalError &sipStrings_QtXml[2596]
#define sipNameNr_characters 2607
#define sipName_characters &sipStrings_QtXml[2607]
#define sipNameNr_endElement 2618
#define sipName_endElement &sipStrings_QtXml[2618]
#define sipNameNr_DTDHandler 1534
#define sipName_DTDHandler &sipStrings_QtXml[1534]
#define sipNameNr_setFeature 2629
#define sipName_setFeature &sipStrings_QtXml[2629]
#define sipNameNr_QXmlReader 2640
#define sipName_QXmlReader &sipStrings_QtXml[2640]
#define sipNameNr_popContext 2651
#define sipName_popContext &sipStrings_QtXml[2651]
#define sipNameNr_QDomEntity 2662
#define sipName_QDomEntity &sipStrings_QtXml[2662]
#define sipNameNr_setTagName 2673
#define sipName_setTagName &sipStrings_QtXml[2673]
#define sipNameNr_deleteData 2684
#define sipName_deleteData &sipStrings_QtXml[2684]
#define sipNameNr_insertData 2695
#define sipName_insertData &sipStrings_QtXml[2695]
#define sipNameNr_appendData 2706
#define sipName_appendData &sipStrings_QtXml[2706]
#define sipNameNr_setContent 2717
#define sipName_setContent &sipStrings_QtXml[2717]
#define sipNameNr_importNode 2728
#define sipName_importNode &sipStrings_QtXml[2728]
#define sipNameNr_toNotation 2739
#define sipName_toNotation &sipStrings_QtXml[2739]
#define sipNameNr_toDocument 2750
#define sipName_toDocument &sipStrings_QtXml[2750]
#define sipNameNr_isNotation 2761
#define sipName_isNotation &sipStrings_QtXml[2761]
#define sipNameNr_isDocument 2772
#define sipName_isDocument &sipStrings_QtXml[2772]
#define sipNameNr_firstChild 2783
#define sipName_firstChild &sipStrings_QtXml[2783]
#define sipNameNr_childNodes 2794
#define sipName_childNodes &sipStrings_QtXml[2794]
#define sipNameNr_parentNode 2805
#define sipName_parentNode &sipStrings_QtXml[2805]
#define sipNameNr_EntityNode 2816
#define sipName_EntityNode &sipStrings_QtXml[2816]
#define sipNameNr_hasFeature 2827
#define sipName_hasFeature &sipStrings_QtXml[2827]
#define sipNameNr_attributes 2838
#define sipName_attributes &sipStrings_QtXml[2838]
#define sipNameNr_lineNumber 2849
#define sipName_lineNumber &sipStrings_QtXml[2849]
#define sipNameNr_fieldwidth 2860
#define sipName_fieldwidth &sipStrings_QtXml[2860]
#define sipNameNr_fieldWidth 2871
#define sipName_fieldWidth &sipStrings_QtXml[2871]
#define sipNameNr___lshift__ 2882
#define sipName___lshift__ &sipStrings_QtXml[2882]
#define sipNameNr_endEntity 2893
#define sipName_endEntity &sipStrings_QtXml[2893]
#define sipNameNr_beginning 2903
#define sipName_beginning &sipStrings_QtXml[2903]
#define sipNameNr_EndOfData 2913
#define sipName_EndOfData &sipStrings_QtXml[2913]
#define sipNameNr_fetchData 2923
#define sipName_fetchData &sipStrings_QtXml[2923]
#define sipNameNr_splitName 2933
#define sipName_splitName &sipStrings_QtXml[2933]
#define sipNameNr_splitText 2943
#define sipName_splitText &sipStrings_QtXml[2943]
#define sipNameNr_specified 2953
#define sipName_specified &sipStrings_QtXml[2953]
#define sipNameNr_errorLine 2963
#define sipName_errorLine &sipStrings_QtXml[2963]
#define sipNameNr_notations 2973
#define sipName_notations &sipStrings_QtXml[2973]
#define sipNameNr_toComment 2983
#define sipName_toComment &sipStrings_QtXml[2983]
#define sipNameNr_toElement 2993
#define sipName_toElement &sipStrings_QtXml[2993]
#define sipNameNr_namedItem 3003
#define sipName_namedItem &sipStrings_QtXml[3003]
#define sipNameNr_isElement 3013
#define sipName_isElement &sipStrings_QtXml[3013]
#define sipNameNr_setPrefix 3023
#define sipName_setPrefix &sipStrings_QtXml[3023]
#define sipNameNr_nodeValue 3033
#define sipName_nodeValue &sipStrings_QtXml[3033]
#define sipNameNr_localName 3043
#define sipName_localName &sipStrings_QtXml[3043]
#define sipNameNr_lastChild 3053
#define sipName_lastChild &sipStrings_QtXml[3053]
#define sipNameNr_normalize 3063
#define sipName_normalize &sipStrings_QtXml[3063]
#define sipNameNr_cloneNode 3073
#define sipName_cloneNode &sipStrings_QtXml[3073]
#define sipNameNr_isComment 3083
#define sipName_isComment &sipStrings_QtXml[3083]
#define sipNameNr_directory 3093
#define sipName_directory &sipStrings_QtXml[3093]
#define sipNameNr_attribute 3103
#define sipName_attribute &sipStrings_QtXml[3103]
#define sipNameNr_precision 3113
#define sipName_precision &sipStrings_QtXml[3113]
#define sipNameNr_endCDATA 3123
#define sipName_endCDATA &sipStrings_QtXml[3123]
#define sipNameNr_startDTD 3132
#define sipName_startDTD &sipStrings_QtXml[3132]
#define sipNameNr_prefixes 3141
#define sipName_prefixes &sipStrings_QtXml[3141]
#define sipNameNr_QDomText 3150
#define sipName_QDomText &sipStrings_QtXml[3150]
#define sipNameNr_QDomAttr 3159
#define sipName_QDomAttr &sipStrings_QtXml[3159]
#define sipNameNr_errorMsg 3168
#define sipName_errorMsg &sipStrings_QtXml[3168]
#define sipNameNr_entities 3177
#define sipName_entities &sipStrings_QtXml[3177]
#define sipNameNr_toEntity 3186
#define sipName_toEntity &sipStrings_QtXml[3186]
#define sipNameNr_isEntity 3195
#define sipName_isEntity &sipStrings_QtXml[3195]
#define sipNameNr_nodeType 3204
#define sipName_nodeType &sipStrings_QtXml[3204]
#define sipNameNr_nodeName 3213
#define sipName_nodeName &sipStrings_QtXml[3213]
#define sipNameNr_BaseNode 3222
#define sipName_BaseNode &sipStrings_QtXml[3222]
#define sipNameNr_TextNode 1671
#define sipName_TextNode &sipStrings_QtXml[1671]
#define sipNameNr_NodeType 833
#define sipName_NodeType &sipStrings_QtXml[833]
#define sipNameNr_QDomNode 3231
#define sipName_QDomNode &sipStrings_QtXml[3231]
#define sipNameNr_publicId 3240
#define sipName_publicId &sipStrings_QtXml[3240]
#define sipNameNr_systemId 3249
#define sipName_systemId &sipStrings_QtXml[3249]
#define sipNameNr_behavior 3258
#define sipName_behavior &sipStrings_QtXml[3258]
#define sipNameNr_fillChar 3267
#define sipName_fillChar &sipStrings_QtXml[3267]
#define sipNameNr_setValue 3276
#define sipName_setValue &sipStrings_QtXml[3276]
#define sipNameNr_property 3285
#define sipName_property &sipStrings_QtXml[3285]
#define sipNameNr_toString 3294
#define sipName_toString &sipStrings_QtXml[3294]
#define sipNameNr_encoding 3303
#define sipName_encoding &sipStrings_QtXml[3303]
#define sipNameNr_contains 3312
#define sipName_contains &sipStrings_QtXml[3312]
#define sipNameNr_warning 3321
#define sipName_warning &sipStrings_QtXml[3321]
#define sipNameNr_tagName 3329
#define sipName_tagName &sipStrings_QtXml[3329]
#define sipNameNr_doctype 3337
#define sipName_doctype &sipStrings_QtXml[3337]
#define sipNameNr_feature 3345
#define sipName_feature &sipStrings_QtXml[3345]
#define sipNameNr_comment 3353
#define sipName_comment &sipStrings_QtXml[3353]
#define sipNameNr_isEmpty 3361
#define sipName_isEmpty &sipStrings_QtXml[3361]
#define sipNameNr___len__ 3369
#define sipName___len__ &sipStrings_QtXml[3369]
#define sipNameNr_setData 3377
#define sipName_setData &sipStrings_QtXml[3377]
#define sipNameNr_filters 3385
#define sipName_filters &sipStrings_QtXml[3385]
#define sipNameNr_message 3393
#define sipName_message &sipStrings_QtXml[3393]
#define sipNameNr_QString 3401
#define sipName_QString &sipStrings_QtXml[3401]
#define sipNameNr_endDTD 3409
#define sipName_endDTD &sipStrings_QtXml[3409]
#define sipNameNr_indent 3416
#define sipName_indent &sipStrings_QtXml[3416]
#define sipNameNr_toText 3423
#define sipName_toText &sipStrings_QtXml[3423]
#define sipNameNr_toAttr 3430
#define sipName_toAttr &sipStrings_QtXml[3430]
#define sipNameNr_isText 3437
#define sipName_isText &sipStrings_QtXml[3437]
#define sipNameNr_isAttr 3444
#define sipName_isAttr &sipStrings_QtXml[3444]
#define sipNameNr_proper 3451
#define sipName_proper &sipStrings_QtXml[3451]
#define sipNameNr_value9 3458
#define sipName_value9 &sipStrings_QtXml[3458]
#define sipNameNr_value8 3465
#define sipName_value8 &sipStrings_QtXml[3465]
#define sipNameNr_value7 3472
#define sipName_value7 &sipStrings_QtXml[3472]
#define sipNameNr_value6 3479
#define sipName_value6 &sipStrings_QtXml[3479]
#define sipNameNr_value5 3486
#define sipName_value5 &sipStrings_QtXml[3486]
#define sipNameNr_value4 3493
#define sipName_value4 &sipStrings_QtXml[3493]
#define sipNameNr_value3 3500
#define sipName_value3 &sipStrings_QtXml[3500]
#define sipNameNr_value2 3507
#define sipName_value2 &sipStrings_QtXml[3507]
#define sipNameNr_value1 3514
#define sipName_value1 &sipStrings_QtXml[3514]
#define sipNameNr_value0 3521
#define sipName_value0 &sipStrings_QtXml[3521]
#define sipNameNr_symbol 3528
#define sipName_symbol &sipStrings_QtXml[3528]
#define sipNameNr_suffix 3535
#define sipName_suffix &sipStrings_QtXml[3535]
#define sipNameNr_prefix 3542
#define sipName_prefix &sipStrings_QtXml[3542]
#define sipNameNr_format 3549
#define sipName_format &sipStrings_QtXml[3549]
#define sipNameNr_append 3556
#define sipName_append &sipStrings_QtXml[3556]
#define sipNameNr_length 3563
#define sipName_length &sipStrings_QtXml[3563]
#define sipNameNr_isNull 3570
#define sipName_isNull &sipStrings_QtXml[3570]
#define sipNameNr_target 3577
#define sipName_target &sipStrings_QtXml[3577]
#define sipNameNr_column 3584
#define sipName_column &sipStrings_QtXml[3584]
#define sipNameNr___ne__ 3591
#define sipName___ne__ &sipStrings_QtXml[3591]
#define sipNameNr___eq__ 3598
#define sipName___eq__ &sipStrings_QtXml[3598]
#define sipNameNr_parse 3605
#define sipName_parse &sipStrings_QtXml[3605]
#define sipNameNr_qName 3611
#define sipName_qName &sipStrings_QtXml[3611]
#define sipNameNr_clear 3617
#define sipName_clear &sipStrings_QtXml[3617]
#define sipNameNr_reset 3623
#define sipName_reset &sipStrings_QtXml[3623]
#define sipNameNr_count 3629
#define sipName_count &sipStrings_QtXml[3629]
#define sipNameNr_value 3635
#define sipName_value &sipStrings_QtXml[3635]
#define sipNameNr_index 3641
#define sipName_index &sipStrings_QtXml[3641]
#define sipNameNr_error 3647
#define sipName_error &sipStrings_QtXml[3647]
#define sipNameNr_flags 3653
#define sipName_flags &sipStrings_QtXml[3653]
#define sipNameNr_msecs 3659
#define sipName_msecs &sipStrings_QtXml[3659]
#define sipNameNr_item 3665
#define sipName_item &sipStrings_QtXml[3665]
#define sipNameNr_deep 3670
#define sipName_deep &sipStrings_QtXml[3670]
#define sipNameNr_save 3675
#define sipName_save &sipStrings_QtXml[3675]
#define sipNameNr_text 2340
#define sipName_text &sipStrings_QtXml[2340]
#define sipNameNr_line 3680
#define sipName_line &sipStrings_QtXml[3680]
#define sipNameNr_mode 3685
#define sipName_mode &sipStrings_QtXml[3685]
#define sipNameNr_next 3690
#define sipName_next &sipStrings_QtXml[3690]
#define sipNameNr_name 3695
#define sipName_name &sipStrings_QtXml[3695]
#define sipNameNr_base 3700
#define sipName_base &sipStrings_QtXml[3700]
#define sipNameNr_from 3705
#define sipName_from &sipStrings_QtXml[3705]
#define sipNameNr_sort 3710
#define sipName_sort &sipStrings_QtXml[3710]
#define sipNameNr_data 3715
#define sipName_data &sipStrings_QtXml[3715]
#define sipNameNr_type 3340
#define sipName_type &sipStrings_QtXml[3340]
#define sipNameNr_size 3720
#define sipName_size &sipStrings_QtXml[3720]
#define sipNameNr_uri 3725
#define sipName_uri &sipStrings_QtXml[3725]
#define sipNameNr_end 3559
#define sipName_end &sipStrings_QtXml[3559]
#define sipNameNr_cs 3662
#define sipName_cs &sipStrings_QtXml[3662]
#define sipNameNr_ok 3729
#define sipName_ok &sipStrings_QtXml[3729]
#define sipNameNr_at 3553
#define sipName_at &sipStrings_QtXml[3553]

#define sipMalloc                   sipAPI_QtXml->api_malloc
#define sipFree                     sipAPI_QtXml->api_free
#define sipBuildResult              sipAPI_QtXml->api_build_result
#define sipCallMethod               sipAPI_QtXml->api_call_method
#define sipCallProcedureMethod      sipAPI_QtXml->api_call_procedure_method
#define sipCallErrorHandler         sipAPI_QtXml->api_call_error_handler
#define sipParseResultEx            sipAPI_QtXml->api_parse_result_ex
#define sipParseResult              sipAPI_QtXml->api_parse_result
#define sipParseArgs                sipAPI_QtXml->api_parse_args
#define sipParseKwdArgs             sipAPI_QtXml->api_parse_kwd_args
#define sipParsePair                sipAPI_QtXml->api_parse_pair
#define sipInstanceDestroyed        sipAPI_QtXml->api_instance_destroyed
#define sipInstanceDestroyedEx      sipAPI_QtXml->api_instance_destroyed_ex
#define sipConvertFromSequenceIndex sipAPI_QtXml->api_convert_from_sequence_index
#define sipConvertFromVoidPtr       sipAPI_QtXml->api_convert_from_void_ptr
#define sipConvertToVoidPtr         sipAPI_QtXml->api_convert_to_void_ptr
#define sipAddException             sipAPI_QtXml->api_add_exception
#define sipNoFunction               sipAPI_QtXml->api_no_function
#define sipNoMethod                 sipAPI_QtXml->api_no_method
#define sipAbstractMethod           sipAPI_QtXml->api_abstract_method
#define sipBadClass                 sipAPI_QtXml->api_bad_class
#define sipBadCatcherResult         sipAPI_QtXml->api_bad_catcher_result
#define sipBadCallableArg           sipAPI_QtXml->api_bad_callable_arg
#define sipBadOperatorArg           sipAPI_QtXml->api_bad_operator_arg
#define sipTrace                    sipAPI_QtXml->api_trace
#define sipTransferBack             sipAPI_QtXml->api_transfer_back
#define sipTransferTo               sipAPI_QtXml->api_transfer_to
#define sipTransferBreak            sipAPI_QtXml->api_transfer_break
#define sipSimpleWrapper_Type       sipAPI_QtXml->api_simplewrapper_type
#define sipWrapper_Type             sipAPI_QtXml->api_wrapper_type
#define sipWrapperType_Type         sipAPI_QtXml->api_wrappertype_type
#define sipVoidPtr_Type             sipAPI_QtXml->api_voidptr_type
#define sipGetPyObject              sipAPI_QtXml->api_get_pyobject
#define sipGetAddress               sipAPI_QtXml->api_get_address
#define sipGetMixinAddress          sipAPI_QtXml->api_get_mixin_address
#define sipGetCppPtr                sipAPI_QtXml->api_get_cpp_ptr
#define sipGetComplexCppPtr         sipAPI_QtXml->api_get_complex_cpp_ptr
#define sipIsPyMethod               sipAPI_QtXml->api_is_py_method
#define sipCallHook                 sipAPI_QtXml->api_call_hook
#define sipEndThread                sipAPI_QtXml->api_end_thread
#define sipConnectRx                sipAPI_QtXml->api_connect_rx
#define sipDisconnectRx             sipAPI_QtXml->api_disconnect_rx
#define sipRaiseUnknownException    sipAPI_QtXml->api_raise_unknown_exception
#define sipRaiseTypeException       sipAPI_QtXml->api_raise_type_exception
#define sipBadLengthForSlice        sipAPI_QtXml->api_bad_length_for_slice
#define sipAddTypeInstance          sipAPI_QtXml->api_add_type_instance
#define sipFreeSipslot              sipAPI_QtXml->api_free_sipslot
#define sipSameSlot                 sipAPI_QtXml->api_same_slot
#define sipPySlotExtend             sipAPI_QtXml->api_pyslot_extend
#define sipConvertRx                sipAPI_QtXml->api_convert_rx
#define sipAddDelayedDtor           sipAPI_QtXml->api_add_delayed_dtor
#define sipCanConvertToType         sipAPI_QtXml->api_can_convert_to_type
#define sipConvertToType            sipAPI_QtXml->api_convert_to_type
#define sipForceConvertToType       sipAPI_QtXml->api_force_convert_to_type
#define sipCanConvertToEnum         sipAPI_QtXml->api_can_convert_to_enum
#define sipConvertToEnum            sipAPI_QtXml->api_convert_to_enum
#define sipConvertToBool            sipAPI_QtXml->api_convert_to_bool
#define sipReleaseType              sipAPI_QtXml->api_release_type
#define sipConvertFromType          sipAPI_QtXml->api_convert_from_type
#define sipConvertFromNewType       sipAPI_QtXml->api_convert_from_new_type
#define sipConvertFromNewPyType     sipAPI_QtXml->api_convert_from_new_pytype
#define sipConvertFromEnum          sipAPI_QtXml->api_convert_from_enum
#define sipGetState                 sipAPI_QtXml->api_get_state
#define sipExportSymbol             sipAPI_QtXml->api_export_symbol
#define sipImportSymbol             sipAPI_QtXml->api_import_symbol
#define sipFindType                 sipAPI_QtXml->api_find_type
#define sipFindNamedEnum            sipAPI_QtXml->api_find_named_enum
#define sipBytes_AsChar             sipAPI_QtXml->api_bytes_as_char
#define sipBytes_AsString           sipAPI_QtXml->api_bytes_as_string
#define sipString_AsASCIIChar       sipAPI_QtXml->api_string_as_ascii_char
#define sipString_AsASCIIString     sipAPI_QtXml->api_string_as_ascii_string
#define sipString_AsLatin1Char      sipAPI_QtXml->api_string_as_latin1_char
#define sipString_AsLatin1String    sipAPI_QtXml->api_string_as_latin1_string
#define sipString_AsUTF8Char        sipAPI_QtXml->api_string_as_utf8_char
#define sipString_AsUTF8String      sipAPI_QtXml->api_string_as_utf8_string
#define sipUnicode_AsWChar          sipAPI_QtXml->api_unicode_as_wchar
#define sipUnicode_AsWString        sipAPI_QtXml->api_unicode_as_wstring
#define sipConvertFromConstVoidPtr  sipAPI_QtXml->api_convert_from_const_void_ptr
#define sipConvertFromVoidPtrAndSize    sipAPI_QtXml->api_convert_from_void_ptr_and_size
#define sipConvertFromConstVoidPtrAndSize   sipAPI_QtXml->api_convert_from_const_void_ptr_and_size
#define sipInvokeSlot               sipAPI_QtXml->api_invoke_slot
#define sipInvokeSlotEx             sipAPI_QtXml->api_invoke_slot_ex
#define sipSaveSlot                 sipAPI_QtXml->api_save_slot
#define sipClearAnySlotReference    sipAPI_QtXml->api_clear_any_slot_reference
#define sipVisitSlot                sipAPI_QtXml->api_visit_slot
#define sipWrappedTypeName(wt)      ((wt)->wt_td->td_cname)
#define sipDeprecated               sipAPI_QtXml->api_deprecated
#define sipGetReference             sipAPI_QtXml->api_get_reference
#define sipKeepReference            sipAPI_QtXml->api_keep_reference
#define sipRegisterProxyResolver    sipAPI_QtXml->api_register_proxy_resolver
#define sipRegisterPyType           sipAPI_QtXml->api_register_py_type
#define sipTypeFromPyTypeObject     sipAPI_QtXml->api_type_from_py_type_object
#define sipTypeScope                sipAPI_QtXml->api_type_scope
#define sipResolveTypedef           sipAPI_QtXml->api_resolve_typedef
#define sipRegisterAttributeGetter  sipAPI_QtXml->api_register_attribute_getter
#define sipIsAPIEnabled             sipAPI_QtXml->api_is_api_enabled
#define sipSetDestroyOnExit         sipAPI_QtXml->api_set_destroy_on_exit
#define sipEnableAutoconversion     sipAPI_QtXml->api_enable_autoconversion
#define sipEnableOverflowChecking   sipAPI_QtXml->api_enable_overflow_checking
#define sipInitMixin                sipAPI_QtXml->api_init_mixin
#define sipExportModule             sipAPI_QtXml->api_export_module
#define sipInitModule               sipAPI_QtXml->api_init_module
#define sipGetInterpreter           sipAPI_QtXml->api_get_interpreter
#define sipSetNewUserTypeHandler    sipAPI_QtXml->api_set_new_user_type_handler
#define sipSetTypeUserData          sipAPI_QtXml->api_set_type_user_data
#define sipGetTypeUserData          sipAPI_QtXml->api_get_type_user_data
#define sipPyTypeDict               sipAPI_QtXml->api_py_type_dict
#define sipPyTypeName               sipAPI_QtXml->api_py_type_name
#define sipGetCFunction             sipAPI_QtXml->api_get_c_function
#define sipGetMethod                sipAPI_QtXml->api_get_method
#define sipFromMethod               sipAPI_QtXml->api_from_method
#define sipGetDate                  sipAPI_QtXml->api_get_date
#define sipFromDate                 sipAPI_QtXml->api_from_date
#define sipGetDateTime              sipAPI_QtXml->api_get_datetime
#define sipFromDateTime             sipAPI_QtXml->api_from_datetime
#define sipGetTime                  sipAPI_QtXml->api_get_time
#define sipFromTime                 sipAPI_QtXml->api_from_time
#define sipIsUserType               sipAPI_QtXml->api_is_user_type
#define sipGetFrame                 sipAPI_QtXml->api_get_frame
#define sipCheckPluginForType       sipAPI_QtXml->api_check_plugin_for_type
#define sipUnicodeNew               sipAPI_QtXml->api_unicode_new
#define sipUnicodeWrite             sipAPI_QtXml->api_unicode_write
#define sipUnicodeData              sipAPI_QtXml->api_unicode_data
#define sipGetBufferInfo            sipAPI_QtXml->api_get_buffer_info
#define sipReleaseBufferInfo        sipAPI_QtXml->api_release_buffer_info
#define sipIsOwnedByPython          sipAPI_QtXml->api_is_owned_by_python
#define sipIsDerivedClass           sipAPI_QtXml->api_is_derived_class
#define sipGetUserObject            sipAPI_QtXml->api_get_user_object
#define sipSetUserObject            sipAPI_QtXml->api_set_user_object
#define sipRegisterEventHandler     sipAPI_QtXml->api_register_event_handler
#define sipLong_AsChar              sipAPI_QtXml->api_long_as_char
#define sipLong_AsSignedChar        sipAPI_QtXml->api_long_as_signed_char
#define sipLong_AsUnsignedChar      sipAPI_QtXml->api_long_as_unsigned_char
#define sipLong_AsShort             sipAPI_QtXml->api_long_as_short
#define sipLong_AsUnsignedShort     sipAPI_QtXml->api_long_as_unsigned_short
#define sipLong_AsInt               sipAPI_QtXml->api_long_as_int
#define sipLong_AsUnsignedInt       sipAPI_QtXml->api_long_as_unsigned_int
#define sipLong_AsLong              sipAPI_QtXml->api_long_as_long
#define sipLong_AsUnsignedLong      sipAPI_QtXml->api_long_as_unsigned_long
#define sipLong_AsLongLong          sipAPI_QtXml->api_long_as_long_long
#define sipLong_AsUnsignedLongLong  sipAPI_QtXml->api_long_as_unsigned_long_long

/* These are deprecated. */
#define sipMapStringToClass         sipAPI_QtXml->api_map_string_to_class
#define sipMapIntToClass            sipAPI_QtXml->api_map_int_to_class
#define sipFindClass                sipAPI_QtXml->api_find_class
#define sipFindMappedType           sipAPI_QtXml->api_find_mapped_type
#define sipConvertToArray           sipAPI_QtXml->api_convert_to_array
#define sipConvertToTypedArray      sipAPI_QtXml->api_convert_to_typed_array
#define sipEnableGC                 sipAPI_QtXml->api_enable_gc
#define sipPrintObject              sipAPI_QtXml->api_print_object
#define sipWrapper_Check(w)         PyObject_TypeCheck((w), sipAPI_QtXml->api_wrapper_type)
#define sipGetWrapper(p, wt)        sipGetPyObject((p), (wt)->wt_td)
#define sipReleaseInstance(p, wt, s)    sipReleaseType((p), (wt)->wt_td, (s))
#define sipReleaseMappedType        sipReleaseType
#define sipCanConvertToInstance(o, wt, f)   sipCanConvertToType((o), (wt)->wt_td, (f))
#define sipCanConvertToMappedType   sipCanConvertToType
#define sipConvertToInstance(o, wt, t, f, s, e)     sipConvertToType((o), (wt)->wt_td, (t), (f), (s), (e))
#define sipConvertToMappedType      sipConvertToType
#define sipForceConvertToInstance(o, wt, t, f, s, e)    sipForceConvertToType((o), (wt)->wt_td, (t), (f), (s), (e))
#define sipForceConvertToMappedType sipForceConvertToType
#define sipConvertFromInstance(p, wt, t)    sipConvertFromType((p), (wt)->wt_td, (t))
#define sipConvertFromMappedType    sipConvertFromType
#define sipConvertFromNamedEnum(v, pt)  sipConvertFromEnum((v), ((sipEnumTypeObject *)(pt))->type)
#define sipConvertFromNewInstance(p, wt, t) sipConvertFromNewType((p), (wt)->wt_td, (t))

/* The strings used by this module. */
extern const char sipStrings_QtXml[];

#define sipType_QDomImplementation sipExportedTypes_QtXml[10]
#define sipClass_QDomImplementation sipExportedTypes_QtXml[10]->u.td_wrapper_type

#define sipType_QDomImplementation_InvalidDataPolicy sipExportedTypes_QtXml[11]
#define sipEnum_QDomImplementation_InvalidDataPolicy sipExportedTypes_QtXml[11]->u.td_py_type

extern sipClassTypeDef sipTypeDef_QtXml_QDomImplementation;

#define sipType_QDomNode sipExportedTypes_QtXml[13]
#define sipClass_QDomNode sipExportedTypes_QtXml[13]->u.td_wrapper_type

#define sipType_QDomNode_EncodingPolicy sipExportedTypes_QtXml[14]
#define sipEnum_QDomNode_EncodingPolicy sipExportedTypes_QtXml[14]->u.td_py_type

#define sipType_QDomNode_NodeType sipExportedTypes_QtXml[15]
#define sipEnum_QDomNode_NodeType sipExportedTypes_QtXml[15]->u.td_py_type

extern sipClassTypeDef sipTypeDef_QtXml_QDomNode;

#define sipType_QDomNodeList sipExportedTypes_QtXml[16]
#define sipClass_QDomNodeList sipExportedTypes_QtXml[16]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtXml_QDomNodeList;

#define sipType_QDomDocumentType sipExportedTypes_QtXml[6]
#define sipClass_QDomDocumentType sipExportedTypes_QtXml[6]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtXml_QDomDocumentType;

#define sipType_QDomDocument sipExportedTypes_QtXml[4]
#define sipClass_QDomDocument sipExportedTypes_QtXml[4]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtXml_QDomDocument;

#define sipType_QDomNamedNodeMap sipExportedTypes_QtXml[12]
#define sipClass_QDomNamedNodeMap sipExportedTypes_QtXml[12]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtXml_QDomNamedNodeMap;

#define sipType_QDomDocumentFragment sipExportedTypes_QtXml[5]
#define sipClass_QDomDocumentFragment sipExportedTypes_QtXml[5]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtXml_QDomDocumentFragment;

#define sipType_QDomCharacterData sipExportedTypes_QtXml[2]
#define sipClass_QDomCharacterData sipExportedTypes_QtXml[2]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtXml_QDomCharacterData;

#define sipType_QDomAttr sipExportedTypes_QtXml[0]
#define sipClass_QDomAttr sipExportedTypes_QtXml[0]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtXml_QDomAttr;

#define sipType_QDomElement sipExportedTypes_QtXml[7]
#define sipClass_QDomElement sipExportedTypes_QtXml[7]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtXml_QDomElement;

#define sipType_QDomText sipExportedTypes_QtXml[19]
#define sipClass_QDomText sipExportedTypes_QtXml[19]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtXml_QDomText;

#define sipType_QDomComment sipExportedTypes_QtXml[3]
#define sipClass_QDomComment sipExportedTypes_QtXml[3]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtXml_QDomComment;

#define sipType_QDomCDATASection sipExportedTypes_QtXml[1]
#define sipClass_QDomCDATASection sipExportedTypes_QtXml[1]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtXml_QDomCDATASection;

#define sipType_QDomNotation sipExportedTypes_QtXml[17]
#define sipClass_QDomNotation sipExportedTypes_QtXml[17]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtXml_QDomNotation;

#define sipType_QDomEntity sipExportedTypes_QtXml[8]
#define sipClass_QDomEntity sipExportedTypes_QtXml[8]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtXml_QDomEntity;

#define sipType_QDomEntityReference sipExportedTypes_QtXml[9]
#define sipClass_QDomEntityReference sipExportedTypes_QtXml[9]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtXml_QDomEntityReference;

#define sipType_QDomProcessingInstruction sipExportedTypes_QtXml[18]
#define sipClass_QDomProcessingInstruction sipExportedTypes_QtXml[18]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtXml_QDomProcessingInstruction;

#define sipType_QXmlNamespaceSupport sipExportedTypes_QtXml[30]
#define sipClass_QXmlNamespaceSupport sipExportedTypes_QtXml[30]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtXml_QXmlNamespaceSupport;

#define sipType_QXmlAttributes sipExportedTypes_QtXml[20]
#define sipClass_QXmlAttributes sipExportedTypes_QtXml[20]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtXml_QXmlAttributes;

#define sipType_QXmlInputSource sipExportedTypes_QtXml[27]
#define sipClass_QXmlInputSource sipExportedTypes_QtXml[27]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtXml_QXmlInputSource;

#define sipType_QXmlParseException sipExportedTypes_QtXml[31]
#define sipClass_QXmlParseException sipExportedTypes_QtXml[31]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtXml_QXmlParseException;

#define sipType_QXmlReader sipExportedTypes_QtXml[32]
#define sipClass_QXmlReader sipExportedTypes_QtXml[32]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtXml_QXmlReader;

#define sipType_QXmlSimpleReader sipExportedTypes_QtXml[33]
#define sipClass_QXmlSimpleReader sipExportedTypes_QtXml[33]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtXml_QXmlSimpleReader;

#define sipType_QXmlLocator sipExportedTypes_QtXml[29]
#define sipClass_QXmlLocator sipExportedTypes_QtXml[29]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtXml_QXmlLocator;

#define sipType_QXmlContentHandler sipExportedTypes_QtXml[21]
#define sipClass_QXmlContentHandler sipExportedTypes_QtXml[21]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtXml_QXmlContentHandler;

#define sipType_QXmlErrorHandler sipExportedTypes_QtXml[26]
#define sipClass_QXmlErrorHandler sipExportedTypes_QtXml[26]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtXml_QXmlErrorHandler;

#define sipType_QXmlDTDHandler sipExportedTypes_QtXml[22]
#define sipClass_QXmlDTDHandler sipExportedTypes_QtXml[22]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtXml_QXmlDTDHandler;

#define sipType_QXmlEntityResolver sipExportedTypes_QtXml[25]
#define sipClass_QXmlEntityResolver sipExportedTypes_QtXml[25]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtXml_QXmlEntityResolver;

#define sipType_QXmlLexicalHandler sipExportedTypes_QtXml[28]
#define sipClass_QXmlLexicalHandler sipExportedTypes_QtXml[28]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtXml_QXmlLexicalHandler;

#define sipType_QXmlDeclHandler sipExportedTypes_QtXml[23]
#define sipClass_QXmlDeclHandler sipExportedTypes_QtXml[23]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtXml_QXmlDeclHandler;

#define sipType_QXmlDefaultHandler sipExportedTypes_QtXml[24]
#define sipClass_QXmlDefaultHandler sipExportedTypes_QtXml[24]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtXml_QXmlDefaultHandler;

/* The SIP API, this module's API and the APIs of any imported modules. */
extern const sipAPIDef *sipAPI_QtXml;
extern sipExportedModuleDef sipModuleAPI_QtXml;
extern sipTypeDef *sipExportedTypes_QtXml[];

#define sipType_QIODevice sipImportedTypes_QtXml_QtCore[2].it_td
#define sipClass_QIODevice sipImportedTypes_QtXml_QtCore[2].it_td->u.td_wrapper_type

#define sipType_QByteArray sipImportedTypes_QtXml_QtCore[0].it_td
#define sipClass_QByteArray sipImportedTypes_QtXml_QtCore[0].it_td->u.td_wrapper_type

#define sipType_QTextStream sipImportedTypes_QtXml_QtCore[5].it_td
#define sipClass_QTextStream sipImportedTypes_QtXml_QtCore[5].it_td->u.td_wrapper_type

#define sipType_QStringList sipImportedTypes_QtXml_QtCore[4].it_td

#define sipType_QString sipImportedTypes_QtXml_QtCore[3].it_td

#define sipType_QChar sipImportedTypes_QtXml_QtCore[1].it_td
extern sipImportedTypeDef sipImportedTypes_QtXml_QtCore[];

typedef const QMetaObject *(*sip_qt_metaobject_func)(sipSimpleWrapper *,sipTypeDef *);
extern sip_qt_metaobject_func sip_QtXml_qt_metaobject;

typedef int (*sip_qt_metacall_func)(sipSimpleWrapper *,sipTypeDef *,QMetaObject::Call,int,void **);
extern sip_qt_metacall_func sip_QtXml_qt_metacall;

typedef int (*sip_qt_metacast_func)(sipSimpleWrapper *, sipTypeDef *, const char *);
extern sip_qt_metacast_func sip_QtXml_qt_metacast;

#endif
