/*
 * Internal module API header file.
 *
 * Generated by SIP 4.19.8
 *
 * Copyright (c) 2016 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of PyQt4.
 * 
 * This file may be used under the terms of the GNU General Public License
 * version 3.0 as published by the Free Software Foundation and appearing in
 * the file LICENSE included in the packaging of this file.  Please review the
 * following information to ensure the GNU General Public License version 3.0
 * requirements will be met: http://www.gnu.org/copyleft/gpl.html.
 * 
 * If you do not wish to use this file under the terms of the GPL version 3.0
 * then you may purchase a commercial license.  For more information contact
 * info@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#ifndef _QtMultimediaAPI_H
#define _QtMultimediaAPI_H

#include <sip.h>

#include <QMetaType>
#include <QThread>

/* These are the qualifiers that are enabled. */
#define SIP_FEATURE_PyQt_Process
#define SIP_FEATURE_PyQt_NotBootstrapped
#define SIP_FEATURE_PyQt_Deprecated_5_0
#define SIP_FEATURE_PyQt_NoOpenGLES
#define SIP_FEATURE_PyQt_RawFont
#define SIP_FEATURE_PyQt_SystemTrayIcon
#define SIP_FEATURE_PyQt_PrintPreviewDialog
#define SIP_FEATURE_PyQt_PrintPreviewWidget
#define SIP_FEATURE_PyQt_Printer
#define SIP_FEATURE_PyQt_PrintDialog
#define SIP_FEATURE_Py_v3
#define SIP_FEATURE_PyQt_qreal_double
#define SIP_FEATURE_PyQt_SizeGrip
#define SIP_FEATURE_PyQt_OpenSSL
#define SIP_FEATURE_Py_DateTime
#define SIP_FEATURE_PyQt_NoQtPrintRangeBug
#define SIP_FEATURE_PyQt_WhatsThis
#define SIP_FEATURE_PyQt_ToolTip
#define SIP_FEATURE_PyQt_StatusTip
#define SIP_FEATURE_PyQt_SessionManager
#define SIP_FEATURE_PyQt_Accessibility
#define SIP_PLATFORM_WS_X11
#define SIP_TIMELINE_Qt_5_0_0


/*
 * Convenient names to refer to various strings defined in this module.
 * Only the class names are part of the public API.
 */
#define sipNameNr_QVideoSurfaceFormat__YCbCrColorSpace 0
#define sipName_QVideoSurfaceFormat__YCbCrColorSpace &sipStrings_QtMultimedia[0]
#define sipNameNr_QAbstractVideoBuffer__HandleType 37
#define sipName_QAbstractVideoBuffer__HandleType &sipStrings_QtMultimedia[37]
#define sipNameNr_70 70
#define sipName_70 &sipStrings_QtMultimedia[70]
#define sipNameNr_102 102
#define sipName_102 &sipStrings_QtMultimedia[102]
#define sipNameNr_QVideoSurfaceFormat__Direction 134
#define sipName_QVideoSurfaceFormat__Direction &sipStrings_QtMultimedia[134]
#define sipNameNr_Format_BGRA5658_Premultiplied 165
#define sipName_Format_BGRA5658_Premultiplied &sipStrings_QtMultimedia[165]
#define sipNameNr_QAbstractVideoBuffer__MapMode 195
#define sipName_QAbstractVideoBuffer__MapMode &sipStrings_QtMultimedia[195]
#define sipNameNr_Format_ARGB8565_Premultiplied 225
#define sipName_Format_ARGB8565_Premultiplied &sipStrings_QtMultimedia[225]
#define sipNameNr_Format_AYUV444_Premultiplied 255
#define sipName_Format_AYUV444_Premultiplied &sipStrings_QtMultimedia[255]
#define sipNameNr_QAbstractVideoSurface__Error 284
#define sipName_QAbstractVideoSurface__Error &sipStrings_QtMultimedia[284]
#define sipNameNr_PyQt4_QtCore_pyqtWrapperType 313
#define sipName_PyQt4_QtCore_pyqtWrapperType &sipStrings_QtMultimedia[313]
#define sipNameNr_Format_BGRA32_Premultiplied 342
#define sipName_Format_BGRA32_Premultiplied &sipStrings_QtMultimedia[342]
#define sipNameNr_370 370
#define sipName_370 &sipStrings_QtMultimedia[370]
#define sipNameNr_Format_ARGB32_Premultiplied 398
#define sipName_Format_ARGB32_Premultiplied &sipStrings_QtMultimedia[398]
#define sipNameNr_imageFormatFromPixelFormat 426
#define sipName_imageFormatFromPixelFormat &sipStrings_QtMultimedia[426]
#define sipNameNr_pixelFormatFromImageFormat 453
#define sipName_pixelFormatFromImageFormat &sipStrings_QtMultimedia[453]
#define sipNameNr_QVideoFrame__PixelFormat 480
#define sipName_QVideoFrame__PixelFormat &sipStrings_QtMultimedia[480]
#define sipNameNr_QAudioFormat__SampleType 505
#define sipName_QAudioFormat__SampleType &sipStrings_QtMultimedia[505]
#define sipNameNr_530 530
#define sipName_530 &sipStrings_QtMultimedia[530]
#define sipNameNr_nativeResolutionChanged 554
#define sipName_nativeResolutionChanged &sipStrings_QtMultimedia[554]
#define sipNameNr_supportedFormatsChanged 578
#define sipName_supportedFormatsChanged &sipStrings_QtMultimedia[578]
#define sipNameNr_QVideoFrame__FieldType 602
#define sipName_QVideoFrame__FieldType &sipStrings_QtMultimedia[602]
#define sipNameNr_supportedChannelCounts 625
#define sipName_supportedChannelCounts &sipStrings_QtMultimedia[625]
#define sipNameNr_UnsupportedFormatError 648
#define sipName_UnsupportedFormatError &sipStrings_QtMultimedia[648]
#define sipNameNr_supportedPixelFormats 671
#define sipName_supportedPixelFormats &sipStrings_QtMultimedia[671]
#define sipNameNr_QAbstractVideoSurface 693
#define sipName_QAbstractVideoSurface &sipStrings_QtMultimedia[693]
#define sipNameNr_setScanLineDirection 715
#define sipName_setScanLineDirection &sipStrings_QtMultimedia[715]
#define sipNameNr_QAudioFormat__Endian 736
#define sipName_QAudioFormat__Endian &sipStrings_QtMultimedia[736]
#define sipNameNr_supportedSampleRates 757
#define sipName_supportedSampleRates &sipStrings_QtMultimedia[757]
#define sipNameNr_supportedSampleTypes 778
#define sipName_supportedSampleTypes &sipStrings_QtMultimedia[778]
#define sipNameNr_supportedSampleSizes 799
#define sipName_supportedSampleSizes &sipStrings_QtMultimedia[799]
#define sipNameNr_surfaceFormatChanged 820
#define sipName_surfaceFormatChanged &sipStrings_QtMultimedia[820]
#define sipNameNr_IncorrectFormatError 841
#define sipName_IncorrectFormatError &sipStrings_QtMultimedia[841]
#define sipNameNr_QAbstractVideoBuffer 862
#define sipName_QAbstractVideoBuffer &sipStrings_QtMultimedia[862]
#define sipNameNr_setPixelAspectRatio 883
#define sipName_setPixelAspectRatio &sipStrings_QtMultimedia[883]
#define sipNameNr_QVideoSurfaceFormat 903
#define sipName_QVideoSurfaceFormat &sipStrings_QtMultimedia[903]
#define sipNameNr_defaultOutputDevice 923
#define sipName_defaultOutputDevice &sipStrings_QtMultimedia[923]
#define sipNameNr_supportedByteOrders 943
#define sipName_supportedByteOrders &sipStrings_QtMultimedia[943]
#define sipNameNr_setNativeResolution 963
#define sipName_setNativeResolution &sipStrings_QtMultimedia[963]
#define sipNameNr_defaultButtonNumber 983
#define sipName_defaultButtonNumber &sipStrings_QtMultimedia[983]
#define sipNameNr_setYCbCrColorSpace 1003
#define sipName_setYCbCrColorSpace &sipStrings_QtMultimedia[1003]
#define sipNameNr_defaultInputDevice 1022
#define sipName_defaultInputDevice &sipStrings_QtMultimedia[1022]
#define sipNameNr_escapeButtonNumber 1041
#define sipName_escapeButtonNumber &sipStrings_QtMultimedia[1041]
#define sipNameNr_PyQt4_QtMultimedia 1060
#define sipName_PyQt4_QtMultimedia &sipStrings_QtMultimedia[1060]
#define sipNameNr_scanLineDirection 1079
#define sipName_scanLineDirection &sipStrings_QtMultimedia[1079]
#define sipNameNr_availableMetaData 1097
#define sipName_availableMetaData &sipStrings_QtMultimedia[1097]
#define sipNameNr_setNotifyInterval 1115
#define sipName_setNotifyInterval &sipStrings_QtMultimedia[1115]
#define sipNameNr_durationForFrames 1133
#define sipName_durationForFrames &sipStrings_QtMultimedia[1133]
#define sipNameNr_framesForDuration 1151
#define sipName_framesForDuration &sipStrings_QtMultimedia[1151]
#define sipNameNr_isFormatSupported 1169
#define sipName_isFormatSupported &sipStrings_QtMultimedia[1169]
#define sipNameNr_sip_simplewrapper 1187
#define sipName_sip_simplewrapper &sipStrings_QtMultimedia[1187]
#define sipNameNr_pixelAspectRatio 1205
#define sipName_pixelAspectRatio &sipStrings_QtMultimedia[1205]
#define sipNameNr_Format_CameraRaw 1222
#define sipName_Format_CameraRaw &sipStrings_QtMultimedia[1222]
#define sipNameNr_ProgressiveFrame 1239
#define sipName_ProgressiveFrame &sipStrings_QtMultimedia[1239]
#define sipNameNr_durationForBytes 1256
#define sipName_durationForBytes &sipStrings_QtMultimedia[1256]
#define sipNameNr_bytesForDuration 1273
#define sipName_bytesForDuration &sipStrings_QtMultimedia[1273]
#define sipNameNr_availableDevices 1290
#define sipName_availableDevices &sipStrings_QtMultimedia[1290]
#define sipNameNr_QAudioDeviceInfo 1307
#define sipName_QAudioDeviceInfo &sipStrings_QtMultimedia[1307]
#define sipNameNr_nativeResolution 1324
#define sipName_nativeResolution &sipStrings_QtMultimedia[1324]
#define sipNameNr_XvShmImageHandle 1341
#define sipName_XvShmImageHandle &sipStrings_QtMultimedia[1341]
#define sipNameNr_disconnectNotify 1358
#define sipName_disconnectNotify &sipStrings_QtMultimedia[1358]
#define sipNameNr_yCbCrColorSpace 1375
#define sipName_yCbCrColorSpace &sipStrings_QtMultimedia[1375]
#define sipNameNr_YCbCr_Undefined 1391
#define sipName_YCbCr_Undefined &sipStrings_QtMultimedia[1391]
#define sipNameNr_YCbCrColorSpace 21
#define sipName_YCbCrColorSpace &sipStrings_QtMultimedia[21]
#define sipNameNr_Format_AdobeDng 1407
#define sipName_Format_AdobeDng &sipStrings_QtMultimedia[1407]
#define sipNameNr_InterlacedFrame 1423
#define sipName_InterlacedFrame &sipStrings_QtMultimedia[1423]
#define sipNameNr_setChannelCount 1439
#define sipName_setChannelCount &sipStrings_QtMultimedia[1439]
#define sipNameNr_supportedCodecs 1455
#define sipName_supportedCodecs &sipStrings_QtMultimedia[1455]
#define sipNameNr_preferredFormat 1471
#define sipName_preferredFormat &sipStrings_QtMultimedia[1471]
#define sipNameNr_CoreImageHandle 1487
#define sipName_CoreImageHandle &sipStrings_QtMultimedia[1487]
#define sipNameNr_GLTextureHandle 1503
#define sipName_GLTextureHandle &sipStrings_QtMultimedia[1503]
#define sipNameNr_aspectRatioMode 1519
#define sipName_aspectRatioMode &sipStrings_QtMultimedia[1519]
#define sipNameNr_deviceTransform 1535
#define sipName_deviceTransform &sipStrings_QtMultimedia[1535]
#define sipNameNr_YCbCr_xvYCC709 1551
#define sipName_YCbCr_xvYCC709 &sipStrings_QtMultimedia[1551]
#define sipNameNr_YCbCr_xvYCC601 1566
#define sipName_YCbCr_xvYCC601 &sipStrings_QtMultimedia[1566]
#define sipNameNr_Format_YUV420P 1581
#define sipName_Format_YUV420P &sipStrings_QtMultimedia[1581]
#define sipNameNr_Format_AYUV444 1596
#define sipName_Format_AYUV444 &sipStrings_QtMultimedia[1596]
#define sipNameNr_processedUSecs 1611
#define sipName_processedUSecs &sipStrings_QtMultimedia[1611]
#define sipNameNr_notifyInterval 1626
#define sipName_notifyInterval &sipStrings_QtMultimedia[1626]
#define sipNameNr_framesForBytes 1641
#define sipName_framesForBytes &sipStrings_QtMultimedia[1641]
#define sipNameNr_bytesForFrames 1656
#define sipName_bytesForFrames &sipStrings_QtMultimedia[1656]
#define sipNameNr_SuspendedState 1671
#define sipName_SuspendedState &sipStrings_QtMultimedia[1671]
#define sipNameNr_Format_Invalid 1686
#define sipName_Format_Invalid &sipStrings_QtMultimedia[1686]
#define sipNameNr_selectedFilter 1701
#define sipName_selectedFilter &sipStrings_QtMultimedia[1701]
#define sipNameNr_disambiguation 1716
#define sipName_disambiguation &sipStrings_QtMultimedia[1716]
#define sipNameNr_propertyNames 1731
#define sipName_propertyNames &sipStrings_QtMultimedia[1731]
#define sipNameNr_Format_YUV444 1745
#define sipName_Format_YUV444 &sipStrings_QtMultimedia[1745]
#define sipNameNr_Format_BGR555 1759
#define sipName_Format_BGR555 &sipStrings_QtMultimedia[1759]
#define sipNameNr_Format_BGR565 1773
#define sipName_Format_BGR565 &sipStrings_QtMultimedia[1773]
#define sipNameNr_Format_BGRA32 1787
#define sipName_Format_BGRA32 &sipStrings_QtMultimedia[1787]
#define sipNameNr_Format_RGB565 1801
#define sipName_Format_RGB565 &sipStrings_QtMultimedia[1801]
#define sipNameNr_setBufferSize 1815
#define sipName_setBufferSize &sipStrings_QtMultimedia[1815]
#define sipNameNr_bytesPerFrame 1829
#define sipName_bytesPerFrame &sipStrings_QtMultimedia[1829]
#define sipNameNr_setSampleRate 1843
#define sipName_setSampleRate &sipStrings_QtMultimedia[1843]
#define sipNameNr_setSampleType 1857
#define sipName_setSampleType &sipStrings_QtMultimedia[1857]
#define sipNameNr_setSampleSize 1871
#define sipName_setSampleSize &sipStrings_QtMultimedia[1871]
#define sipNameNr_QAudio__State 1885
#define sipName_QAudio__State &sipStrings_QtMultimedia[1885]
#define sipNameNr_UnderrunError 1899
#define sipName_UnderrunError &sipStrings_QtMultimedia[1899]
#define sipNameNr_QAudio__Error 1913
#define sipName_QAudio__Error &sipStrings_QtMultimedia[1913]
#define sipNameNr_activeChanged 1927
#define sipName_activeChanged &sipStrings_QtMultimedia[1927]
#define sipNameNr_surfaceFormat 1941
#define sipName_surfaceFormat &sipStrings_QtMultimedia[1941]
#define sipNameNr_nearestFormat 1955
#define sipName_nearestFormat &sipStrings_QtMultimedia[1955]
#define sipNameNr_QPixmapHandle 1969
#define sipName_QPixmapHandle &sipStrings_QtMultimedia[1969]
#define sipNameNr_transformMode 1983
#define sipName_transformMode &sipStrings_QtMultimedia[1983]
#define sipNameNr_Format_RGB555 1997
#define sipName_Format_RGB555 &sipStrings_QtMultimedia[1997]
#define sipNameNr_Format_ARGB32 2011
#define sipName_Format_ARGB32 &sipStrings_QtMultimedia[2011]
#define sipNameNr_ResourceError 2025
#define sipName_ResourceError &sipStrings_QtMultimedia[2025]
#define sipNameNr_connectNotify 1361
#define sipName_connectNotify &sipStrings_QtMultimedia[1361]
#define sipNameNr_setFrameRate 2039
#define sipName_setFrameRate &sipStrings_QtMultimedia[2039]
#define sipNameNr_setFrameSize 2052
#define sipName_setFrameSize &sipStrings_QtMultimedia[2052]
#define sipNameNr_setStartTime 2065
#define sipName_setStartTime &sipStrings_QtMultimedia[2065]
#define sipNameNr_setFieldType 2078
#define sipName_setFieldType &sipStrings_QtMultimedia[2078]
#define sipNameNr_Format_BGR24 2091
#define sipName_Format_BGR24 &sipStrings_QtMultimedia[2091]
#define sipNameNr_Format_BGR32 2104
#define sipName_Format_BGR32 &sipStrings_QtMultimedia[2104]
#define sipNameNr_Format_RGB24 2117
#define sipName_Format_RGB24 &sipStrings_QtMultimedia[2117]
#define sipNameNr_QAudioOutput 2130
#define sipName_QAudioOutput &sipStrings_QtMultimedia[2130]
#define sipNameNr_elapsedUSecs 2143
#define sipName_elapsedUSecs &sipStrings_QtMultimedia[2143]
#define sipNameNr_channelCount 2156
#define sipName_channelCount &sipStrings_QtMultimedia[2156]
#define sipNameNr_QAudioFormat 2169
#define sipName_QAudioFormat &sipStrings_QtMultimedia[2169]
#define sipNameNr_QAudio__Mode 2182
#define sipName_QAudio__Mode &sipStrings_QtMultimedia[2182]
#define sipNameNr_StoppedState 2195
#define sipName_StoppedState &sipStrings_QtMultimedia[2195]
#define sipNameNr_StoppedError 2208
#define sipName_StoppedError &sipStrings_QtMultimedia[2208]
#define sipNameNr_sourceRegion 2221
#define sipName_sourceRegion &sipStrings_QtMultimedia[2221]
#define sipNameNr_targetOffset 2234
#define sipName_targetOffset &sipStrings_QtMultimedia[2234]
#define sipNameNr_bytesPerLine 2247
#define sipName_bytesPerLine &sipStrings_QtMultimedia[2247]
#define sipNameNr_Format_RGB32 2260
#define sipName_Format_RGB32 &sipStrings_QtMultimedia[2260]
#define sipNameNr_boundingRect 2273
#define sipName_boundingRect &sipStrings_QtMultimedia[2273]
#define sipNameNr_midLineWidth 2286
#define sipName_midLineWidth &sipStrings_QtMultimedia[2286]
#define sipNameNr_setByteOrder 2299
#define sipName_setByteOrder &sipStrings_QtMultimedia[2299]
#define sipNameNr_stateChanged 2312
#define sipName_stateChanged &sipStrings_QtMultimedia[2312]
#define sipNameNr_LittleEndian 2325
#define sipName_LittleEndian &sipStrings_QtMultimedia[2325]
#define sipNameNr_frameHeight 2338
#define sipName_frameHeight &sipStrings_QtMultimedia[2338]
#define sipNameNr_YCbCr_BT709 2350
#define sipName_YCbCr_BT709 &sipStrings_QtMultimedia[2350]
#define sipNameNr_YCbCr_BT601 2362
#define sipName_YCbCr_BT601 &sipStrings_QtMultimedia[2362]
#define sipNameNr_setMetaData 2374
#define sipName_setMetaData &sipStrings_QtMultimedia[2374]
#define sipNameNr_mappedBytes 2386
#define sipName_mappedBytes &sipStrings_QtMultimedia[2386]
#define sipNameNr_pixelFormat 2398
#define sipName_pixelFormat &sipStrings_QtMultimedia[2398]
#define sipNameNr_Format_User 2410
#define sipName_Format_User &sipStrings_QtMultimedia[2410]
#define sipNameNr_Format_Jpeg 2422
#define sipName_Format_Jpeg &sipStrings_QtMultimedia[2422]
#define sipNameNr_Format_IMC4 2434
#define sipName_Format_IMC4 &sipStrings_QtMultimedia[2434]
#define sipNameNr_Format_IMC3 2446
#define sipName_Format_IMC3 &sipStrings_QtMultimedia[2446]
#define sipNameNr_Format_IMC2 2458
#define sipName_Format_IMC2 &sipStrings_QtMultimedia[2458]
#define sipNameNr_Format_IMC1 2470
#define sipName_Format_IMC1 &sipStrings_QtMultimedia[2470]
#define sipNameNr_Format_NV21 2482
#define sipName_Format_NV21 &sipStrings_QtMultimedia[2482]
#define sipNameNr_Format_NV12 2494
#define sipName_Format_NV12 &sipStrings_QtMultimedia[2494]
#define sipNameNr_Format_YUYV 2506
#define sipName_Format_YUYV &sipStrings_QtMultimedia[2506]
#define sipNameNr_Format_UYVY 2518
#define sipName_Format_UYVY &sipStrings_QtMultimedia[2518]
#define sipNameNr_Format_YV12 2530
#define sipName_Format_YV12 &sipStrings_QtMultimedia[2530]
#define sipNameNr_PixelFormat 441
#define sipName_PixelFormat &sipStrings_QtMultimedia[441]
#define sipNameNr_BottomField 2542
#define sipName_BottomField &sipStrings_QtMultimedia[2542]
#define sipNameNr_QVideoFrame 2554
#define sipName_QVideoFrame &sipStrings_QtMultimedia[2554]
#define sipNameNr_setCategory 2566
#define sipName_setCategory &sipStrings_QtMultimedia[2566]
#define sipNameNr_QAudioInput 2578
#define sipName_QAudioInput &sipStrings_QtMultimedia[2578]
#define sipNameNr_UnSignedInt 2590
#define sipName_UnSignedInt &sipStrings_QtMultimedia[2590]
#define sipNameNr_AudioOutput 2131
#define sipName_AudioOutput &sipStrings_QtMultimedia[2131]
#define sipNameNr_ActiveState 2602
#define sipName_ActiveState &sipStrings_QtMultimedia[2602]
#define sipNameNr_button2Text 2614
#define sipName_button2Text &sipStrings_QtMultimedia[2614]
#define sipNameNr_button1Text 2626
#define sipName_button1Text &sipStrings_QtMultimedia[2626]
#define sipNameNr_BottomToTop 2638
#define sipName_BottomToTop &sipStrings_QtMultimedia[2638]
#define sipNameNr_TopToBottom 2650
#define sipName_TopToBottom &sipStrings_QtMultimedia[2650]
#define sipNameNr_setViewport 2662
#define sipName_setViewport &sipStrings_QtMultimedia[2662]
#define sipNameNr_customEvent 2674
#define sipName_customEvent &sipStrings_QtMultimedia[2674]
#define sipNameNr_setProperty 2686
#define sipName_setProperty &sipStrings_QtMultimedia[2686]
#define sipNameNr_eventFilter 2698
#define sipName_eventFilter &sipStrings_QtMultimedia[2698]
#define sipNameNr_YCbCr_JPEG 2710
#define sipName_YCbCr_JPEG &sipStrings_QtMultimedia[2710]
#define sipNameNr_setEndTime 2721
#define sipName_setEndTime &sipStrings_QtMultimedia[2721]
#define sipNameNr_Format_Y16 2732
#define sipName_Format_Y16 &sipStrings_QtMultimedia[2732]
#define sipNameNr_periodSize 2743
#define sipName_periodSize &sipStrings_QtMultimedia[2743]
#define sipNameNr_bytesReady 2754
#define sipName_bytesReady &sipStrings_QtMultimedia[2754]
#define sipNameNr_bufferSize 2765
#define sipName_bufferSize &sipStrings_QtMultimedia[2765]
#define sipNameNr_sampleRate 2776
#define sipName_sampleRate &sipStrings_QtMultimedia[2776]
#define sipNameNr_sampleType 2787
#define sipName_sampleType &sipStrings_QtMultimedia[2787]
#define sipNameNr_sampleSize 2798
#define sipName_sampleSize &sipStrings_QtMultimedia[2798]
#define sipNameNr_SampleType 519
#define sipName_SampleType &sipStrings_QtMultimedia[519]
#define sipNameNr_deviceName 2809
#define sipName_deviceName &sipStrings_QtMultimedia[2809]
#define sipNameNr_AudioInput 2579
#define sipName_AudioInput &sipStrings_QtMultimedia[2579]
#define sipNameNr_handleType 2820
#define sipName_handleType &sipStrings_QtMultimedia[2820]
#define sipNameNr_UserHandle 2831
#define sipName_UserHandle &sipStrings_QtMultimedia[2831]
#define sipNameNr_HandleType 59
#define sipName_HandleType &sipStrings_QtMultimedia[59]
#define sipNameNr_frameWidth 2842
#define sipName_frameWidth &sipStrings_QtMultimedia[2842]
#define sipNameNr_fieldwidth 2853
#define sipName_fieldwidth &sipStrings_QtMultimedia[2853]
#define sipNameNr_fieldWidth 2864
#define sipName_fieldWidth &sipStrings_QtMultimedia[2864]
#define sipNameNr_childEvent 2875
#define sipName_childEvent &sipStrings_QtMultimedia[2875]
#define sipNameNr_timerEvent 2886
#define sipName_timerEvent &sipStrings_QtMultimedia[2886]
#define sipNameNr_isWritable 2897
#define sipName_isWritable &sipStrings_QtMultimedia[2897]
#define sipNameNr_FatalError 2908
#define sipName_FatalError &sipStrings_QtMultimedia[2908]
#define sipNameNr_isReadable 2919
#define sipName_isReadable &sipStrings_QtMultimedia[2919]
#define sipNameNr_frameRate 2930
#define sipName_frameRate &sipStrings_QtMultimedia[2930]
#define sipNameNr_startTime 2940
#define sipName_startTime &sipStrings_QtMultimedia[2940]
#define sipNameNr_fieldType 2950
#define sipName_fieldType &sipStrings_QtMultimedia[2950]
#define sipNameNr_Format_Y8 2960
#define sipName_Format_Y8 &sipStrings_QtMultimedia[2960]
#define sipNameNr_FieldType 615
#define sipName_FieldType &sipStrings_QtMultimedia[615]
#define sipNameNr_bytesFree 2970
#define sipName_bytesFree &sipStrings_QtMultimedia[2970]
#define sipNameNr_setVolume 2980
#define sipName_setVolume &sipStrings_QtMultimedia[2980]
#define sipNameNr_SignedInt 2592
#define sipName_SignedInt &sipStrings_QtMultimedia[2592]
#define sipNameNr_IdleState 2990
#define sipName_IdleState &sipStrings_QtMultimedia[2990]
#define sipNameNr_NotMapped 3000
#define sipName_NotMapped &sipStrings_QtMultimedia[3000]
#define sipNameNr_frameSize 3010
#define sipName_frameSize &sipStrings_QtMultimedia[3010]
#define sipNameNr_operation 3020
#define sipName_operation &sipStrings_QtMultimedia[3020]
#define sipNameNr_lineWidth 3030
#define sipName_lineWidth &sipStrings_QtMultimedia[3030]
#define sipNameNr_directory 3040
#define sipName_directory &sipStrings_QtMultimedia[3040]
#define sipNameNr_alignment 3050
#define sipName_alignment &sipStrings_QtMultimedia[3050]
#define sipNameNr_ReadWrite 3060
#define sipName_ReadWrite &sipStrings_QtMultimedia[3060]
#define sipNameNr_WriteOnly 3070
#define sipName_WriteOnly &sipStrings_QtMultimedia[3070]
#define sipNameNr_OpenError 3080
#define sipName_OpenError &sipStrings_QtMultimedia[3080]
#define sipNameNr_byteOrder 3090
#define sipName_byteOrder &sipStrings_QtMultimedia[3090]
#define sipNameNr_precision 3100
#define sipName_precision &sipStrings_QtMultimedia[3100]
#define sipNameNr_Direction 155
#define sipName_Direction &sipStrings_QtMultimedia[155]
#define sipNameNr_BigEndian 3110
#define sipName_BigEndian &sipStrings_QtMultimedia[3110]
#define sipNameNr_metaData 3120
#define sipName_metaData &sipStrings_QtMultimedia[3120]
#define sipNameNr_isMapped 3129
#define sipName_isMapped &sipStrings_QtMultimedia[3129]
#define sipNameNr_TopField 3138
#define sipName_TopField &sipStrings_QtMultimedia[3138]
#define sipNameNr_setError 3147
#define sipName_setError &sipStrings_QtMultimedia[3147]
#define sipNameNr_NoHandle 3156
#define sipName_NoHandle &sipStrings_QtMultimedia[3156]
#define sipNameNr_fillRule 3165
#define sipName_fillRule &sipStrings_QtMultimedia[3165]
#define sipNameNr_tabArray 3174
#define sipName_tabArray &sipStrings_QtMultimedia[3174]
#define sipNameNr_tabStops 3183
#define sipName_tabStops &sipStrings_QtMultimedia[3183]
#define sipNameNr_userData 3192
#define sipName_userData &sipStrings_QtMultimedia[3192]
#define sipNameNr_viewport 3201
#define sipName_viewport &sipStrings_QtMultimedia[3201]
#define sipNameNr_sizeHint 3210
#define sipName_sizeHint &sipStrings_QtMultimedia[3210]
#define sipNameNr_shortcut 3219
#define sipName_shortcut &sipStrings_QtMultimedia[3219]
#define sipNameNr_setCodec 3228
#define sipName_setCodec &sipStrings_QtMultimedia[3228]
#define sipNameNr_behavior 3237
#define sipName_behavior &sipStrings_QtMultimedia[3237]
#define sipNameNr_position 3246
#define sipName_position &sipStrings_QtMultimedia[3246]
#define sipNameNr_fillChar 3255
#define sipName_fillChar &sipStrings_QtMultimedia[3255]
#define sipNameNr_property 3264
#define sipName_property &sipStrings_QtMultimedia[3264]
#define sipNameNr_ReadOnly 3273
#define sipName_ReadOnly &sipStrings_QtMultimedia[3273]
#define sipNameNr_encoding 3282
#define sipName_encoding &sipStrings_QtMultimedia[3282]
#define sipNameNr_category 3291
#define sipName_category &sipStrings_QtMultimedia[3291]
#define sipNameNr_isActive 3300
#define sipName_isActive &sipStrings_QtMultimedia[3300]
#define sipNameNr_endTime 3309
#define sipName_endTime &sipStrings_QtMultimedia[3309]
#define sipNameNr_suspend 3317
#define sipName_suspend &sipStrings_QtMultimedia[3317]
#define sipNameNr_IOError 3325
#define sipName_IOError &sipStrings_QtMultimedia[3325]
#define sipNameNr_present 3333
#define sipName_present &sipStrings_QtMultimedia[3333]
#define sipNameNr_mapMode 3341
#define sipName_mapMode &sipStrings_QtMultimedia[3341]
#define sipNameNr_MapMode 217
#define sipName_MapMode &sipStrings_QtMultimedia[217]
#define sipNameNr_Unknown 3349
#define sipName_Unknown &sipStrings_QtMultimedia[3349]
#define sipNameNr_exposed 3357
#define sipName_exposed &sipStrings_QtMultimedia[3357]
#define sipNameNr_button2 3365
#define sipName_button2 &sipStrings_QtMultimedia[3365]
#define sipNameNr_button1 3373
#define sipName_button1 &sipStrings_QtMultimedia[3373]
#define sipNameNr_quality 3381
#define sipName_quality &sipStrings_QtMultimedia[3381]
#define sipNameNr_yMargin 3389
#define sipName_yMargin &sipStrings_QtMultimedia[3389]
#define sipNameNr_xMargin 3397
#define sipName_xMargin &sipStrings_QtMultimedia[3397]
#define sipNameNr_caption 3405
#define sipName_caption &sipStrings_QtMultimedia[3405]
#define sipNameNr_release 3413
#define sipName_release &sipStrings_QtMultimedia[3413]
#define sipNameNr_options 3421
#define sipName_options &sipStrings_QtMultimedia[3421]
#define sipNameNr_NoError 3429
#define sipName_NoError &sipStrings_QtMultimedia[3429]
#define sipNameNr_isValid 3437
#define sipName_isValid &sipStrings_QtMultimedia[3437]
#define sipNameNr_filters 3445
#define sipName_filters &sipStrings_QtMultimedia[3445]
#define sipNameNr_volume 3453
#define sipName_volume &sipStrings_QtMultimedia[3453]
#define sipNameNr_QAudio 3460
#define sipName_QAudio &sipStrings_QtMultimedia[3460]
#define sipNameNr_yRound 3467
#define sipName_yRound &sipStrings_QtMultimedia[3467]
#define sipNameNr_xRound 3474
#define sipName_xRound &sipStrings_QtMultimedia[3474]
#define sipNameNr_layers 3481
#define sipName_layers &sipStrings_QtMultimedia[3481]
#define sipNameNr_sunken 3488
#define sipName_sunken &sipStrings_QtMultimedia[3488]
#define sipNameNr_option 3495
#define sipName_option &sipStrings_QtMultimedia[3495]
#define sipNameNr_height 3502
#define sipName_height &sipStrings_QtMultimedia[3502]
#define sipNameNr_proper 3509
#define sipName_proper &sipStrings_QtMultimedia[3509]
#define sipNameNr_value9 3516
#define sipName_value9 &sipStrings_QtMultimedia[3516]
#define sipNameNr_value8 3523
#define sipName_value8 &sipStrings_QtMultimedia[3523]
#define sipNameNr_value7 3530
#define sipName_value7 &sipStrings_QtMultimedia[3530]
#define sipNameNr_value6 3537
#define sipName_value6 &sipStrings_QtMultimedia[3537]
#define sipNameNr_value5 3544
#define sipName_value5 &sipStrings_QtMultimedia[3544]
#define sipNameNr_value4 3551
#define sipName_value4 &sipStrings_QtMultimedia[3551]
#define sipNameNr_value3 3558
#define sipName_value3 &sipStrings_QtMultimedia[3558]
#define sipNameNr_value2 3565
#define sipName_value2 &sipStrings_QtMultimedia[3565]
#define sipNameNr_value1 3572
#define sipName_value1 &sipStrings_QtMultimedia[3572]
#define sipNameNr_value0 3579
#define sipName_value0 &sipStrings_QtMultimedia[3579]
#define sipNameNr_symbol 3586
#define sipName_symbol &sipStrings_QtMultimedia[3586]
#define sipNameNr_suffix 3593
#define sipName_suffix &sipStrings_QtMultimedia[3593]
#define sipNameNr_handle 3600
#define sipName_handle &sipStrings_QtMultimedia[3600]
#define sipNameNr_prefix 3607
#define sipName_prefix &sipStrings_QtMultimedia[3607]
#define sipNameNr_notify 3614
#define sipName_notify &sipStrings_QtMultimedia[3614]
#define sipNameNr_format 3621
#define sipName_format &sipStrings_QtMultimedia[3621]
#define sipNameNr_isNull 3628
#define sipName_isNull &sipStrings_QtMultimedia[3628]
#define sipNameNr_column 3635
#define sipName_column &sipStrings_QtMultimedia[3635]
#define sipNameNr_filter 3642
#define sipName_filter &sipStrings_QtMultimedia[3642]
#define sipNameNr_resume 3649
#define sipName_resume &sipStrings_QtMultimedia[3649]
#define sipNameNr_parent 3656
#define sipName_parent &sipStrings_QtMultimedia[3656]
#define sipNameNr___ne__ 3663
#define sipName___ne__ &sipStrings_QtMultimedia[3663]
#define sipNameNr___eq__ 3670
#define sipName___eq__ &sipStrings_QtMultimedia[3670]
#define sipNameNr_Endian 750
#define sipName_Endian &sipStrings_QtMultimedia[750]
#define sipNameNr_brush 3677
#define sipName_brush &sipStrings_QtMultimedia[3677]
#define sipNameNr_Error 307
#define sipName_Error &sipStrings_QtMultimedia[307]
#define sipNameNr_codec 3683
#define sipName_codec &sipStrings_QtMultimedia[3683]
#define sipNameNr_Float 3689
#define sipName_Float &sipStrings_QtMultimedia[3689]
#define sipNameNr_unmap 3695
#define sipName_unmap &sipStrings_QtMultimedia[3695]
#define sipNameNr_width 2858
#define sipName_width &sipStrings_QtMultimedia[2858]
#define sipNameNr_reset 3701
#define sipName_reset &sipStrings_QtMultimedia[3701]
#define sipNameNr_order 3707
#define sipName_order &sipStrings_QtMultimedia[3707]
#define sipNameNr_error 3713
#define sipName_error &sipStrings_QtMultimedia[3713]
#define sipNameNr_flags 3719
#define sipName_flags &sipStrings_QtMultimedia[3719]
#define sipNameNr_event 3725
#define sipName_event &sipStrings_QtMultimedia[3725]
#define sipNameNr_msecs 3731
#define sipName_msecs &sipStrings_QtMultimedia[3731]
#define sipNameNr_start 3737
#define sipName_start &sipStrings_QtMultimedia[3737]
#define sipNameNr_state 3743
#define sipName_state &sipStrings_QtMultimedia[3743]
#define sipNameNr_State 1680
#define sipName_State &sipStrings_QtMultimedia[1680]
#define sipNameNr_Mode 220
#define sipName_Mode &sipStrings_QtMultimedia[220]
#define sipNameNr_bits 3749
#define sipName_bits &sipStrings_QtMultimedia[3749]
#define sipNameNr_mode 3754
#define sipName_mode &sipStrings_QtMultimedia[3754]
#define sipNameNr_name 3759
#define sipName_name &sipStrings_QtMultimedia[3759]
#define sipNameNr_base 3764
#define sipName_base &sipStrings_QtMultimedia[3764]
#define sipNameNr_fill 3769
#define sipName_fill &sipStrings_QtMultimedia[3769]
#define sipNameNr_from 3774
#define sipName_from &sipStrings_QtMultimedia[3774]
#define sipNameNr_sort 3779
#define sipName_sort &sipStrings_QtMultimedia[3779]
#define sipNameNr_type 3784
#define sipName_type &sipStrings_QtMultimedia[3784]
#define sipNameNr_size 3789
#define sipName_size &sipStrings_QtMultimedia[3789]
#define sipNameNr_stop 3794
#define sipName_stop &sipStrings_QtMultimedia[3794]
#define sipNameNr_pen 3799
#define sipName_pen &sipStrings_QtMultimedia[3799]
#define sipNameNr_map 3697
#define sipName_map &sipStrings_QtMultimedia[3697]
#define sipNameNr_end 3321
#define sipName_end &sipStrings_QtMultimedia[3321]
#define sipNameNr_pos 3803
#define sipName_pos &sipStrings_QtMultimedia[3803]
#define sipNameNr_sw 3807
#define sipName_sw &sipStrings_QtMultimedia[3807]
#define sipNameNr_sy 3810
#define sipName_sy &sipStrings_QtMultimedia[3810]
#define sipNameNr_sx 3813
#define sipName_sx &sipStrings_QtMultimedia[3813]
#define sipNameNr_sh 3680
#define sipName_sh &sipStrings_QtMultimedia[3680]
#define sipNameNr_cs 1468
#define sipName_cs &sipStrings_QtMultimedia[1468]
#define sipNameNr_at 450
#define sipName_at &sipStrings_QtMultimedia[450]

#define sipMalloc                   sipAPI_QtMultimedia->api_malloc
#define sipFree                     sipAPI_QtMultimedia->api_free
#define sipBuildResult              sipAPI_QtMultimedia->api_build_result
#define sipCallMethod               sipAPI_QtMultimedia->api_call_method
#define sipCallProcedureMethod      sipAPI_QtMultimedia->api_call_procedure_method
#define sipCallErrorHandler         sipAPI_QtMultimedia->api_call_error_handler
#define sipParseResultEx            sipAPI_QtMultimedia->api_parse_result_ex
#define sipParseResult              sipAPI_QtMultimedia->api_parse_result
#define sipParseArgs                sipAPI_QtMultimedia->api_parse_args
#define sipParseKwdArgs             sipAPI_QtMultimedia->api_parse_kwd_args
#define sipParsePair                sipAPI_QtMultimedia->api_parse_pair
#define sipInstanceDestroyed        sipAPI_QtMultimedia->api_instance_destroyed
#define sipInstanceDestroyedEx      sipAPI_QtMultimedia->api_instance_destroyed_ex
#define sipConvertFromSequenceIndex sipAPI_QtMultimedia->api_convert_from_sequence_index
#define sipConvertFromVoidPtr       sipAPI_QtMultimedia->api_convert_from_void_ptr
#define sipConvertToVoidPtr         sipAPI_QtMultimedia->api_convert_to_void_ptr
#define sipAddException             sipAPI_QtMultimedia->api_add_exception
#define sipNoFunction               sipAPI_QtMultimedia->api_no_function
#define sipNoMethod                 sipAPI_QtMultimedia->api_no_method
#define sipAbstractMethod           sipAPI_QtMultimedia->api_abstract_method
#define sipBadClass                 sipAPI_QtMultimedia->api_bad_class
#define sipBadCatcherResult         sipAPI_QtMultimedia->api_bad_catcher_result
#define sipBadCallableArg           sipAPI_QtMultimedia->api_bad_callable_arg
#define sipBadOperatorArg           sipAPI_QtMultimedia->api_bad_operator_arg
#define sipTrace                    sipAPI_QtMultimedia->api_trace
#define sipTransferBack             sipAPI_QtMultimedia->api_transfer_back
#define sipTransferTo               sipAPI_QtMultimedia->api_transfer_to
#define sipTransferBreak            sipAPI_QtMultimedia->api_transfer_break
#define sipSimpleWrapper_Type       sipAPI_QtMultimedia->api_simplewrapper_type
#define sipWrapper_Type             sipAPI_QtMultimedia->api_wrapper_type
#define sipWrapperType_Type         sipAPI_QtMultimedia->api_wrappertype_type
#define sipVoidPtr_Type             sipAPI_QtMultimedia->api_voidptr_type
#define sipGetPyObject              sipAPI_QtMultimedia->api_get_pyobject
#define sipGetAddress               sipAPI_QtMultimedia->api_get_address
#define sipGetMixinAddress          sipAPI_QtMultimedia->api_get_mixin_address
#define sipGetCppPtr                sipAPI_QtMultimedia->api_get_cpp_ptr
#define sipGetComplexCppPtr         sipAPI_QtMultimedia->api_get_complex_cpp_ptr
#define sipIsPyMethod               sipAPI_QtMultimedia->api_is_py_method
#define sipCallHook                 sipAPI_QtMultimedia->api_call_hook
#define sipEndThread                sipAPI_QtMultimedia->api_end_thread
#define sipConnectRx                sipAPI_QtMultimedia->api_connect_rx
#define sipDisconnectRx             sipAPI_QtMultimedia->api_disconnect_rx
#define sipRaiseUnknownException    sipAPI_QtMultimedia->api_raise_unknown_exception
#define sipRaiseTypeException       sipAPI_QtMultimedia->api_raise_type_exception
#define sipBadLengthForSlice        sipAPI_QtMultimedia->api_bad_length_for_slice
#define sipAddTypeInstance          sipAPI_QtMultimedia->api_add_type_instance
#define sipFreeSipslot              sipAPI_QtMultimedia->api_free_sipslot
#define sipSameSlot                 sipAPI_QtMultimedia->api_same_slot
#define sipPySlotExtend             sipAPI_QtMultimedia->api_pyslot_extend
#define sipConvertRx                sipAPI_QtMultimedia->api_convert_rx
#define sipAddDelayedDtor           sipAPI_QtMultimedia->api_add_delayed_dtor
#define sipCanConvertToType         sipAPI_QtMultimedia->api_can_convert_to_type
#define sipConvertToType            sipAPI_QtMultimedia->api_convert_to_type
#define sipForceConvertToType       sipAPI_QtMultimedia->api_force_convert_to_type
#define sipCanConvertToEnum         sipAPI_QtMultimedia->api_can_convert_to_enum
#define sipConvertToEnum            sipAPI_QtMultimedia->api_convert_to_enum
#define sipConvertToBool            sipAPI_QtMultimedia->api_convert_to_bool
#define sipReleaseType              sipAPI_QtMultimedia->api_release_type
#define sipConvertFromType          sipAPI_QtMultimedia->api_convert_from_type
#define sipConvertFromNewType       sipAPI_QtMultimedia->api_convert_from_new_type
#define sipConvertFromNewPyType     sipAPI_QtMultimedia->api_convert_from_new_pytype
#define sipConvertFromEnum          sipAPI_QtMultimedia->api_convert_from_enum
#define sipGetState                 sipAPI_QtMultimedia->api_get_state
#define sipExportSymbol             sipAPI_QtMultimedia->api_export_symbol
#define sipImportSymbol             sipAPI_QtMultimedia->api_import_symbol
#define sipFindType                 sipAPI_QtMultimedia->api_find_type
#define sipFindNamedEnum            sipAPI_QtMultimedia->api_find_named_enum
#define sipBytes_AsChar             sipAPI_QtMultimedia->api_bytes_as_char
#define sipBytes_AsString           sipAPI_QtMultimedia->api_bytes_as_string
#define sipString_AsASCIIChar       sipAPI_QtMultimedia->api_string_as_ascii_char
#define sipString_AsASCIIString     sipAPI_QtMultimedia->api_string_as_ascii_string
#define sipString_AsLatin1Char      sipAPI_QtMultimedia->api_string_as_latin1_char
#define sipString_AsLatin1String    sipAPI_QtMultimedia->api_string_as_latin1_string
#define sipString_AsUTF8Char        sipAPI_QtMultimedia->api_string_as_utf8_char
#define sipString_AsUTF8String      sipAPI_QtMultimedia->api_string_as_utf8_string
#define sipUnicode_AsWChar          sipAPI_QtMultimedia->api_unicode_as_wchar
#define sipUnicode_AsWString        sipAPI_QtMultimedia->api_unicode_as_wstring
#define sipConvertFromConstVoidPtr  sipAPI_QtMultimedia->api_convert_from_const_void_ptr
#define sipConvertFromVoidPtrAndSize    sipAPI_QtMultimedia->api_convert_from_void_ptr_and_size
#define sipConvertFromConstVoidPtrAndSize   sipAPI_QtMultimedia->api_convert_from_const_void_ptr_and_size
#define sipInvokeSlot               sipAPI_QtMultimedia->api_invoke_slot
#define sipInvokeSlotEx             sipAPI_QtMultimedia->api_invoke_slot_ex
#define sipSaveSlot                 sipAPI_QtMultimedia->api_save_slot
#define sipClearAnySlotReference    sipAPI_QtMultimedia->api_clear_any_slot_reference
#define sipVisitSlot                sipAPI_QtMultimedia->api_visit_slot
#define sipWrappedTypeName(wt)      ((wt)->wt_td->td_cname)
#define sipDeprecated               sipAPI_QtMultimedia->api_deprecated
#define sipGetReference             sipAPI_QtMultimedia->api_get_reference
#define sipKeepReference            sipAPI_QtMultimedia->api_keep_reference
#define sipRegisterProxyResolver    sipAPI_QtMultimedia->api_register_proxy_resolver
#define sipRegisterPyType           sipAPI_QtMultimedia->api_register_py_type
#define sipTypeFromPyTypeObject     sipAPI_QtMultimedia->api_type_from_py_type_object
#define sipTypeScope                sipAPI_QtMultimedia->api_type_scope
#define sipResolveTypedef           sipAPI_QtMultimedia->api_resolve_typedef
#define sipRegisterAttributeGetter  sipAPI_QtMultimedia->api_register_attribute_getter
#define sipIsAPIEnabled             sipAPI_QtMultimedia->api_is_api_enabled
#define sipSetDestroyOnExit         sipAPI_QtMultimedia->api_set_destroy_on_exit
#define sipEnableAutoconversion     sipAPI_QtMultimedia->api_enable_autoconversion
#define sipEnableOverflowChecking   sipAPI_QtMultimedia->api_enable_overflow_checking
#define sipInitMixin                sipAPI_QtMultimedia->api_init_mixin
#define sipExportModule             sipAPI_QtMultimedia->api_export_module
#define sipInitModule               sipAPI_QtMultimedia->api_init_module
#define sipGetInterpreter           sipAPI_QtMultimedia->api_get_interpreter
#define sipSetNewUserTypeHandler    sipAPI_QtMultimedia->api_set_new_user_type_handler
#define sipSetTypeUserData          sipAPI_QtMultimedia->api_set_type_user_data
#define sipGetTypeUserData          sipAPI_QtMultimedia->api_get_type_user_data
#define sipPyTypeDict               sipAPI_QtMultimedia->api_py_type_dict
#define sipPyTypeName               sipAPI_QtMultimedia->api_py_type_name
#define sipGetCFunction             sipAPI_QtMultimedia->api_get_c_function
#define sipGetMethod                sipAPI_QtMultimedia->api_get_method
#define sipFromMethod               sipAPI_QtMultimedia->api_from_method
#define sipGetDate                  sipAPI_QtMultimedia->api_get_date
#define sipFromDate                 sipAPI_QtMultimedia->api_from_date
#define sipGetDateTime              sipAPI_QtMultimedia->api_get_datetime
#define sipFromDateTime             sipAPI_QtMultimedia->api_from_datetime
#define sipGetTime                  sipAPI_QtMultimedia->api_get_time
#define sipFromTime                 sipAPI_QtMultimedia->api_from_time
#define sipIsUserType               sipAPI_QtMultimedia->api_is_user_type
#define sipGetFrame                 sipAPI_QtMultimedia->api_get_frame
#define sipCheckPluginForType       sipAPI_QtMultimedia->api_check_plugin_for_type
#define sipUnicodeNew               sipAPI_QtMultimedia->api_unicode_new
#define sipUnicodeWrite             sipAPI_QtMultimedia->api_unicode_write
#define sipUnicodeData              sipAPI_QtMultimedia->api_unicode_data
#define sipGetBufferInfo            sipAPI_QtMultimedia->api_get_buffer_info
#define sipReleaseBufferInfo        sipAPI_QtMultimedia->api_release_buffer_info
#define sipIsOwnedByPython          sipAPI_QtMultimedia->api_is_owned_by_python
#define sipIsDerivedClass           sipAPI_QtMultimedia->api_is_derived_class
#define sipGetUserObject            sipAPI_QtMultimedia->api_get_user_object
#define sipSetUserObject            sipAPI_QtMultimedia->api_set_user_object
#define sipRegisterEventHandler     sipAPI_QtMultimedia->api_register_event_handler
#define sipLong_AsChar              sipAPI_QtMultimedia->api_long_as_char
#define sipLong_AsSignedChar        sipAPI_QtMultimedia->api_long_as_signed_char
#define sipLong_AsUnsignedChar      sipAPI_QtMultimedia->api_long_as_unsigned_char
#define sipLong_AsShort             sipAPI_QtMultimedia->api_long_as_short
#define sipLong_AsUnsignedShort     sipAPI_QtMultimedia->api_long_as_unsigned_short
#define sipLong_AsInt               sipAPI_QtMultimedia->api_long_as_int
#define sipLong_AsUnsignedInt       sipAPI_QtMultimedia->api_long_as_unsigned_int
#define sipLong_AsLong              sipAPI_QtMultimedia->api_long_as_long
#define sipLong_AsUnsignedLong      sipAPI_QtMultimedia->api_long_as_unsigned_long
#define sipLong_AsLongLong          sipAPI_QtMultimedia->api_long_as_long_long
#define sipLong_AsUnsignedLongLong  sipAPI_QtMultimedia->api_long_as_unsigned_long_long

/* These are deprecated. */
#define sipMapStringToClass         sipAPI_QtMultimedia->api_map_string_to_class
#define sipMapIntToClass            sipAPI_QtMultimedia->api_map_int_to_class
#define sipFindClass                sipAPI_QtMultimedia->api_find_class
#define sipFindMappedType           sipAPI_QtMultimedia->api_find_mapped_type
#define sipConvertToArray           sipAPI_QtMultimedia->api_convert_to_array
#define sipConvertToTypedArray      sipAPI_QtMultimedia->api_convert_to_typed_array
#define sipEnableGC                 sipAPI_QtMultimedia->api_enable_gc
#define sipPrintObject              sipAPI_QtMultimedia->api_print_object
#define sipWrapper_Check(w)         PyObject_TypeCheck((w), sipAPI_QtMultimedia->api_wrapper_type)
#define sipGetWrapper(p, wt)        sipGetPyObject((p), (wt)->wt_td)
#define sipReleaseInstance(p, wt, s)    sipReleaseType((p), (wt)->wt_td, (s))
#define sipReleaseMappedType        sipReleaseType
#define sipCanConvertToInstance(o, wt, f)   sipCanConvertToType((o), (wt)->wt_td, (f))
#define sipCanConvertToMappedType   sipCanConvertToType
#define sipConvertToInstance(o, wt, t, f, s, e)     sipConvertToType((o), (wt)->wt_td, (t), (f), (s), (e))
#define sipConvertToMappedType      sipConvertToType
#define sipForceConvertToInstance(o, wt, t, f, s, e)    sipForceConvertToType((o), (wt)->wt_td, (t), (f), (s), (e))
#define sipForceConvertToMappedType sipForceConvertToType
#define sipConvertFromInstance(p, wt, t)    sipConvertFromType((p), (wt)->wt_td, (t))
#define sipConvertFromMappedType    sipConvertFromType
#define sipConvertFromNamedEnum(v, pt)  sipConvertFromEnum((v), ((sipEnumTypeObject *)(pt))->type)
#define sipConvertFromNewInstance(p, wt, t) sipConvertFromNewType((p), (wt)->wt_td, (t))

/* The strings used by this module. */
extern const char sipStrings_QtMultimedia[];

#define sipType_QAbstractVideoBuffer sipExportedTypes_QtMultimedia[0]
#define sipClass_QAbstractVideoBuffer sipExportedTypes_QtMultimedia[0]->u.td_wrapper_type

#define sipType_QAbstractVideoBuffer_MapMode sipExportedTypes_QtMultimedia[2]
#define sipEnum_QAbstractVideoBuffer_MapMode sipExportedTypes_QtMultimedia[2]->u.td_py_type

#define sipType_QAbstractVideoBuffer_HandleType sipExportedTypes_QtMultimedia[1]
#define sipEnum_QAbstractVideoBuffer_HandleType sipExportedTypes_QtMultimedia[1]->u.td_py_type

extern sipClassTypeDef sipTypeDef_QtMultimedia_QAbstractVideoBuffer;

#define sipType_QAbstractVideoSurface sipExportedTypes_QtMultimedia[3]
#define sipClass_QAbstractVideoSurface sipExportedTypes_QtMultimedia[3]->u.td_wrapper_type

#define sipType_QAbstractVideoSurface_Error sipExportedTypes_QtMultimedia[4]
#define sipEnum_QAbstractVideoSurface_Error sipExportedTypes_QtMultimedia[4]->u.td_py_type

extern sipClassTypeDef sipTypeDef_QtMultimedia_QAbstractVideoSurface;

#define sipType_QAudio sipExportedTypes_QtMultimedia[5]
#define sipClass_QAudio sipExportedTypes_QtMultimedia[5]->u.td_wrapper_type

#define sipType_QAudio_Mode sipExportedTypes_QtMultimedia[7]
#define sipEnum_QAudio_Mode sipExportedTypes_QtMultimedia[7]->u.td_py_type

#define sipType_QAudio_State sipExportedTypes_QtMultimedia[8]
#define sipEnum_QAudio_State sipExportedTypes_QtMultimedia[8]->u.td_py_type

#define sipType_QAudio_Error sipExportedTypes_QtMultimedia[6]
#define sipEnum_QAudio_Error sipExportedTypes_QtMultimedia[6]->u.td_py_type

extern sipClassTypeDef sipTypeDef_QtMultimedia_QAudio;

#define sipType_QAudioDeviceInfo sipExportedTypes_QtMultimedia[9]
#define sipClass_QAudioDeviceInfo sipExportedTypes_QtMultimedia[9]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtMultimedia_QAudioDeviceInfo;

#define sipType_QAudioFormat sipExportedTypes_QtMultimedia[10]
#define sipClass_QAudioFormat sipExportedTypes_QtMultimedia[10]->u.td_wrapper_type

#define sipType_QAudioFormat_Endian sipExportedTypes_QtMultimedia[11]
#define sipEnum_QAudioFormat_Endian sipExportedTypes_QtMultimedia[11]->u.td_py_type

#define sipType_QAudioFormat_SampleType sipExportedTypes_QtMultimedia[12]
#define sipEnum_QAudioFormat_SampleType sipExportedTypes_QtMultimedia[12]->u.td_py_type

extern sipClassTypeDef sipTypeDef_QtMultimedia_QAudioFormat;

#define sipType_QAudioInput sipExportedTypes_QtMultimedia[13]
#define sipClass_QAudioInput sipExportedTypes_QtMultimedia[13]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtMultimedia_QAudioInput;

#define sipType_QAudioOutput sipExportedTypes_QtMultimedia[14]
#define sipClass_QAudioOutput sipExportedTypes_QtMultimedia[14]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtMultimedia_QAudioOutput;

#define sipType_QVideoFrame sipExportedTypes_QtMultimedia[19]
#define sipClass_QVideoFrame sipExportedTypes_QtMultimedia[19]->u.td_wrapper_type

#define sipType_QVideoFrame_PixelFormat sipExportedTypes_QtMultimedia[21]
#define sipEnum_QVideoFrame_PixelFormat sipExportedTypes_QtMultimedia[21]->u.td_py_type

#define sipType_QVideoFrame_FieldType sipExportedTypes_QtMultimedia[20]
#define sipEnum_QVideoFrame_FieldType sipExportedTypes_QtMultimedia[20]->u.td_py_type

extern sipClassTypeDef sipTypeDef_QtMultimedia_QVideoFrame;

#define sipType_QVideoSurfaceFormat sipExportedTypes_QtMultimedia[22]
#define sipClass_QVideoSurfaceFormat sipExportedTypes_QtMultimedia[22]->u.td_wrapper_type

#define sipType_QVideoSurfaceFormat_YCbCrColorSpace sipExportedTypes_QtMultimedia[24]
#define sipEnum_QVideoSurfaceFormat_YCbCrColorSpace sipExportedTypes_QtMultimedia[24]->u.td_py_type

#define sipType_QVideoSurfaceFormat_Direction sipExportedTypes_QtMultimedia[23]
#define sipEnum_QVideoSurfaceFormat_Direction sipExportedTypes_QtMultimedia[23]->u.td_py_type

extern sipClassTypeDef sipTypeDef_QtMultimedia_QVideoSurfaceFormat;

#define sipType_QList_0100QAudioDeviceInfo sipExportedTypes_QtMultimedia[15]

extern sipMappedTypeDef sipTypeDef_QtMultimedia_QList_0100QAudioDeviceInfo;

#define sipType_QList_0100QVideoFrame_PixelFormat sipExportedTypes_QtMultimedia[18]

extern sipMappedTypeDef sipTypeDef_QtMultimedia_QList_0100QVideoFrame_PixelFormat;

#define sipType_QList_0100QAudioFormat_SampleType sipExportedTypes_QtMultimedia[17]

extern sipMappedTypeDef sipTypeDef_QtMultimedia_QList_0100QAudioFormat_SampleType;

#define sipType_QList_0100QAudioFormat_Endian sipExportedTypes_QtMultimedia[16]

extern sipMappedTypeDef sipTypeDef_QtMultimedia_QList_0100QAudioFormat_Endian;

/* The SIP API, this module's API and the APIs of any imported modules. */
extern const sipAPIDef *sipAPI_QtMultimedia;
extern sipExportedModuleDef sipModuleAPI_QtMultimedia;
extern sipTypeDef *sipExportedTypes_QtMultimedia[];

#define sipType_QObject sipImportedTypes_QtMultimedia_QtCore[7].it_td
#define sipClass_QObject sipImportedTypes_QtMultimedia_QtCore[7].it_td->u.td_wrapper_type

#define sipType_QIODevice sipImportedTypes_QtMultimedia_QtCore[2].it_td
#define sipClass_QIODevice sipImportedTypes_QtMultimedia_QtCore[2].it_td->u.td_wrapper_type

#define sipType_QEvent sipImportedTypes_QtMultimedia_QtCore[1].it_td
#define sipClass_QEvent sipImportedTypes_QtMultimedia_QtCore[1].it_td->u.td_wrapper_type

#define sipType_QTimerEvent sipImportedTypes_QtMultimedia_QtCore[12].it_td
#define sipClass_QTimerEvent sipImportedTypes_QtMultimedia_QtCore[12].it_td->u.td_wrapper_type

#define sipType_QChildEvent sipImportedTypes_QtMultimedia_QtCore[0].it_td
#define sipClass_QChildEvent sipImportedTypes_QtMultimedia_QtCore[0].it_td->u.td_wrapper_type

#define sipType_QMetaMethod sipImportedTypes_QtMultimedia_QtCore[6].it_td
#define sipClass_QMetaMethod sipImportedTypes_QtMultimedia_QtCore[6].it_td->u.td_wrapper_type

#define sipType_QRect sipImportedTypes_QtMultimedia_QtCore[8].it_td
#define sipClass_QRect sipImportedTypes_QtMultimedia_QtCore[8].it_td->u.td_wrapper_type

#define sipType_QSize sipImportedTypes_QtMultimedia_QtCore[9].it_td
#define sipClass_QSize sipImportedTypes_QtMultimedia_QtCore[9].it_td->u.td_wrapper_type

#define sipType_QVariant sipImportedTypes_QtMultimedia_QtCore[13].it_td
#define sipClass_QVariant sipImportedTypes_QtMultimedia_QtCore[13].it_td->u.td_wrapper_type

#define sipType_QList_0100QByteArray sipImportedTypes_QtMultimedia_QtCore[3].it_td

#define sipType_QMap_0100QString_0100QVariant sipImportedTypes_QtMultimedia_QtCore[5].it_td

#define sipType_QStringList sipImportedTypes_QtMultimedia_QtCore[11].it_td

#define sipType_QString sipImportedTypes_QtMultimedia_QtCore[10].it_td

#define sipType_QList_1800 sipImportedTypes_QtMultimedia_QtCore[4].it_td
extern sipImportedTypeDef sipImportedTypes_QtMultimedia_QtCore[];

#define sipType_QImage sipImportedTypes_QtMultimedia_QtGui[0].it_td
#define sipClass_QImage sipImportedTypes_QtMultimedia_QtGui[0].it_td->u.td_wrapper_type

#define sipType_QImage_Format sipImportedTypes_QtMultimedia_QtGui[1].it_td
#define sipEnum_QImage_Format sipImportedTypes_QtMultimedia_QtGui[1].it_td->u.td_py_type
extern sipImportedTypeDef sipImportedTypes_QtMultimedia_QtGui[];

typedef const QMetaObject *(*sip_qt_metaobject_func)(sipSimpleWrapper *,sipTypeDef *);
extern sip_qt_metaobject_func sip_QtMultimedia_qt_metaobject;

typedef int (*sip_qt_metacall_func)(sipSimpleWrapper *,sipTypeDef *,QMetaObject::Call,int,void **);
extern sip_qt_metacall_func sip_QtMultimedia_qt_metacall;

typedef int (*sip_qt_metacast_func)(sipSimpleWrapper *, sipTypeDef *, const char *);
extern sip_qt_metacast_func sip_QtMultimedia_qt_metacast;

#endif
