
all:
	@(cd QtCore; $(MAKE))
	@(cd QtGui; $(MAKE))
	@(cd QtDBus; $(MAKE))
	@(cd QtOpenGL; $(MAKE))

install:
	@(cd QtCore; $(MAKE) install)
	@(cd QtGui; $(MAKE) install)
	@(cd QtDBus; $(MAKE) install)
	@(cd QtOpenGL; $(MAKE) install)

clean:
	@(cd QtCore; $(MAKE) clean)
	@(cd QtGui; $(MAKE) clean)
	@(cd QtDBus; $(MAKE) clean)
	@(cd QtOpenGL; $(MAKE) clean)
